### ISSUE TITLE
Redesign synchronous join API

### ISSUE THREAD

**Issue by sharonovd** [tarantool/cartridge#101]
In GitLab by @rosik on May 14, 2019, 11:18

Now function `join_server` is async by default unless timeout option is specified. Some people think this is unclear and should be changed.

**Comment by sharonovd** [comment]
In GitLab by @rosik on Jul 23, 2019, 13:05

### Design proposal

```lua
join_server({..., async = true/false, timeout = T})
```

### Defaults (to be discussed)

```lua
async = false
timeout = 30
```

### Corner cases

* `async = true` -> `timeout` is ignored
* `async = false, timeout <= 0` -> error
* `async = false, timeout > 0` -> wait until server becomes ready

**Comment by sharonovd** [comment]
In GitLab by @rosik on Jul 23, 2019, 13:06

@mtrempoltsev @racktear what do you think about defaults?

**Comment by sharonovd** [comment]
In GitLab by @rosik on Jul 23, 2019, 13:09

### Current behavior

Nowadays there is only one parameter `timeout`, which is 0 by default.

In terms of proposed API it can be interpreted as follows:

* `timeout <= 0` -> `async = true`
* `timeout > 0` -> `async = false, timeout = timeout`

**Comment by sharonovd** [comment]
In GitLab by @rosik on Jul 23, 2019, 14:19

mentioned in merge request !149

**Comment by rosik** [comment]
Obsolete since grand refactoring of instances lifecycle
