### ISSUE TITLE
[4pt] Cartridge skips two-phase commit if didn't change and says "OK" when it's not

### ISSUE THREAD

**Issue by rosik** [tarantool/cartridge#1046]
Nowadays cartridge behavior upon config upload is the following:

* If it didn't change, `log.warn("Clusterwide config didn't change, skipping")` and `return true` immediately.

Several times we've received questions regarding config upload in WebUI which doesn't reconfigure anything.

It may also play a dirty trick if:

- Some server is in OperationError state
- Some server is completely offline

<details>
  <summary>Abandoned proposal</summary>

So I think, that at least HTTP upload should always trigger fair two-phase commit. And, possibly, other operations too.

My proposal:

- Implement new option: `cartridge.config_patch_clusterwide({}, {never_skip = true})`, default `false`; 
- Make it default for HTTP `PUT /admin/config` (i.e. Configuration Management page in WebUI);
- Make it default for GraphQL `muatation{ cluster{ sections(){} }}` (i.e. Code page in WebUI).
</details>

**Comment by rosik** [comment]
P.S. Skipping two-phase commit was introduced in 2.0.0
P.P.S It's also related to #566

**Comment by filonenko-mikhail** [comment]
Seems useful

**Comment by olegrok** [comment]
My opinion:

> * Implement new option: cartridge.config_patch_clusterwide({}, {never_skip = true}), default false;

Agree. But seems "never" in flag name could lead to misunderstanding. "Never" means that we enable some mode that apply config always. IMO "never" is not appropriate here. Should be "force" similar to box option "force_recovery"

> * Make it default for HTTP PUT /admin/config (i.e. Configuration Management page in WebUI);
> * Make it default for GraphQL muatation{ cluster{ sections(){} }} (i.e. Code page in WebUI).

Warning should be shown. Force apply should be optional.

**Comment by rosik** [comment]
Here's the new plan. With the soon introduction of the upload stage (#1266) we can stop worrying about two-phase commit performance.

The `patch_clusterwide` function shouldn't skip a 2pc upload if nothing changed. Instead, it'll do fair `upload` and `prepare_2pc`. And the `commit_2pc` on every instance can then decide if the instance state is suitable for the `skipping`.
