### ISSUE TITLE
Exposing graphql admin queries/mutations for role even when role does not run on http admin node

### ISSUE THREAD

**Issue by sharonovd** [tarantool/cartridge#105]
In GitLab by @filonenko-mikhail on May 14, 2019, 13:18

Add an API for roles to expose their graphql endpoints in admin

Currently it's impossible to call role's graphql endpoints if one is not located on the same node with the role.

This needs a general solution: a role should declare its graphql endpoints and decide on a strategy how they should be reached, and then those endpoints should be accessible on any node.

**Comment by rosik** [comment]
The solution is the same as for regular http routes - call `graphql.add_callback` for the top level of `myrole.lua`
