### ISSUE TITLE
[2pt] New option to turn off autodiscavery for new nodes via udp

### ISSUE THREAD

**Issue by RepentantGopher** [tarantool/cartridge#1057]
Hello!
We ecnountered the same issue already 3 times when our new devops deployed Tarantool cluster with cartridge via cartridge ansbile in to the same subnet with same same cookie as existing Tarantool cluster.
This issue leads to bugs in existed and new Tarantool clusters.
We don't need autodiscavery feature and i think we should have option to turn off this feature to prevent situations like this in future.

**Comment by rosik** [comment]
Have to be mentioned that this issue has a workaround:

```lua
-- init.lua
local cartridge = require('cartridge')
package.loaded.membership.broadcast = function() end

cartridge.cfg(...)
```
