### ISSUE TITLE
Default role config

### ISSUE THREAD

**Issue by vasiliy-t** [tarantool/cartridge#1067]
### Problem

Sometimes it is convenient to have default role config set directly into init.lua. 

E.g. user creates it's own template and set's default vshard config values to it's own defaults, but could not set any other role defaults from code e.g. metrics or it's own roles.

**Comment by sharonovd** [comment]
Looks like it's now feasible via [require('cartridge.twophase').on_patch()](https://stackoverflow.com/questions/64065868/how-to-implement-default-config-section-for-a-custom-tarantool-cartridge-role)

**Comment by filonenko-mikhail** [comment]
on_patch() the job is done. Feel free to reopen.
