### ISSUE TITLE
Tests completely broken on MacOS

### ISSUE THREAD

**Issue by olegrok** [tarantool/cartridge#1069]
See log https://gist.github.com/olegrok/a04e58bc94cd162bbe02cde10a5b2e24

Seems one moment we occupied all file descriptors

**Comment by rosik** [comment]
I've investigated the problem:

2. Default `ulimit -n` on macos is 256.
1. Luatest produces a lot of garbage fds for pipes

**Comment by olegrok** [comment]
Yes, it's so. I workarounded it in Mac OS CI https://github.com/tarantool/cartridge/pull/1110/files#diff-ffd0e8d632226f905ef8cdf81bcbbe1717163c00416566e344cabb454965e482R24

Also seems we should investigate Luatest as well. E.g. I suppose here https://github.com/tarantool/luatest/blob/0eb5d59d0b7a4da0fb0f237d760acbb264b959cb/luatest/ffi_io.lua#L51 old_fd could be closed (But I checked it, it didn't help in general). Another way - rewrite luatest with "popen" module.

**Comment by filonenko-mikhail** [comment]
So increasing ulimit seems solution now.
Last attempt:
- https://github.com/tarantool/cartridge/tree/tests-on-macos-2
