### ISSUE TITLE
Call `validate_config()` only for the defined roles on an instance

### ISSUE THREAD

**Issue by sharonovd** [tarantool/cartridge#107]
In GitLab by @opomuc on May 16, 2019, 14:21

When we have role-specific and instance-specific validation rules (for example an existence of a particular directory on current machine) we do not want to trigger this check for every other node in cluster. This is a `role-specific` case and should be checked when role is defined

**Comment by sharonovd** [comment]
In GitLab by @rosik on May 16, 2019, 14:41

Despite you don't want to trigger validation on replicas without a role, there are other projects who need this feature. Please, suggest another change, preferably in api, not in behavior.

To elimitate excess checks you can manually skip it with the following code:

```lua
local function validate_config(conf_new)
    local my_instance_uuid, my_replicaset_uuid = topology.get_myself_uuids(conf_new.topology)
    local my_replicaset = conf_new.topology.replicasets[my_replicaset_uuid]
    local enabled_roles = confapplier.get_enabled_roles(my_replicaset.roles)
    if enabled_roles['myrole'] then
        check_my_directory()
    end
end
```

@racktear what do you think?

**Comment by sharonovd** [comment]
In GitLab by @rosik on May 17, 2019, 15:03

Ok, let's do it as proposed.

**Comment by opomuc** [comment]
I guess we don't need it anymore.
