### ISSUE TITLE
[1pt] UI: confusing helper text when collapsing/expanding replication_info

### ISSUE THREAD

**Issue by RunsFor** [tarantool/cartridge#1070]
At the right side of `replication_info` row, helper text should suggest to "expand", not "collapse.

<img width="1000" alt="Screenshot 2020-09-28 at 11 24 16" src="https://user-images.githubusercontent.com/2008930/94408802-f9e4e700-017d-11eb-9621-6c9d2807b4c6.png">

**Comment by rosik** [comment]
Related to https://gitlab.com/tarantool/tdg/ux_ui/-/issues/23#note_417903612
