### ISSUE TITLE
[8pt] ☂️ WebUI usability when vshard-storage role is hidden

### ISSUE THREAD

**Issue by rosik** [tarantool/cartridge#1071]
TDG explicitly marks vshard-storage role as hidden in favor of simple "storage". WebUI is unable to determine when vshard could be bootstrapped.

**Comment by rosik** [comment]
WebUI renders "Edit replicaset" dialog using the following query

```graphl
{
  cluster {
    known_roles {
      name dependencies
    }
  }
}
```

Let's extend it with two new fields: `implies_storage`, `implies_router` (both boolean). Then WebUI could make decisions basing on it rather then on hardcoded "vshard-storage" name.

**Comment by Errora** [comment]
Need to change vshard-router status in Bootstrap Panel, when server unreachable for RPC (i.e for vshard-routers) after change uri

**Comment by rosik** [comment]
Initially, there were two options:

1. Don't omit hidden roles from the `known_roles` query, but supply them with the `hidden` attribute.
2. Add `implies_router` and `implies_storage` attributes as proposed.

We've recalled the motivation for choosing the second option:

It may seem that `implies_router` is a new concept, but it's not. It's already used on the frontend implicitly. It's tied on a hardcoded name of the "vshard-router" role. Using the second option makes it possible to eliminate implicit relations.

The first option doesn't help to make it explicit. And it also affects the Lua API while the issue is only related to the GraphQL.

**Comment by rosik** [comment]
Reopening for the frontend fixes.

WebUI should use new fields instead of relying on hardcoded role names.

**Comment by rosik** [comment]
A hint for testing: we've added `implies_router, impliest_storage = true` to the `myrole`. It can be used for checking the WebUI usability.
