### ISSUE TITLE
[2pt] Format "json" in "code" section 

### ISSUE THREAD

**Issue by Satbek** [tarantool/cartridge#1075]
Usually I put my config by http manual request or by u"uploading config" button in "Configurations file" section. 
If i want to read my current application's clusterwide config, I will look at "code" section in UI. And If I do it, I will see this:
<img width="1010" alt="Screenshot 2020-09-29 at 14 33 57" src="https://user-images.githubusercontent.com/26044679/94553388-2160b000-0261-11eb-9db4-7bbbfe46f1ec.png">

It is impossible to read, modify and understand this config by UI. Because of this "сode" section is useless if we have config with sections bigger than 10 lines.

**Comment by olegrok** [comment]
I think it's enough to setmetatable(cfg, {__serialize = 'mapping'}) to resolve this issue.

```lua
tarantool> setmetatable({a = 'b', b = {'a', 'b', c}}, {__serialize = 'map'})
---
- {'a': 'b', 'b': ['a', 'b']}
...

tarantool> setmetatable({a = 'b', b = {'a', 'b', c}}, {__serialize = 'mapping'})
---
- a: b
  b:
  - a
  - b
...
```

**Comment by denesterov** [comment]
I suspect that 
`cartridge.config_patch_clusterwide(conf)`
corrupts config formatting.

It is used to patch config by section, not as a whole
