### ISSUE TITLE
[1pt] Allow to hide "Make all instances writeable"

### ISSUE THREAD

**Issue by olegrok** [tarantool/cartridge#1079]
Some systems could work only when master is single instance. Usage of "all_rw" option could be easily banned with topology check. However checkbox still will be shown in WebUI. So it could confuse users.

Therefore I suggest to implement a way to hide "Make all instances writeable" option.

**Comment by rosik** [comment]
We can do it with frontend `set_variable` feature similar to #1061

See https://github.com/tarantool/frontend-core#set_variablekey-value
