### ISSUE TITLE
[4pt] schema.yml disappears from page "Code"

### ISSUE THREAD

**Issue by dsamirov** [tarantool/cartridge#1085]
I create file named "schema.yml" on the page `/admin/cluster/code`. Then I press Apply and this file disappears.

However downloaded config contains my uploaded data.

**Comment by rosik** [comment]
Proposal: get rid of the "schema" page. 

It's almost useless in comparison to the "code" page.

There are two features missing on the "code" page:

- The "validate" button. But we can add it.
- Schema example. Can be added similar to https://github.com/tarantool/cartridge/pull/1194

This would also resolve https://github.com/tarantool/cartridge/issues/1082, https://github.com/tarantool/cartridge/issues/1201, https://github.com/tarantool/cartridge/issues/1203

**Comment by rosik** [comment]
N.B. Originally the issue is caused by the following line in frontend code:

```
src/store/reducers/files.reducer.js:const ignoreFiles = ['schema.yml']
```
