### ISSUE TITLE
Transient error during config update leaves cluster locked

### ISSUE THREAD

**Issue by sharonovd** [tarantool/cartridge#1087]
We've encountered errors during config update under production load. If it happens, cluster becomes `locked`:
 - each consescutive config update fails upon `two-phase commit is locked` until nodes are restarted
 - config.prepare files must be removed manually
 - only afterwards one may perform another config update attempt.

I suggest to allow somehow to update config forcibly, without having to restart the cluster.

**Comment by rosik** [comment]
Seems related to #1046

**Comment by sharonovd** [comment]
> Seems related to #1046

I don't see how. In this case, user does want to update config, he just fails to do so.

**Comment by rosik** [comment]
I meant internally in implementation specifics.

**Comment by rosik** [comment]
Resolved in #1287
See also #1187, #1238
