### ISSUE TITLE
[Feature request]Triggers for custom events

### ISSUE THREAD

**Issue by trollsid** [tarantool/cartridge#1094]
It will be cool to have triggers for something cluster events (like up, down, bootstrap, errors) , where users can define something actions.

**Comment by rosik** [comment]
Could you add more details, please, what do these events mean.

The event "up" is ambiguous. We already have roles `init` callback.

The event "down" also could be considered as roles `stop` callback, or `box.ctl.on_shutdown` trigger.

Bootstrap is `init` + `apply_config`.

And what errors are you talking about?

**Comment by yngvar-antonsson** [comment]
No details provided since last comment. Closed until more detailed description.
