### ISSUE TITLE
Enhance ConnectingFullmesh troubleshooting doc

### ISSUE THREAD

**Issue by rosik** [tarantool/cartridge#1101]
Sergey, [22.10.20 00:29]
Добавьте, плз, в доку - в troubleshooting про ConnectingFullmesh
replication_connect_quorum : 0 надо в instances.yml добавлять для каждого инстанса (с ошибкой)
у вас есть только пример для CLI с командой replication_connect_quorum = 0

**Comment by Onvember** [comment]
I see no need in enhancing because `instances.yml` implies using colon, so it seems to be obvious to use it here.
