### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by nodermann** [tarantool/cartridge#1103]
— I closed the lid on my MacBook this midnight
— I opened it this morning
— After a few minutes, Cartridge began to eat all the RAM although no one used it
— Cartridge started logging **Too many open files**
This is a complete log from launch to demise, I had to stop it.
[zsh.log](https://github.com/tarantool/cartridge/files/5432565/zsh.log)

**Comment by rosik** [comment]
Does your cartridge app use some kind of IO? I've checked bare cartridge and couldn't find any FD leaks, but it may come from somewhere else, see #1069 for example.

In general, this error means that the process reached its `ulimit -n` which is 256 on Mac by default. If this problem bothers you ever again, you can find useful information in `lsof -p <TARANTOOL_PID>`.
