### ISSUE TITLE
Consider singletone role supporting.

### ISSUE THREAD

**Issue by sharonovd** [tarantool/cartridge#111]
In GitLab by @filonenko-mikhail on May 24, 2019, 15:46

There are cases when role have to be the only one in whole cluster.

For example `logger` role which collects (business) logs from cluster nodes. 
 
API suggestion.

```lua

return {
  role_name = 'logger',
  singleton = true
}
```

**Comment by sharonovd** [comment]
In GitLab by @filonenko-mikhail on May 24, 2019, 15:46

changed title from **Consider singletone role {-implementation-}.** to **Consider singletone role {+supporting+}.**

**Comment by rosik** [comment]
It can already be achieved by the proper validate_config implementation.
