### ISSUE TITLE
Add status, dignostics and errors of rebalancing process in WebUI

### ISSUE THREAD

**Issue by no1seman** [tarantool/cartridge#1112]
It will be great if administrator could see in WebUI not only number of buckets on every shard instance but also a status of rebalancing process itself, rebalancing errors and also some diagnostics.

**Comment by rosik** [comment]
Touched in #1490. Now you can find `buckets_sending` / `buckets_receiving` in server details.

**Comment by sergos** [comment]
1. buckets_sending / buckets_receiving are available in server details, that reflects the rebalancer activity.
2. alerting is not feasible in the current architecture due to a lot of messages during bootstrap
