### ISSUE TITLE
UI: not empty schema without any spaces is considered to be 'valid'

### ISSUE THREAD

**Issue by vrogach2020** [tarantool/cartridge#1117]
Steps to reproduce:
1. in ui create and upload schema.yml with the following contents:
```
not-a-spaces:
    -test
    -test2
```
2. Apply config
3. Goto schema and press reload
![image](https://user-images.githubusercontent.com/73178536/98817300-f8743300-243a-11eb-9994-9fb23b8d8c1c.png)

**Comment by rosik** [comment]
Here's the problem:

https://github.com/tarantool/cartridge/blob/4f49a799f0fa41cbf3c9b9112268d1e4195b9d4e/cartridge/ddl-manager.lua#L42-L48

There also should be a check for unknown keys, like in `topology.lua`:

https://github.com/tarantool/cartridge/blob/master/cartridge/topology.lua#L312-L323
