### ISSUE TITLE
[2pt] Revise healthcheck predicates

### ISSUE THREAD

**Issue by rosik** [tarantool/cartridge#1139]
Nowadays there are several different health check predicates in Cartridge.

# Eventual failover

https://github.com/tarantool/cartridge/blob/e5ca1328056bf3a3fcccc3b7a108d25d23c1f445/cartridge/failover.lua#L150-L161

# Stateful failover 

https://github.com/tarantool/cartridge/blob/e5ca1328056bf3a3fcccc3b7a108d25d23c1f445/cartridge/roles/coordinator.lua#L34-L47

# RPC

https://github.com/tarantool/cartridge/blob/e5ca1328056bf3a3fcccc3b7a108d25d23c1f445/cartridge/rpc.lua#L41-L52

I see two potential problems here:
1. Neither eventual nor stateful failover isn't triggered until a 'suspect' member becomes dead, but RPC already considers it as unhealthy. As a result, `get_active_leaders` may return a suspect leader and the RPC call would return an error "No remotes with role %q available" preliminary.
2. Stateful failover isn't triggered for OperationError, but eventual failover is. It seems to be slightly inconsistent.

**Comment by rosik** [comment]
After a brief discussion with @olegrok and @mtrempoltsev we agreed that RPC should consider 'suspects' as healthy.

**Comment by rosik** [comment]
And I think that OperationError shouldn't be considered unhealthy even if it sounds silly. RPC DoS and additional config applications are even worse taking into account that OperationError is the result of `apply_config` (or `init`) failure.

**Comment by sharonovd** [comment]
Dmitry Sharonov, [15.06.21 14:00]
почему фейловер не сработал, я не понимаю

Dmitry Sharonov, [15.06.21 14:00]
да, мастер гикнулся при накате конфига

Yaroslav Dynnikov, [15.06.21 14:10]
https://github.com/tarantool/cartridge/issues/1139

Да, стейтфул не триггерится на OperationError.
