### ISSUE TITLE
Implement zone filtering 

### ISSUE THREAD

**Issue by rosik** [tarantool/cartridge#1140]
Proposed API:

```lua
cartridge.rpc_get_candidates('vshard-router', {zone = ...})
cartridge.rpc_call('myrole', 'foo', {}, {zone = ...})
```

Or should it be called `same_zone_only`?

**Comment by sharonovd** [comment]
What's the API for getting my own zone?

**Comment by rosik** [comment]
> What's the API for getting my own zone?

Nowadays it looks like this:

```lua
cartridge.admin_get_servers(box.info.uuid)[1].zone
```

I know it's pretty ugly, so it's a reason to enhance it later.

**Comment by filonenko-mikhail** [comment]
Probably it have to be done in separate api, to not make complex existing.
