### ISSUE TITLE
[UI] Add horizontal scroll to Error details

### ISSUE THREAD

**Issue by Errora** [tarantool/cartridge#1141]
**Steps to Reproduce:**

1. Open Error Details modal

**Result:**

Long lines did not fit into the modal:

![изображение](https://user-images.githubusercontent.com/12095303/100454217-86a01880-30cd-11eb-813d-2c9fa8e51808.png)

**Expected Result:**

There is a horizontal scroll in the modal (as in TDG)

**Comment by rosik** [comment]
Resolved in https://github.com/tarantool/front-ui-kit/pull/193
