### ISSUE TITLE
[2pt] Uploading big config fails on large clusters

### ISSUE THREAD

**Issue by rosik** [tarantool/cartridge#1145]
When the cluster-wide configuration is updated, Cartridge sends it whole to every instance in a cluster. He does it in parallel and imposes a hardcoded 5-second timeout restriction. If we suppose that there are 100 instances, the size of config is 1MB and the network bandwidth is 100Mb/s, then it would take 8 seconds and obviously fail.

**Comment by sharonovd** [comment]
Our customer bumped into it
