### ISSUE TITLE
Downloading and building all dependencies when creating a deb package

### ISSUE THREAD

**Issue by first-leon** [tarantool/cartridge#1160]
Every time, where I build a deb package, all the dependencies are downloaded and built.
This is slow and requires Internet access.
Is it possible to reuse previously downloaded and installed dependencies?

```
cartridge -v
Tarantool Cartridge CLI v2.4.0 linux/amd64 commit: 2079d9b
```

**Comment by rosik** [comment]
What dependencies are built for you? How does your rockspec look like? Is cartridge dependency specified with a particular version? If not, it may be the cause of a slow build.

**Comment by rosik** [comment]
And with a version specified it takes about 13s for me.

**Comment by first-leon** [comment]
This my rockspec file:

```
package = 'dombrain'
version = 'scm-1'
source  = {
    url = '/dev/null',
}
-- Put any modules your app depends on here
dependencies = {
    'tarantool',
    'lua >= 5.1',
    'checks == 3.0.1-1',
    'cartridge == 2.3.0-1',
    'metrics == 0.5.0-1',
    'cartridge-cli-extensions == 1.0.0-1',
    'icu-date == 1.3.3-1',
    'cron-parser == 1.0.0-1',

}
build = {
    type = 'none';
}

```
Cartridge dependency specified version.

But every run pack deb package, i see (log in attach). Every dependency compiling every time.

[cart.log](https://github.com/tarantool/cartridge/files/5656996/cart.log)

**Comment by rosik** [comment]
On my laptop `cartridge pack deb` of the same rockspec takes 23s and installs 14 rocks in total.

As I see from the log only a few rocks are getting compiled, but they're quick. Most of the time is wasted on the communication with the rocks server. Actually, we have a feature of offline development, but it's in Tarantool Enterprise. It requires patching luarocks and a specific file layout. I don't know how to speed it up in a general case.

**Comment by rosik** [comment]
By the way, why do you need `pack deb` to be fast? Most of the development tasks don't require deb, `cartridge start` is enough for manual testing. And there's https://github.com/tarantool/luatest for autotests.

**Comment by first-leon** [comment]
Yes. I have slow Internet access. And sometimes there is no Internet access. Therefore, the build is slow and sometimes crashes. So I wanted to configure the build without Internet access, using the cache.
If this is only available in the Enterprise version, then building a deb package using Cartridge is not suitable for me.

Thanks for the answer.
