### ISSUE TITLE
Security Audit

### ISSUE THREAD

**Issue by sharonovd** [tarantool/cartridge#117]
In GitLab by @filonenko-mikhail on Jun 5, 2019, 15:05

Audit log MUST contain:

1. Timestamp of event (e.g. Login/Logout/Action/etc)
2. User identifier which makes Action
3. IP address
4. Identifier of User Session or Application Token
5. Error if login/logout/action failed.
6. User/Token management events. Log all events about user/token CRUD.
  - who make
  - what make
  - with what parameters
7. Log system settings changes with old and new values of params.

**Comment by sharonovd** [comment]
In GitLab by @filonenko-mikhail on Jun 5, 2019, 15:07

changed the description

**Comment by rosik** [comment]
Not a cartridge feature, implemented in tdg instead
