### ISSUE TITLE
[3pt] Describe rebootstrap process

### ISSUE THREAD

**Issue by rosik** [tarantool/cartridge#1180]
Cartridge has a feature of re-bootstrapping a replica - you remove snaps, xlogs, but preserve cluster-wide config (`config` dir). Then you restart an instance and it bootstraps from a master.

See also https://github.com/tarantool/ansible-cartridge/issues/149

**Comment by artur-barsegyan** [comment]
Please, describe the motivation for this procedure. I can't take it for the next sprint with this description.

**Comment by rosik** [comment]
I'd say it's necessary when the replication is doomed.

@sharonovd could you help me with a better description?

**Comment by sharonovd** [comment]
Yes, e. g. when you see 'Missing xlog/duplicate key found'
