### ISSUE TITLE
[8pt] Revise queries made by the WebUI

### ISSUE THREAD

**Issue by rosik** [tarantool/cartridge#1182]
There're several aspects of WebUI requests which may be a problem or maybe not.

## WebUI polls server list

On a large cluster it transfers 300KB every 3 sec. The query includes the whole topology, but it changes only occasionally.

## WebUI queries sometimes duplicate

In particular server stats (the memory usage bar). If it's not loaded yet, WebUI tries to fetch it every request.

![image](https://user-images.githubusercontent.com/2205188/102218639-5343f300-3eef-11eb-9050-092d4e1c1496.png)

## Map-reduce queries are suboptimal

The following queries require map-reducing info from all servers:

- boxinfo
- issues
- server stats (memory usage, buckets count)

What can we do to make them cheaper? (And should we?)

## WebUI bundle is huge

![image](https://user-images.githubusercontent.com/2205188/102220603-1af1e400-3ef2-11eb-8824-ac609b64bfe3.png)

- It's not cached
- It's not gzipped

## The question is

Which of the above are the real problems?

**Comment by opomuc** [comment]
![image](https://user-images.githubusercontent.com/8739816/105319480-f9ada300-5bd5-11eb-8d12-23639483ebea.png)
If you restart half of 112 instances, WebGUI will load for **15 min**. This correlates to storage instance reload time, so might be connected.
Not all of replicasets are storages. Routers have their own replicasets. Out of 58 replicasets, 13 -- routers. 45 replicasets are reloaded _at the same time_.

**Comment by opomuc** [comment]
Since **cartridge 2.6.0** I see a dramatic change in this:
![image](https://user-images.githubusercontent.com/8739816/119674110-9b732400-be44-11eb-9258-034d5947c706.png)
Looks lika a 60s timeout somewhere

**Comment by usenko-timur** [comment]
What do we need to do?

- Enable (gzip, deflate, br) compression of static files (js, pictures) in our http server.
- Enable caching of static files (js, pictures) in our http server (there is a Cache-control: max-age = 86400 header, need to add more caching headers).
- Add support for getting new server data without constant polling.
  possible options: 
  * [Server Sent Events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events) (no IE support, but we don't need)
  * [WebSocket](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API)

**Comment by filonenko-mikhail** [comment]
Seems, the central station of configs is solution. Anyway for such activity we have to investigate hot places with appropriate instrument.

**Comment by opomuc** [comment]
What is "central station of configs"? 

On a second note, I haven't seen long loading times for a while.
