### ISSUE TITLE
Group operations

### ISSUE THREAD

**Issue by sharonovd** [tarantool/cartridge#1195]
I want to:
a) select several servers (probable, filter by label or enabled role)
b) change some box.cfg parameters for them

Second scenario - I wantt to select several replicasets (again, probably feiltered by label) and promote replicas in all of them (mass promote to another DC)

**Comment by rosik** [comment]
Related to #442

**Comment by filonenko-mikhail** [comment]
Seems that opinions devided between static config and possible of dynamic changing. This time I think we have to move such feature to roadmap of mentenance with appropriate planning. .
