### ISSUE TITLE
Implement "Backup" button

### ISSUE THREAD

**Issue by sharonovd** [tarantool/cartridge#12]
In GitLab by @rosik on Oct 22, 2018, 19:00

**Comment by sharonovd** [comment]
In GitLab by @rosik on Jan 10, 2019, 15:56

mentioned in commit cebda3eb0bb83a2ca8b2e71c23f39dac9b5dbaef

**Comment by rosik** [comment]
Suppressed by https://github.com/tarantool/tt/issues/1, https://github.com/tarantool/tt/issues/3
