### ISSUE TITLE
Allow removing spaces from DDL schema

### ISSUE THREAD

**Issue by rosik** [tarantool/cartridge#1200]
There is a case in [migrations](https://github.com/tarantool/migrations/) module:

- Some migration drops a space;
- `get_schema` returns one space less;
- Migration module tries to `set_schema`;
- Cartridge complains "Missing space .. in schema, removing spaces is forbidden".

But it's a legal case and it should be allowed.

**Comment by sharonovd** [comment]
Some users patched this check as:
Dmitry Sharonov, [20.04.20 14:01]
 if schema_new.spaces[space_name] == nil and box.space[space_name]  ~= nil
