### ISSUE TITLE
[SWIM] old members of the cluster do not send pings to a new member

### ISSUE THREAD

**Issue by sharonovd** [tarantool/cartridge#121]
In GitLab by @opomuc on Jun 13, 2019, 12:55

If we probe a newly started instance from a bootstrapped cluster, it is added to a membership table on the probe server. After that, each member of the table on the probe server recieves ping from a new server. BUT there is no backward PING, meaning new instance will NOT know about a membership table on the probe server

**Comment by sharonovd** [comment]
In GitLab by @opomuc on Jun 13, 2019, 12:55

marked this issue as related to #119

**Comment by sharonovd** [comment]
In GitLab by @olegrok on Jun 18, 2019, 18:28

Есть планы по переезду на https://www.tarantool.io/ru/doc/2.1/reference/reference_lua/swim/ ?

**Comment by rosik** [comment]
Even if this bug ever existed, I believe it's all fine nowadays
