### ISSUE TITLE
[EPIC] Make UI for data viewing  

### ISSUE THREAD

**Issue by rosik** [tarantool/cartridge#1211]
## Description
TBD feature description here.

## List of tasks implementing the epic
- [ ] Implement UI design (in figma)
- [ ] *TODO* Enumerate epic development tasks here
- [ ] Automated tests
- [ ] Documentation

**Comment by no1seman** [comment]
Also it would be great if it will be not only local space-explorer but it would also allow making cluster queries with a known sharding key or even a fullscan with a limit on the number of records / data volume to return
