### ISSUE TITLE
Server status is "suspect" and "dead"

### ISSUE THREAD

**Issue by seet61** [tarantool/cartridge#1216]
We have cartridge cluster.
2 servers.
At each server router, master and replica.

We save some information through crud and after that we don't do anything due new year holidays.
Today I see that cluster have a lot of errors. 
Nodes periodically change their status to healthy -> suspect -> dead and this is repeated constantly.

Reboot, reinstall of services not help to solv this problem.
Uprgade of tarantool from Tarantool 2.5.2-0-g05730d3 to Tarantool 2.5.3-0-gf93e480 not help too. 

CentOS Linux release 7.9.2009 (Core)

![suspect_1](https://user-images.githubusercontent.com/6140289/104153847-741b3d80-53f4-11eb-8744-2e30a1468acf.jpg)
![suspect_2](https://user-images.githubusercontent.com/6140289/104153841-72517a00-53f4-11eb-92c7-70e4dc04d467.jpg)
![suspect_3](https://user-images.githubusercontent.com/6140289/104153845-7382a700-53f4-11eb-988c-3dfad66d796f.jpg)

Logs fromn two servers
[s1.tar.gz](https://github.com/tarantool/cartridge/files/5794343/s1.tar.gz)
[s2.tar.gz](https://github.com/tarantool/cartridge/files/5794346/s2.tar.gz)

**Comment by seet61** [comment]
s1 - 10.78.221.227, s2 - 10.78.221.228. 
It is not a problem of network, because at logs we see errors between nodes at the same server.

**Comment by seet61** [comment]
cartridge 2.3

**Comment by seet61** [comment]
@rosik Thank you about information of tarantool events pool. I changed custom fibers, now cartridge cluster works stable.

**Comment by rosik** [comment]
I would add that we can see in s1-master (10.78.221.227:3302) logs:

```
2021-01-11T09:48:20.670+0300 Could not reach node: 10.78.221.227:3302
```

It means it couldn't respond to ping in time. Most likely, it means that some fiber holds control without a yield for too long.
