### ISSUE TITLE
Export `server.status` values from cluster topology as a enum/table

### ISSUE THREAD

**Issue by opomuc** [tarantool/cartridge#1218]
I mean statuses like:
```
unreachable
unconfigured
not found
```

If I want to check server.status, I will need a string comparison. If by any change those statuses change, that will corrupt a lot of code.

Maybe under `require('cartridge.lua-api.const')` or similar module.
```
local statuses = {
    UNREACHABLE = 'unreachable',
    UNCONFIGURED = 'unconfigured',
    NOT_FOUND = 'not found',
    ...
}

return {
   statuses = statuses
}
```

**Comment by rosik** [comment]
Is your question about the compatibility only? The `{ servers { status }}` is a part of the public API and semantic versioning prohibits breaking backward compatibility unless it's a new major release.

I'd like to note that in the scope of #1066 we're going to develop a better status model, which will not require a change in the future, but we'll do our best to keep it compatible.

**Comment by opomuc** [comment]
We need a method in lua-api, not the GraphQL one

**Comment by rosik** [comment]
The same is true for the `admin_get_servers()` public Lua API. The string comparison is OK. I can't see why the constant string key name is better than the constant string value.

**Comment by opomuc** [comment]
Incorrect key name can be found with static analyzers

**Comment by rosik** [comment]
Luacheck? Show me how to.

**Comment by opomuc** [comment]
Ok, I can't give an example of a static analyzer right away (but guess some in IntelliJ might work).
But at least this will work:
![image](https://user-images.githubusercontent.com/8739816/105464276-570f2600-5ca2-11eb-81f3-9fdfdde7031a.png)

**Comment by filonenko-mikhail** [comment]
Gently closing. Feel free to reopen.
