### ISSUE TITLE
Add user module hot-reload guide/example with crud+migrations modules

### ISSUE THREAD

**Issue by no1seman** [tarantool/cartridge#1219]
edited by @filonenko-mikhail:

Проблема такая, для работы хотрелода, нужен некоторый набор тайных знаний. Какие требования должны быть выполнены в обработчиках apply_config, validate_config и др, чтобы хотрелод сработал.

**Comment by rosik** [comment]
Related to https://github.com/tarantool/migrations/issues/35

**Comment by filonenko-mikhail** [comment]
This time there are no stability in hotreload during components updates. I think that's it's too early to make documentation. Much much gently closing.
