### ISSUE TITLE
Introduce "fences" for cluster initialization

### ISSUE THREAD

**Issue by sharonovd** [tarantool/cartridge#122]
In GitLab by @racktear on Jun 20, 2019, 13:04

It is often the case when a client waits until a certain state is achieved. For instance, when adding members through SWIM, we should wait for them to become healthy, until we can apply any configuration. When applying configuration, we should wait until all cluster nodes converge on that configuration (especially if it's the first config).

So, let's introduce ways for client code to poll on the cluster state. This is very important for integration testing helpers, as well as for ansible scripts and a kubernetes operator.

**Comment by rosik** [comment]
Seems like ansible and k8s are ok even without it. Moreover, once some state is reached it doesn't mean it won't change again.
