### ISSUE TITLE
[2pt] [UI] Code: Add notification for name check

### ISSUE THREAD

**Issue by Errora** [tarantool/cartridge#1223]
**Шаги:**

1. Перейти на страницу Code
2. Добавить файл/папку с наименованием 123
3. На том же уровне дерева добавить еще один файл/папку с наименованием 123

**Ожидаемый результат:**

Поле стало красным и отобразилась нотификация о том, что такое имя уже существует

**Полученный результат:**

Файл/папка не создается и нотификации с причиной нет

**Comment by rgbabaev** [comment]
Ожидаем дизайн от @Katedraw

**Comment by rgbabaev** [comment]
Design: https://github.com/tarantool/ux_ui/issues/77
