### ISSUE TITLE
☂️ Support native tarantool election_mode as cartridge failover mode

### ISSUE THREAD

**Issue by R-omk** [tarantool/cartridge#1233]
_Modified by @filonenko-mikhail_

## Motivation
There are two failover modes in catridge:
  - eventual
  - stateful
  
Eventual is lightweight but not strong consistent.
Stateful consistent but requires additional sync cross dc kv storage cluster.

Introduce new mode for built-in raft based tarantool failover.

## Bucket Ref On Replica Problem 

Case, when bucket ref was on replica and read the query from replica, lost data during rebalance happened.

- https://github.com/tarantool/vshard/issues/173

## Server disable/enable

The problem when raft switch ro, at this time vshard does not know that request routing changed. vshard router knows about new raft master only after failover timeout + reconfiguration timeout.

If `storage.disable` exists, it happens right after raft switch master flag.

- https://github.com/tarantool/vshard/discussions/307

## We do not know by raft monitoring about leader lost

For e.g. there are three nodes. The first is a leader. And there are two followers.
First two become dead. And the third remember that leader is first. And we can't make the right decision according to the third node world view.

- https://github.com/tarantool/tarantool/issues/6690

## Auto revoke leadership when connectivity loss (r-omk)

- https://github.com/tarantool/tarantool/issues/6661

## (probably) Split-brain when low quorum

- https://github.com/tarantool/tarantool/issues/5295

**Comment by Fedora7** [comment]
Please provide API for manual update of replication_synchro_quorum , election_timeout, replication_timeout under raft election_mode if possible.

**Comment by R-omk** [comment]
Related (even blocks) for "vsahrd router" role https://github.com/tarantool/vshard/issues/209

**Comment by rosik** [comment]
> Please provide API for manual update of replication_synchro_quorum , election_timeout, replication_timeout under raft election_mode if possible.

What kind of API do you need? GraphQL and WebUI? Because `box.cfg()` is already there.

**Comment by Fedora7** [comment]
> What kind of API do you need? GraphQL and WebUI? Because `box.cfg()` is already there.

I need to change these settings by ansible cartridge's playbook (yml).

**Comment by R-omk** [comment]
related 
https://github.com/tarantool/tarantool/issues/5819
