### ISSUE TITLE
Update docs on cartridge.pool [mopinion]

### ISSUE THREAD

**Issue by NickVolynkin** [tarantool/cartridge#1242]
(table) United error object, gathering errors for every URI that failed. -- https://github.com/tarantool/cartridge/blob/master/cartridge/pool.lua#L175 code says it returns nil as second argument if no error occured. Also it is hard to understand what 'united error object' is without reading the source code. 

It also would be convenient to provide some example on `fn_name` and use of map_call 

https://www.tarantool.io/en/doc/latest/book/cartridge/cartridge_api/modules/cartridge.pool/

**Comment by rosik** [comment]
A side problem here is that `cartridge.pool` module isn't actually a part of the public API.
