### ISSUE TITLE
☂️  Unify error handling in webUI

### ISSUE THREAD

**Issue by rosik** [tarantool/cartridge#1252]
1. Change zone in server details 
![image](https://user-images.githubusercontent.com/2205188/106881208-49b85980-66ee-11eb-8be7-e837cbb14ca7.png)

2. Add new zone in server details 
![image](https://user-images.githubusercontent.com/2205188/106881146-360cf300-66ee-11eb-9ea1-f561efe28fe3.png)

3. Expel dead server - webui failure

4. Expel server 
![image](https://user-images.githubusercontent.com/2205188/106882004-4a9dbb00-66ef-11eb-87a8-03974057ebf9.png)

5. Edit replicaset / Create replicaset / Join replicaset

6. Bootstrap vshard - close button misplaced 
![image](https://user-images.githubusercontent.com/2205188/106882309-ab2cf800-66ef-11eb-951e-c9ef50289894.png)

7. Add user dialog (spinner ok)
![image](https://user-images.githubusercontent.com/2205188/106882544-edeed000-66ef-11eb-9296-a00bf25aea92.png)

7. Enable auth ![image](https://user-images.githubusercontent.com/2205188/106883146-a87ed280-66f0-11eb-9df1-8ac24f24ce3c.png)

8. Code page 
![image](https://user-images.githubusercontent.com/2205188/106882948-63f33700-66f0-11eb-9e8f-099bf798255b.png)

9. Schema page 
![image](https://user-images.githubusercontent.com/2205188/106883035-7a00f780-66f0-11eb-92f9-b45d1e0b568e.png)

**Comment by Katedraw** [comment]
Задача разбита на подзачачи: 
Обновление экранов с ошибкой при потери связи сети
https://github.com/tarantool/ux_ui/issues/88

Обновление иконок для блоков: пустой список, загрузка файла, выбор файла
https://github.com/tarantool/ux_ui/issues/91

Баг при загрузке пустого списка 
https://github.com/tarantool/ux_ui/issues/92

Унификация нотификаций и алертов 
https://github.com/tarantool/ux_ui/issues/90

Удаление/редактирование успешной нотификации
https://github.com/tarantool/ux_ui/issues/89

**Comment by Katedraw** [comment]
Partially done.
