### ISSUE TITLE
[2pt] A couple of UI issues with latest cartridge

### ISSUE THREAD

**Issue by FZambia** [tarantool/cartridge#1263]
Hello, I just installed Cartridge using

```
tarantoolctl rocks install cartridge
```

Seems like it's being installed from master branch.

Then in admin UI I came across two issues.

1) Create Replica Set button is always in disabled state:

<img width="1680" alt="Снимок экрана 2021-02-12 в 21 39 38" src="https://user-images.githubusercontent.com/1196565/107815969-24c68500-6d85-11eb-909a-c68d3c4044d4.png">

2) Closing button of Bootstrap Vshard modal window is in a wrong top-right position:

<img width="1680" alt="Снимок экрана 2021-02-12 в 22 52 32" src="https://user-images.githubusercontent.com/1196565/107816075-432c8080-6d85-11eb-8175-79963692acf5.png">

When I am using Cartridge 2.4.0 using:

```
tarantoolctl rocks install cartridge 2.4.0
```

– there are no issues.

MacOS Big Sur, Google Chrome 88.0.4324.150 (x86_64)

**Comment by rosik** [comment]
Hi. Thanks for your feedback. Those are known bugs. They'll be resolved in #1262.

**Comment by FZambia** [comment]
Thanks guys! Will check it out and report back in case of any problem.

**Comment by rosik** [comment]
The closing button is still misplaced though. We keep it in mind and fix it later in the other repo, hope it doesn't affect anything. Anyway, without vshard, this button won't be visible anymore (it's useless).
