### ISSUE TITLE
Hypothesis: trigger issues 

### ISSUE THREAD

**Issue by filonenko-mikhail** [tarantool/cartridge#1268]
My feature request is about the trigger managing.

The situation is that:

- User make the trigger
- User place trigger setup on the space in cartridge callback
- And cartridge calls callback several times because of cluster lifecycle
  - For e.g. enabling/disabling role 
- The frustrating result is that the same trigger function can be set on the same space many times

So, the thing also can be happened when hotreload code.

What is the solution?

The cartridge already contains hotreload manager and cluster issue tracker.

So cluster manages instance state.
Cluster changes instance state. Cluster calls role callbacks, and role callback can change instance state too.

The sinergy is 
- Track the system state transitions between cluster configuring steps
- Generate issues in case of dangerous transitions

For e.g.

- There is space `users` on storage node
- Cartridge apply roles on storage node
- Role every time setup new trigger on table `users`
- Cartridge count that there are already 20 triggers and make an issue, that there is «too much logic on one space, be careful my little clusterbuilder»

**Comment by rosik** [comment]
> Cluster calls role callbacks, and role callback can change instance state too.

If by the instance state you mean internal state machine, then no, it can't.

> What is the solution?

1. Set the trigger exactly once, you can always check if it's already set. 
2. Remove the trigger when the role is disabled.

Roles reload in cartridge works as `stop() -> reload -> init() -> apply_config()`.

**Comment by sharonovd** [comment]
Honestly, I'd prefer to see it 
a) fixed in core
b) monitored in cartridge
Please feel free to involve me in triage process

**Comment by filonenko-mikhail** [comment]
closed due to https://github.com/tarantool/metrics/issues/272
