### ISSUE TITLE
[UI] When the role vshard-storage is disabled, an extra separator is displayed in replica set

### ISSUE THREAD

**Issue by Errora** [tarantool/cartridge#1271]
**Steps:**

1. Enable vshard-storage role for replicaset
2. Enable default Vshard group
3. Disable vshard-storage and save replicaset

**Result:**

Extra separator is displayed in replica set:

![изображение](https://user-images.githubusercontent.com/12095303/108366291-3f777e80-7209-11eb-9059-2101054abd16.png)

**Comment by usenko-timur** [comment]
The issue is no longer relevant and may be closed because we changed the design [here](https://github.com/tarantool/cartridge/issues/1390).
