### ISSUE TITLE
Password policy

### ISSUE THREAD

**Issue by sharonovd** [tarantool/cartridge#129]
In GitLab by @racktear on Jun 3, 2019, 11:22

It should be possible to specify password policy requirements for users (password length, number of symbols, etc)

**Comment by sharonovd** [comment]
In GitLab by @rosik on Jun 26, 2019, 11:04

You implement `add_user` yourself. You can check there whatever you want.

**Comment by sharonovd** [comment]
In GitLab by @racktear on Jun 26, 2019, 13:24

this is true. however, we should have at least a few functions that validate password policies and return meaningful errors. without this, it will be hard to certify our products

**Comment by sharonovd** [comment]
In GitLab by @rosik on Jun 26, 2019, 14:53

Ok. Here is design proposal.

Let's implement the following in `cluster.auth` module:

```
function generate_password(opts) 
  checks({
    length = '?number',
    use_lowercase = '?boolean', -- a-z
    use_uppercase = '?boolean', -- A-Z
    use_numbers = '?boolean', -- 0-9
    use_symbols = '?boolean', -- !@#$%^&*
    min_numbers = '?number', -- default 1
    min_symbols = '?number', -- default 1
  })
end
```

```
function check_password_policy(password, policy)
  checks('string', {
    min_length = 'number',
    has_lowercase = '?boolean',
    has_uppercase = '?boolean',
    has_numbers = '?boolean',
    has_symbols = '?boolean',
  })
end
```

**Comment by sharonovd** [comment]
In GitLab by @rosik on Jun 26, 2019, 14:59

moved from central#101

**Comment by sharonovd** [comment]
In GitLab by @rosik on Jun 26, 2019, 15:02

Or we can choose another way - use a library to estimate password entropy ([zxcvbn](https://github.com/dropbox/zxcvbn) for example) and check for minimum value

**Comment by rosik** [comment]
Not a cartridge feature, implemented in tdg
