### ISSUE TITLE
Enabling failover without conflict triggers set on storages may lead to replicasets in a broken state

### ISSUE THREAD

**Issue by akudiyar** [tarantool/cartridge#1311]
Steps to reproduce:

1) Write some code with non-idempotent operations, running in Cartridge cluster (e.g. using this example https://github.com/no1seman/replication_conflict)
2) Enable eventual failover
3) Some replicasets may appear in inconsistent state like this:

![image](https://user-images.githubusercontent.com/2381032/110908063-59dfdc00-831f-11eb-8220-0e7fcd119685.png)

The only way to fix this seems to be either restarting the replica with `replication_skip_conflict` option or rebootstrapping it completely by removing all the data. Both ways are not very safe on production and may lead to either missing data or cluster out of service.

Proposed ideas:

1) Check the presence of conflict triggers on all cluster spaces when a failover is being enabled on a replicaset, and notifying the user if there are no such triggers
2) Add some "default" trigger automatically when enabling the failover, which will notify the user via logs or errors about the necessity of  configuring the triggers

**Comment by Mons** [comment]
Don't do that.

Presence of "trigger" can not state, that trigger is for conflict resolving.
There is no possibility to create universal trigger
"Eventual failover" is broken by architecture design and always eventually leads to broken cluster
The only correct solution for automatic healthy cluster is using synchronous replication and raft

**Comment by akudiyar** [comment]
> Presence of "trigger" can not state, that trigger is for conflict resolving.
Of course. Cartridge must be able to determine if a trigger is the replication trigger.

> There is no possibility to create universal trigger
It is not proposed. The proposed idea is __notifying__ the user that the trigger __must__  be set before using the failover. How it will be done, needs analysis and design.

> "Eventual failover" is broken by architecture design and always eventually leads to broken cluster
Doesn't the stateful failover lead to the broken cluster as well? They say that triggers are necessary for the stateful failover too.

**Comment by Mons** [comment]
> Of course. Cartridge must be able to determine if a trigger is the replication conflict trigger.

There is no definition of "replication conflict trigger"

> Doesn't the stateful failover lead to the broken cluster as well?

Automatic failover with **asynchronous** replication leads to broken replication. The answer is: synchronous replication.
This is why there is no such automatic failover in mission critical MRG projects, that use Tarantool as a main datastore.

**Comment by sharonovd** [comment]
I'm voting for including this (info on non-idempotent operations) into documentation at some point, e. g. "Common mistakes", or "Replication gimmicks".
Users seldom care to test it before-hands
