### ISSUE TITLE
Add option for automatic rebootstrapping a replica from UI if it is in a conflicted or broken state

### ISSUE THREAD

**Issue by akudiyar** [tarantool/cartridge#1312]
Consider that the user sees the following broken replicaset state:

![image](https://user-images.githubusercontent.com/2381032/110914140-070a2280-8327-11eb-9fdc-13a9e49aa5a9.png)

It may decrease the suffering for the users if they will be able to rebootstrap the replica directly from UI.

**Comment by akudiyar** [comment]
Related issues:
https://github.com/tarantool/ansible-cartridge/issues/149
https://github.com/tarantool/cartridge/issues/1180

**Comment by rosik** [comment]
Cartridge WebUI responsibilities end when it comes to the OS process management. Rebootstrap implies restarting the instance, and WebUI can't help it.

One can write a Lua script which would help, but it may be implemented in several slightly different ways. Btw, there already exists a Cartridge CLI admin extension https://github.com/tarantool/cartridge-cli-extensions/blob/master/doc/admin.md.

E.g.:

1. Cleanup snapshots and WAL files
2. Call `os.exit(0)`, and hope the systemd would restart it.

The final decision is up to SRE, which way to choose.
