### ISSUE TITLE
Incomprehensible warning when a replica is in a conflict state

### ISSUE THREAD

**Issue by akudiyar** [tarantool/cartridge#1313]
If the replica is in a conflict state and definitely broken (needs rebootstrapping), the user sees an incomprehensible "issue" in UI that "replication is loading":

![image](https://user-images.githubusercontent.com/2381032/110917309-d4622900-832a-11eb-9765-2ec3011f1f93.png)

I suggest showing the user that xlog gap is an unrecoverable error.

**Comment by sharonovd** [comment]
Looks covered by #1335

**Comment by sharonovd** [comment]
> Looks covered by #1335

@rosik can yoou confirm?

**Comment by rosik** [comment]
Yes. Since `2.5.1-0` it's shown as critical.
