### ISSUE TITLE
Hotreload: Add reload state setter/getter and public reload mutex

### ISSUE THREAD

**Issue by no1seman** [tarantool/cartridge#1328]
Cartridge roles hotreload was introduced In Cartridge 2.4.0. It very powerful feature, but there are some API missings:

1. Some special roles, for example `migrations` have to have an ability to temporarily block firing cartridge.reload() when it performs long migration with yields.
2. Cartridge roles have to have an option to get current reload state: Started/Finished or smth like this to avoid starting any dangerous operations when reload process is already started.
3. Administrator must have an option to toggle roles_reload_allowed with lua api to prevent occasional firing cartridge.roles.reload() for example disable before/during rolling update and enable it after.

**Comment by filonenko-mikhail** [comment]
Example:
```
cartridge.cfg{hotrealoadble = false}
long running app
cartridge.cfg{hotrealoadble = true}
```
