### ISSUE TITLE
CFG: Make public API for all dynamic cartridge.cfg options

### ISSUE THREAD

**Issue by no1seman** [tarantool/cartridge#1341]
Make public LUA API (getters/setters) for all dynamic cartridge.cfg options to be able to change them in runtime:
http_enabled
webui_enabled
http_port
http_host
alias
auth_enabled
auth_backend_name
webui_blacklist
roles_reload_allowed
and may be some other options

**Comment by filonenko-mikhail** [comment]
This time such feature required roadmap and api design. Gently closing now.
