### ISSUE TITLE
[4pt] WebUI components state hydration

### ISSUE THREAD

**Issue by no1seman** [tarantool/cartridge#1346]
All modern web interfaces use property hydration (persistence of properties that survives page reloads in the local or session storage of the browser). For example, if I collapsed Cartridge WebUI menu, then after reloading the page, it should remain collapsed, if I applied a filter on the Cluster page, then after reloading the page, the filter should remain and so on....

**Comment by usenko-timur** [comment]
Implemented:
- Add the ability to work with localStorage and sessionsStorage in core. 
- Implement collapsed side menu state storage.
- Add filter state storage to the Cluster page.

**Comment by OlgaYakovleva** [comment]
Implement collapsed side menu state storage. Verified:
* saved menu state storage in the current browser in new tab, new window (after closing previous one)
