### ISSUE TITLE
WebUI page update/reload informer

### ISSUE THREAD

**Issue by no1seman** [tarantool/cartridge#1347]
Since frontend-core scm-1 has methods to add, replace or remove front-end modules (https://github.com/tarantool/frontend-core/commit/a8ee33cbf40fe3e873376b6aec4bc0c251f90c12) there must be a mechanism to inform WebUI page to update or reload  front-end module div or whole page. As for now any frontend changes that was made on backend needs manual browser page reload for changes to be applied. Another words Cartridge UI doesn't comply with WISYWIG principles.
For example if smbd make changes of failover config using graphQL or lua API to see changes in WebUI have to reload page in browser.

**Comment by yngvar-antonsson** [comment]
Closed in favor of #1182
