### ISSUE TITLE
Global cluster lock

### ISSUE THREAD

**Issue by olegrok** [tarantool/cartridge#1354]
There are several cases when we run some dangerous operations on cluster e.g. migrations.
This time it's quite important to ban new config apply operation, buckets transfer and so on.

Currently it's so tricky to implement because of failover - we should distinguish such cases - when we manually apply config or failover triggered.

Also helpers to prevent rebalansing are required (seems such functions are implemented in recent vshard update - https://github.com/tarantool/vshard/commit/3b5657fb9bd328263bd5989f744446f7f374a7c6#diff-fdc167c087c06890e9344af61862d7557635799ecbdfccb9a10545697dc7b9c0)

So I suggest to generalize task, discuss with customers and implement some cluster lock to execute some dangerous long process.

**Comment by Gerold103** [comment]
I want to warn you - `vshard.storage.ref` is an internal module. It is not documented, and is not available via any public API. That means you should not use it if you don't want to have issues with upgrade when I will change something in the module.

**Comment by olegrok** [comment]
Yes, thanks for your comment. I know it. I created an issue to vshard reposiotry - https://github.com/tarantool/vshard/issues/270 to make this API public.

**Comment by filonenko-mikhail** [comment]
It seems that this is architecture feature, which can't be done easily now. Gently closing.
