### ISSUE TITLE
API to add app_version and show it in Cartridge UI

### ISSUE THREAD

**Issue by no1seman** [tarantool/cartridge#1367]
As for now Cartridge shows 2 versions in Server details dialog in UI: The Tarantool version and Cartridge version, but there is another one version need to be shown - Application version.
Suggested solution:
Cartridge have to safely require VERSION.lua (see https://github.com/tarantool/cartridge-cli/issues/528) from the root of the app, save return value to _G.app_version and add Application version to Server details dialog in UI.

**Comment by filonenko-mikhail** [comment]
RFC:
- сделать своё приложение на cartridge (cartridge create)
- собрать запустить
- разобраться как генерируется версия (спойлер через git tag)
- упаковать приложение
  - установить в любую чистую систему
  - увидеть где там приехала версия самого приложение
- вернуться своим вниманием в картридж фреймворк
- и в сам cartridge фреймворк добавить require версии приложения
- фреймворк должен предположить, что его использует приложение и у этого приложения есть версия (и вот её надо во фреймворке зареквайрить)
- сделать graphql ендпоинт для этого

**Comment by no1seman** [comment]
@filonenko-mikhail Все проще чем кажется! В 2.10 cartridge-cli уже генерируется VERSION.lua (https://github.com/tarantool/cartridge-cli/pull/561)

Все что хотелось бы - вытащить версию в Server Details если pcall(require('VERSION.lua')) вернул что-то

**Comment by no1seman** [comment]
Точнее так:
local app_version = select(2, pcall(require, 'VERSION')) or 'unknown'
rawset(_G, '_APP_VERSION', app_version)
и потом уже _G._APP_VERSION про кинуть на фронт

**Comment by opomuc** [comment]
Кажется это нужная вещь. постоянно спрашивают как определить версиюю в WebUI...

**Comment by yngvar-antonsson** [comment]
Fronterd in #1686
