### ISSUE TITLE
Provide proxy module to be able to stop input requests during config apply

### ISSUE THREAD

**Issue by olegrok** [tarantool/cartridge#1371]
A problem statement:

During config apply we can create spaces, indexes and so on. This changes are quite dangerous because
our cluster could be in inconsistent state. Single way to eliminate a problem is apply config without any yield.
But it seems impossible in our applications.

Actually I propose to provide some wrapper for functions that will stop all input requests during config apply.
This logic seems should be quite simple implemented using conditional variable. However, I write this issue to cartridge repository for following reasons:
- Cartridge has some implicit steps that could yield
- User could write buggy code that fails with OperationError. In such way we won't have any ways to remove this lock back.

So seems such wrappers is needed only for vshard/netbox calls. rpc calls could be stopped directly on the cartridge level.

**Comment by filonenko-mikhail** [comment]
The definitely like.

The things that I start to feel, that cluster user experience is the follow. There are several cluster life rhythms.
- The birth — first bootstraping cluster
- The mladenchestvo — light business crud operations
- The otrochestvo — business crud operations, topology reconfiguration, failover enabling, leader switching, no many data
- The unost' — the solving env restrictions, more shards, more routers, bucket rebalancing, better failover

At the unost' cluster more frequently stuck on 2pc locked, or some node blinking in suspect, or role operation error, or duplicate key exists (when eventual failover changes master inconsistenly).
 
The thing is that at any time of life there is no way to understand what current operation in cluster is:
- topology config applying
- failover enabling
- switchover
- vshard rebalancing
- business crud traffic
- etc

The best way is that allow such user actions only at strongly separated stages.

**Comment by filonenko-mikhail** [comment]
Seems that box.cfg{read_only=true} can be the fast solution

**Comment by R-omk** [comment]
Related https://github.com/tarantool/cartridge/issues/1411

**Comment by filonenko-mikhail** [comment]
So this time the task is complex to solve with simple solution. Gently closing.
