### ISSUE TITLE
Introduce a way for http cookie customization — LDAP related

### ISSUE THREAD

**Issue by olegrok** [tarantool/cartridge#1427]
https://github.com/tarantool/cartridge/blob/0775e7870a4fbb993e55d538509eba0b471474af/cartridge/auth.lua#L190-L198

Unfortunately, it's not enough in some cases. E.g. if I use custom backend I want to add some custom payload to cookie - role, email and so on. When user is stored in some external system we could check login and password in check_password callback and fetch user's data.
But when user comes to us with cookie we know only username - it's not enough to fetch additional data. So it's a reason why I should do it on "check_password" step and embed it into cookie.

Current way to resolve an issue:
 - cache it locally (but cookie will work only with instance where user got this cookie)
 - export user data and save it to some instance (also looks bad - it's also a cache and I don't understand how to invalidate it).

**Comment by filonenko-mikhail** [comment]
It is required for case when user log in in one node, and than want's to go to other node webui and other node can't go to ldap without password.

**Comment by filonenko-mikhail** [comment]
The idea is to make jwt token with additional info

**Comment by filonenko-mikhail** [comment]
Unfortunately no current plan for such feature. Cartridge is not powerful web framework. Much gently closing.
