### ISSUE TITLE
Config Files

### ISSUE THREAD

**Issue by sharonovd** [tarantool/cartridge#143]
In GitLab by @KlonD90 on Jul 29, 2019, 12:32

GUI config files with explorer.

- Tree explorer
- Add file
- Edit file
- Global Save button

**Comment by sharonovd** [comment]
In GitLab by @KlonD90 on Jul 29, 2019, 12:37

changed the description

**Comment by rosik** [comment]
Related to #320

**Comment by rosik** [comment]
Resolved by #402 and #408
