### ISSUE TITLE
Investigate high CPU usage upon resharding

### ISSUE THREAD

**Issue by rosik** [tarantool/cartridge#1435]

**Comment by filonenko-mikhail** [comment]
There is parallel vshard bucket sending process since some version

**Comment by olegrok** [comment]
> There is parallel vshard bucket sending process since some version

https://github.com/tarantool/vshard/releases/tag/0.1.11 / https://github.com/tarantool/vshard/commit/b9dc5fef12cf3a67519244de126890832399e962

**Comment by rosik** [comment]
Recently on the customer's side, we've discovered that the rebalancing process is quite expensive. The receiving storage used to consume about 120% CPU and was nearly unresponsive.

Now we've reproduced it in the local lab.

![image](https://user-images.githubusercontent.com/2205188/122102025-a60a5300-ce1d-11eb-90b3-ace70bf37726.png)

```console
> vshard.storage.internal.current_cfg.rebalancer_max_receiving
---
- 100
...

```

### Single storage profile

![image](https://user-images.githubusercontent.com/2205188/122102825-89bae600-ce1e-11eb-8219-d261e2af9399.png)

### Storage with 2 replicas

It's much like the one above, but has an additional region for the relay.
![image](https://user-images.githubusercontent.com/2205188/122102852-92abb780-ce1e-11eb-8fb1-648691fdee88.png)

### Conclusion

Most of the workload is a low-level tarantool operation. There're no significant parts to be optimized in Cartridge or TDG.

I would recommend fine-tuning `rebalancer_max_receiving` when necessary

```lua
require('cartridge.vshard-utils').edit_vshard_options('default', {
    rebalancer_max_receiving = 5
})
```

**Comment by rosik** [comment]
Interactive svg: [perf.svg.zip](https://github.com/tarantool/cartridge/files/6725425/perf.svg.zip)
