### ISSUE TITLE
Implement configuration multitenancy

### ISSUE THREAD

**Issue by olegrok** [tarantool/cartridge#1439]
For some cases it would be great to preserve _several_ configuration instances. That means that different roles should have ability to work in several instances in scope of single replicaset. Externally it looks like different users/groups/... share single cluster.

My minds are following:
  - Cartridge supports several instances of clusterwide configuration.
  - Cartridge checks inconsistency between such configuration instances, suggest to reapply configuration for each tenant individually.
  - For the sake of backward compatibility we have default/main tenant that works as now.
  - Another tenants have the same abilities/flow - validate_config/apply_config/... but roles of each tenant work independently each other.
  - __Only main tenant__ can change topology (it acts as admin)
  - After toplogy change we reapply configuration for each tenant (otherwise new roles won't initialized on instances)

Such functionality could be implemented separately on the top of cartridge. But proper solution requires cartridge reimplementation on the top on cartridge. Seems reasonable to do it just inside cartridge.

**Comment by filonenko-mikhail** [comment]
This time it's really hard to say how to support tenants. I do not think that multitenancy is a good idea with coop multitasking.
