### ISSUE TITLE
[RFC] External config/topology storage support + internal `topology` module refactoring

### ISSUE THREAD

**Issue by artur-barsegyan** [tarantool/cartridge#1457]
### Мотивация

Мы хотим поддержать возможность работы с топологией и конфигом в Cartridge без 100% кворума в кластере. Для этого необходимо использовать внешнее хранилища конфига, типа etcd/consul. 

[Попытки подумать в сторону](https://github.com/tarantool/cartridge/issues/50#issuecomment-657483215
) без внешнего хранилища уже были, но идти в ту сторону не решились.

При этом есть условие: мы хотим чтобы пользователи vshard и пользователи Cartridge для этой задачи пользовались единым инструментом. Для этого мы сделали модули `topology` и модуль `conf`.

Самым очевидным решением кажется, встроить эти модуль в Cartridge и заменить при этом встроенный модуль `topology`. 

### Что хотим сделать в рамках тикета?
- [ ] **(prio.1)** Описать какие конкретные шаги нам нужно предпринять, чтобы интегрировать модули в Cartridge в упрощеном варианте, без поддержки внешнего хранилища. Это нужно на случай, если мы решим не идти в сторону внешнего хранилища конфига на данном этапе 
https://github.com/tarantool/cartridge/issues/1458
- [ ] Решить, как использовать двухфазный коммит при работе с внешним хранилищем
- [ ] Описать, как изменится поведение механизма ролей при работе с внешним хранилищем 
- [ ] Описать конкретные шаги по рефакторингу Cartridge, чтобы поддержать возможность работы с внешним хранилищем

**Comment by filonenko-mikhail** [comment]
К сожалению, сейчас это представляется мало возможным. Каждый из пунктов несет в себе риск изменение семантики. В случае изменения семантики, это требует четких шагов миграций, тестирование и прочих вещей.
Вежливо прикрываю тикет, чтобы сосредоточить внимание на более простых вопросах.
