### ISSUE TITLE
☂️ Make Cartridge modular

### ISSUE THREAD

**Issue by artur-barsegyan** [tarantool/cartridge#1458]
### Мотивация

Cartridge сейчас довольно сложный и крупный. Хочется сделать его модульным, чтобы можно было переиспользовать его компоненты и разрабатывать их в параллель от основной команды. 

### Статус и подзадачи

В данном зонтичном тикете предлагается выделить подзадачи по модуляризации и обсуждать прогресс работы над ними.

- Начать мы решили с модуля `topology` #1457

**Comment by filonenko-mikhail** [comment]
К сожалению прямо сейчас это сложный движ. Требуется кадровый ресерч, где как и какую роль ответственности займет.
Сейчас необходимо переоценить стоимость маентенанса каржа в таком виде в каком он есть.
Gently closing now.
