### ISSUE TITLE
[2pt] The list of roles for a replica set does not change without hard refresh in webUi

### ISSUE THREAD

**Issue by vanyarock01** [tarantool/cartridge#1489]
We added a new replicaset with an empty list of roles and a new cartridge role during one deploy. The cluster page in the Chrome browser was opened in advance.
But it was not possible to apply the new role to the new (or any other) replicaset - it was not in the list of available roles.
The ctrl + f5 helped.

Cartridge ver. 2.6.0

**Comment by filonenko-mikhail** [comment]
## Repro

- Close repo
- Build
```
cartridge build
```
- Start
```
cartridge start
```
- Open webui, push Configure button on server
- See that there is role `myrole`
- Ctrl+C in cartridge start
- Comment 'mymodule' string in `test/entrypoint/src_basic.lua` in 160
- `cartridge start`
- Goto webui, there is still myrole in dialog.
- The web reload fix such inconsistence

**Comment by OlgaYakovleva** [comment]
Verified with scenario described by @filonenko-mikhail
