### ISSUE TITLE
[2pt] Setup snapshot testing 

### ISSUE THREAD

**Issue by rosik** [tarantool/cartridge#1499]
There're many places that snapshot testing could help with. See, for example, https://github.com/tarantool/cartridge/issues/1201.

See also https://docs.cypress.io/guides/tooling/visual-testing

**Comment by rosik** [comment]
Here are more details of what should be tested first:

1. Every page with the minimal setup: dashboard, users, config, code
2. Issue described in #1201 is still relevant for the code page.

 I guess the snapshot testing could be integrated into existing tests. Creating new specs isn't necessary (but I may be wrong). If it's true, a single snapshot check could replace a bunch of assertions.

**Comment by yngvar-antonsson** [comment]
Closed in #1620
