### ISSUE TITLE
[1pt] Fix JavaScript warnings

### ISSUE THREAD

**Issue by yngvar-antonsson** [tarantool/cartridge#1524]
JavaScript files produce warnings in CI:
https://github.com/tarantool/cartridge/actions/runs/1116134987

**Comment by usenko-timur** [comment]
It seems that the issue is not relevant.
I have fixed similar problems in other commits.

**Comment by usenko-timur** [comment]
https://github.com/tarantool/cartridge/actions/runs/1389599633
as an example
