### ISSUE TITLE
[1pt] How to find out the HTTP port of cluster instances in webUI

### ISSUE THREAD

**Issue by vanyarock01** [tarantool/cartridge#1527]
### Problem
The cluster webUI does not have information about the HTTP ports that the cluster instances are listening on.

### Motivation
While working with an application, there is often a need to go to the webUI of a specific instance and, for example, view metrics or go to other http endpoints. To do this now, you either need to guess the HTTP port of the desired host or get it in some other way.

**Comment by olegrok** [comment]
Related to https://github.com/tarantool/cartridge/issues/622

**Comment by yngvar-antonsson** [comment]
In #1598 we've add http_port, http_host and webui prefix in GraphQL.

**Comment by filonenko-mikhail** [comment]
Добавить во server details в general

**Comment by panticonur** [comment]
{
    servers {
        boxinfo { 
          general  {
                   http_port
                   http_host
                   webui_prefix
             }
         }
    }
}
