### ISSUE TITLE
LuajitError: not enough memory on routers

### ISSUE THREAD

**Issue by erachenko23** [tarantool/cartridge#1549]
Tarantool: 2.7.2-0-g4d8c068
Cartridge: 2.7.0

We observe unstable working of some routers (roles: failover-coordinator | vshard-router | app.roles.handlers | app.roles.http_rotes | crud-router). On the "Lua Runtime" graph, we see increase of utilization in the interval of several minutes. When the value hits in bound limit (2Gb) router application crashed.

![image](https://user-images.githubusercontent.com/43468129/131795132-709d87b0-5077-4e4f-bf94-a22e2317e375.png)

How can I fix this error? It is possible to increase the lua runteime limit?

Error logs in attachement. [s1_routers_err.log](https://github.com/tarantool/cartridge/files/7096765/s1_routers_err.log)

**Comment by rosik** [comment]
> How can I fix this error?

It's OOM (out-of-memory), you can only investigate and eliminate the cause.

> It is possible to increase the lua runteime limit?

No, it can't. It's a basic architectural restriction of LuaJIT. IMO it's not what you need. Better investigate the source of the memory leak.
