### ISSUE TITLE
Bugs are in need to be fixed after changing colors

### ISSUE THREAD

**Issue by OlgaYakovleva** [tarantool/cartridge#1591]
1. Иконка авторизованного пользователя красного цвета (в правом верхнем углу окна)
![image](https://user-images.githubusercontent.com/86589970/139837958-0f01701a-ba9a-41a9-aff6-3c9d7bd1327b.png)
**Сценарий**: 
* сделать активной старинцу Users;
* залогиниться под одним из существующих пользователей, либо создать нового и зайти под ним;
**Некорректное поведение**: иконка перед полным имененм залогиненного пользователя красного цвета
**Ожидамые поведение**: иконка должна быть синего цвета

2. Окно авторизации пользователя имеет старый дизайн
![image](https://user-images.githubusercontent.com/86589970/139838883-ccbc6954-63b9-4957-bec1-4de129b76e23.png)
**Сценарий**:
* залогиниться существующим пользователем;
* перевести в состояние Enabled авторизацию обязательную;
* сделать Logout
**Некорректное поведение**: окно авторизации имеет старый дизайн
**Ожидаемый результат**: окно авторизации должно иметь синее цветовое решение

3. На странице Code выделенная схема должна иметь индикатор синего цвета, а не красного, как сейчас
![image](https://user-images.githubusercontent.com/86589970/139850339-f5190e74-e7d4-4540-bb42-bb7f8d57e95e.png)

**Comment by usenko-timur** [comment]
Fixed https://github.com/tarantool/cartridge/pull/1578/commits/706f96ccf806c2d887827f4fce4e66e3ae375b89
