### ISSUE TITLE
Allow to redefine vshard router boostrapping code in the vshard-router role

### ISSUE THREAD

**Issue by Totktonada** [tarantool/cartridge#1606]
I want to get rid of this call:

https://github.com/tarantool/cartridge/blob/01faba0362b107d94f1a4445e7e42477e2ccae9b/cartridge/roles/vshard-router.lua#L169

And place my own one to assign bucket ranges to storages manually. I need this to guarantee stability of the bucket_id -> replicaset mapping in tarantool/crud tests. See https://github.com/tarantool/crud/issues/235 for details.

It works now, but leans on stability of `pairs()` iteration over a table, which, in turn, is not guaranteed. I think the issue may be considered with low priority.

**Comment by filonenko-mikhail** [comment]
Dont to you want to monkeypatch vshard router bootstrap function?

**Comment by filonenko-mikhail** [comment]
So the motivation is to make cartridge code complex to make something hardcoded test more hardcoded. Seems that already exists hardcode is evaluated the same from time to time because all data hardcoded and all algorythms hardcoded.
Much gently closing.

**Comment by Totktonada** [comment]
Sorry, I missed your question.

I want to call my own bootstrap function instead of the default one. From cartridge I want ability to pass my own function instead of default vshard's `bootstrap()`, nothing more.

**Comment by Totktonada** [comment]
It seems, I can replace `vshard.router.bootstrap()` via `vshard.router.internal.router_mt`. Didn't check ATM, just looked at the code.
