### ISSUE TITLE
[2pt] Investigate the interface to work in a small resolution (1260x760)

### ISSUE THREAD

**Issue by usenko-timur** [tarantool/cartridge#1608]

**Comment by OlgaYakovleva** [comment]
![UsersPage 1260x760 snap](https://user-images.githubusercontent.com/86589970/144836709-31a8e7a9-d5dd-4ad1-93d8-3156e3b72305.png)

**Comment by OlgaYakovleva** [comment]
![FailoverModalEvantualEtcd 1260x760 snap](https://user-images.githubusercontent.com/86589970/144837037-64d9f467-ca5d-4fb0-b639-d90d28d61a46.png)

**Comment by OlgaYakovleva** [comment]
Need to do selected element readable
![image](https://user-images.githubusercontent.com/86589970/145063318-1e714dbd-2e16-4635-b9b6-95933b70c9aa.png)

With collapsed menu too
![image](https://user-images.githubusercontent.com/86589970/145063434-31f3243b-93e1-4e8f-9056-043c6dc4bff7.png)

**Comment by usenko-timur** [comment]
This element is not supposed to be readable.
I can remove it, and that will increase the space for the code.

@filonenko-mikhail @Katedraw What do you think about this?

**Comment by Katedraw** [comment]
I agree, we have to remove it. 

@usenko-timur
