### ISSUE TITLE
[1pt] UI: Absent space between instance name and `LEADER` sign

### ISSUE THREAD

**Issue by no1seman** [tarantool/cartridge#1624]
No space between instance name and `LEADER` sign in instance details in new design:

![image](https://user-images.githubusercontent.com/17825302/144976914-ed1ab9ef-a4ba-45d0-876b-4d7f9705bd92.png)

**Comment by usenko-timur** [comment]
@OlgaYakovleva 
It looks like this has already been fixed, needs to be rechecked.

**Comment by OlgaYakovleva** [comment]
Now there is the other view 
![image](https://user-images.githubusercontent.com/86589970/147695844-71ee828a-aacc-4607-9a6f-0321a846d7e1.png)

Closing as not existing problem any more
