### ISSUE TITLE
Support Etcd V3

### ISSUE THREAD

**Issue by yngvar-antonsson** [tarantool/cartridge#1625]
We should support Etcd v3 API in Cartridge Stateful Failover
From https://etcd.io/docs/v3.5/op-guide/configuration/ :

--enable-v2 'false'
  Accept etcd V2 client requests. Deprecated and to be decommissioned in v3.6.
--v2-deprecation 'not-yet'
  Phase of v2store deprecation. Allows to opt-in for higher compatibility mode.
  Supported values:
    'not-yet'                // Issues a warning if v2store have meaningful content (default in v3.5)
    'write-only'             // Custom v2 state is not allowed (planned default in v3.6)
    'write-only-drop-data'   // Custom v2 state will get DELETED !
    'gone'                   // v2store is not maintained any longer. (planned default in v3.7)

**Comment by filonenko-mikhail** [comment]
Let's close now to decrease infonoise.

**Comment by opomuc** [comment]
This is an odd statement since etcd v2 will be deprecated in near future? maybe reopen?

**Comment by theonedemon** [comment]
please reopen issue
