### ISSUE TITLE
Change color of the LEADER label in the "Edit replica set" form (from red to blue)

### ISSUE THREAD

**Issue by OlgaYakovleva** [tarantool/cartridge#1634]
![image](https://user-images.githubusercontent.com/86589970/146185114-87e02efb-9edc-476d-a18a-264b45076ab5.png)

**Comment by filonenko-mikhail** [comment]
So, crown color is svetofor for semantic:
- halt (red)
- work with issues (yellow)
- work good (green)

We think to keep it this way.
Gently closing.
