### ISSUE TITLE
Make the button "Apply" in the "Failover control" form unavaliable when there is any error

### ISSUE THREAD

**Issue by OlgaYakovleva** [tarantool/cartridge#1635]
![image](https://user-images.githubusercontent.com/86589970/146185331-d4f07733-0cdb-4cee-9895-047c76a1212c.png)

**Comment by filonenko-mikhail** [comment]
So, we have to investigate this question very much because form validation semantic is a deep deeeep deeeeep hole of rabbit. Gently closing. But keep question in mind.
