### ISSUE TITLE
[4pt] After redesign got very strange stats on cluster page

### ISSUE THREAD

**Issue by no1seman** [tarantool/cartridge#1655]
on Version; 2.7.3-40-g59d39522 on my test cluster got the following:
![image](https://user-images.githubusercontent.com/17825302/147348591-89753da3-84e2-4ff8-88aa-cc4ddf38cef0.png)

Cluster have:

- 3 replicasets (seems OK)
- 7 instances - theres no such total in new design
- 1 server (host) - threre is no in totals in new design

Seems that must bs fixed because we have to easily find out:

- number of replicasets in cluster
- number of instances in cluster
- number of unhealthy instances in cluster
- number of unhealthy replicasets in cluster

As for now we can't get this info

**Comment by filonenko-mikhail** [comment]
<img width="1507" alt="image" src="https://user-images.githubusercontent.com/370551/147551311-711ae86a-24d6-4813-8506-a3ceab82d29f.png">

**Comment by filonenko-mikhail** [comment]
<img width="1507" alt="image" src="https://user-images.githubusercontent.com/370551/147551812-77fbe10a-5a71-4e48-939f-6ab141d7ceac.png">

**Comment by Katedraw** [comment]
@no1seman @filonenko-mikhail @usenko-timur 

![TTC_Main page_Cluster_compact_1](https://user-images.githubusercontent.com/67949016/149087112-8f292334-62cd-4eb4-b50a-5cf444fd2a74.png)

**Comment by no1seman** [comment]
@Katedraw In terms of functionality - OK, in terms of design - all markers are different in taste and color.

**Comment by Katedraw** [comment]
@no1seman Did I understand you correctly?

![TTC_Main page_Cluster_compact_1](https://user-images.githubusercontent.com/67949016/149150717-879d7473-7254-4c6b-8afd-ed55956c0e3a.png)

**Comment by no1seman** [comment]
I like both versions

**Comment by Katedraw** [comment]
@usenko-timur  as I know, the second version easier to develop.

**Comment by usenko-timur** [comment]
> @usenko-timur as I know, the second version easier to develop.

@Katedraw yes

**Comment by filonenko-mikhail** [comment]
Like second version
