### ISSUE TITLE
fluking test vshard_test

### ISSUE THREAD

**Issue by filonenko-mikhail** [tarantool/cartridge#1683]
```
./test/upgrade/tarantool_upgrade_test.lua:63: Tarantool version should be greater 2.0
407
=========================================================
408

409
Tests with errors:
410
------------------
411

412
1) integration.vshard.test_bucket_ref_on_replica_prevent_bucket_move
413
./test/integration/vshard_test.lua:105: attempt to index field 'test' (a nil value)
414
stack traceback:
415
	./test/integration/vshard_test.lua:103: in function 'integration.vshard.test_bucket_ref_on_replica_prevent_bucket_move'
416
	...
417
	[C]: in function 'xpcall'
418

```

**Comment by yngvar-antonsson** [comment]
Tests with an unexpected success:
404
-------------
405

406
1) integration.vshard.test_bucket_ref_on_replica_prevent_bucket_move
407
Test fails until tarantool/vshard#173 will be fixed
408

409

410
Captured stdout:
411
single-storage-1 | 2021-12-29 11:34:59.478 [7435] main/139/localhost:13304 (net.box) I> connected to localhost:13304
412
single-storage-1 | 2021-12-29 11:34:59.478 [7435] main/137/vshard.rebalancer I> The cluster is balanced ok. Schedule next rebalancing after 3600.000000 seconds
413
router-1 | 2021-12-29 11:34:59.537 [7411] main/160/http/127.0.0.1:44362 twophase.lua:497 W> Updating config clusterwide...
414
router-1 | 2021-12-29 11:34:59.538 [7411] main/160/http/127.0.0.1:44362 twophase.lua:373 W> (2PC) patch_clusterwide upload phase...
415
router-1 | 2021-12-29 11:34:59.544 [7411] main/160/http/127.0.0.1:44362 twophase.lua:386 W> (2PC) patch_clusterwide prepare phase...
416
router-1 | 2021-12-29 11:34:59.549 [7411] main/160/http/127.0.0.1:44362 twophase.lua:395 W> Prepared for patch_clusterwide at localhost:13301
417
router-1 | 2021-12-29 11:34:59.549 [7411] main/160/http/127.0.0.1:44362 twophase.lua:395 W> Prepared for patch_clusterwide at localhost:13302
418
router-1 | 2021-12-29 11:34:59.549 [7411] main/160/http/127.0.0.1:44362 twophase.lua:395 W> Prepared for patch_clusterwide at localhost:13303
419
router-1 | 2021-12-29 11:34:59.549 [7411] main/160/http/127.0.0.1:44362 twophase.lua:395 W> Prepared for patch_clusterwide at localhost:13304
420
router-1 | 2021-12-29 11:34:59.549 [7411] main/160/http/127.0.0.1:44362 twophase.lua:419 W> (2PC) patch_clusterwide commit phase...
421
storage-1 | 2021-12-29 11:34:59.551 [7419] main/147/main I> Backup of active config created: "/tmp/tmp.cartridge.gk5qAWQEZ9Zq/localhost-13302/config.backup"
422
storage-1 | 2021-12-29 11:34:59.551 [7419] main/147/main I> Instance state changed: RolesConfigured -> ConfiguringRoles
423
storage-1 | 2021-12-29 11:34:59.551 [7419] main/147/main I> connecting to 2 replicas
424
storage-1 | 2021-12-29 11:34:59.551 [7419] main/147/main C> failed to connect to 2 out of 2 replicas
425
storage-1 | 2021-12-29 11:34:59.552 [7419] main/147/main C> leaving orphan mode
426
storage-1 | 2021-12-29 11:34:59.552 [7419] main/147/main I> set 'replication' configuration option to ["admin@localhost:13302","admin@localhost:13303"]
427
storage-1 | 2021-12-29 11:34:59.552 [7419] main/147/main I> Failover disabled
428
storage-1 | 2021-12-29 11:34:59.553 [7419] main/147/main I> Reconfiguring vshard.storage...
429
storage-1 | 2021-12-29 11:34:59.553 [7419] main/147/main I> Starting reconfiguration of replica d7e1359b-e77e-46fd-84e2-8376972d9157
430
storage-1 | 2021-12-29 11:34:59.553 [7419] main/147/main I> I am master
431
storage-1 | 2021-12-29 11:34:59.553 [7419] main/147/main I> connecting to 2 replicas
432
storage-1 | 2021-12-29 11:34:59.553 [7419] main/147/main C> failed to connect to 2 out of 2 replicas
433
storage-1 | 2021-12-29 11:34:59.553 [7419] main/147/main C> leaving orphan mode
434
storage-1 | 2021-12-29 11:34:59.553 [7419] main/147/main I> set 'replication' configuration option to ["admin@localhost:13303","admin@localhost:13302"]
435
storage-1 | 2021-12-29 11:34:59.553 [7419] main/147/main I> Box has been configured
436
storage-1 | 2021-12-29 11:34:59.554 [7419] main/167/lua I> Old replicaset and replica objects are outdated.
437
storage-1 | 2021-12-29 11:34:59.558 [7419] main/147/main I> --- apply_config({is_master = true})
438
storage-1 | 2021-12-29 11:34:59.558 [7419] main/147/main I> Roles configuration finished
439
storage-1 | 2021-12-29 11:34:59.558 [7419] main/147/main I> Instance state changed: ConfiguringRoles -> RolesConfigured
440
storage-1 | 2021-12-29 11:34:59.558 [7419] relay/127.0.0.1:55538/101/main coio.cc:379 !> SystemError unexpected EOF when reading from socket, called on fd 1395, aka 127.0.0.1:13302, peer of 127.0.0.1:55538: Broken pipe
441
storage-1 | 2021-12-29 11:34:59.558 [7419] relay/127.0.0.1:55538/101/main C> exiting the relay loop
442
storage-1 | 2021-12-29 11:34:59.559 [7419] main/165/applier/admin@localhost:13302 I> remote master d7e1359b-e77e-46fd-84e2-8376972d9157 at 127.0.0.1:13302 running Tarantool 2.8.3
443
storage-1 | 2021-12-29 11:34:59.559 [7419] main/165/applier/admin@localhost:13302 C> leaving orphan mode
444
storage-2 | 2021-12-29 11:34:59.551 [7427] main/122/main I> Backup of active config created: "/tmp/tmp.cartridge.gk5qAWQEZ9Zq/localhost-13303/config.backup"
445
storage-2 | 2021-12-29 11:34:59.551 [7427] main/122/main I> Instance state changed: RolesConfigured -> ConfiguringRoles
446
storage-2 | 2021-12-29 11:34:59.551 [7427] main/122/main I> connecting to 2 replicas
447
storage-2 | 2021-12-29 11:34:59.551 [7427] main/122/main C> failed to connect to 2 out of 2 replicas
448
storage-2 | 2021-12-29 11:34:59.551 [7427] main/122/main C> leaving orphan mode
449
storage-2 | 2021-12-29 11:34:59.551 [7427] main/122/main I> set 'replication' configuration option to ["admin@localhost:13302","admin@localhost:13303"]
450
storage-2 | 2021-12-29 11:34:59.551 [7427] main/122/main I> Failover disabled
451
storage-2 | 2021-12-29 11:34:59.552 [7427] main/122/main I> Reconfiguring vshard.storage...
452
storage-2 | 2021-12-29 11:34:59.552 [7427] main/122/main I> Starting reconfiguration of replica 0b185aab-a6f0-480c-be29-afa0d9213374
453
storage-2 | 2021-12-29 11:34:59.552 [7427] main/122/main I> connecting to 2 replicas
454
storage-2 | 2021-12-29 11:34:59.552 [7427] main/122/main C> failed to connect to 2 out of 2 replicas
455
storage-2 | 2021-12-29 11:34:59.552 [7427] main/122/main C> leaving orphan mode
456
storage-2 | 2021-12-29 11:34:59.552 [7427] main/122/main I> set 'replication' configuration option to ["admin@localhost:13303","admin@localhost:13302"]
457
storage-2 | 2021-12-29 11:34:59.552 [7427] main/122/main I> Box has been configured
458
storage-2 | 2021-12-29 11:34:59.553 [7427] main/162/lua I> Old replicaset and replica objects are outdated.
459
storage-2 | 2021-12-29 11:34:59.562 [7427] main/122/main I> --- apply_config({is_master = false})
460
storage-2 | 2021-12-29 11:34:59.562 [7427] main/122/main I> Roles configuration finished
461
storage-2 | 2021-12-29 11:34:59.562 [7427] main/122/main I> Instance state changed: ConfiguringRoles -> RolesConfigured
462
single-storage-1 | 2021-12-29 11:34:59.552 [7435] main/133/main I> Backup of active config created: "/tmp/tmp.cartridge.gk5qAWQEZ9Zq/localhost-13304/config.backup"
463
single-storage-1 | 2021-12-29 11:34:59.553 [7435] main/133/main I> Instance state changed: RolesConfigured -> ConfiguringRoles
464
single-storage-1 | 2021-12-29 11:34:59.554 [7435] main/133/main I> Failover disabled
465
single-storage-1 | 2021-12-29 11:34:59.554 [7435] main/133/main I> Reconfiguring vshard.storage...
466
single-storage-1 | 2021-12-29 11:34:59.554 [7435] main/133/main I> Starting reconfiguration of replica cccccccc-cccc-0000-0000-000000000001
467
single-storage-1 | 2021-12-29 11:34:59.554 [7435] main/133/main I> I am master
468
single-storage-1 | 2021-12-29 11:34:59.554 [7435] main/133/main I> Box has been configured
469
single-storage-1 | 2021-12-29 11:34:59.556 [7435] main/140/lua I> Old replicaset and replica objects are outdated.
470
single-storage-1 | 2021-12-29 11:34:59.556 [7435] main/133/main I> Wakeup rebalancer
471
storage-1 | 2021-12-29 11:34:59.563 [7419] main/166/applier/admin@localhost:13303 I> remote master 0b185aab-a6f0-480c-be29-afa0d9213374 at 127.0.0.1:13303 running Tarantool 2.8.3
472
single-storage-1 | 2021-12-29 11:34:59.565 [7435] main/133/main I> --- apply_config({is_master = true})
473
single-storage-1 | 2021-12-29 11:34:59.565 [7435] main/133/main I> Roles configuration finished
474
single-storage-1 | 2021-12-29 11:34:59.565 [7435] main/133/main I> Instance state changed: ConfiguringRoles -> RolesConfigured
475
storage-2 | 2021-12-29 11:34:59.566 [7427] relay/127.0.0.1:57642/101/main coio.cc:379 !> SystemError unexpected EOF when reading from socket, called on fd 1404, aka 127.0.0.1:13303, peer of 127.0.0.1:57642: Broken pipe
476
storage-2 | 2021-12-29 11:34:59.566 [7427] relay/127.0.0.1:57642/101/main C> exiting the relay loop
477
storage-2 | 2021-12-29 11:34:59.566 [7427] main/160/applier/admin@localhost:13302 I> remote master d7e1359b-e77e-46fd-84e2-8376972d9157 at 127.0.0.1:13302 running Tarantool 2.8.3
478
storage-2 | 2021-12-29 11:34:59.566 [7427] main/161/applier/admin@localhost:13303 I> remote master 0b185aab-a6f0-480c-be29-afa0d9213374 at 127.0.0.1:13303 running Tarantool 2.8.3
479
storage-2 | 2021-12-29 11:34:59.567 [7427] main/161/applier/admin@localhost:13303 C> leaving orphan mode
480
storage-2 | 2021-12-29 11:34:59.567 [7427] main/122/main I> subscribed replica d7e1359b-e77e-46fd-84e2-8376972d9157 at fd 1403, aka 127.0.0.1:13303, peer of 127.0.0.1:57670
481
storage-2 | 2021-12-29 11:34:59.567 [7427] main/122/main I> remote vclock {1: 3046} local vclock {1: 3046}
482
storage-2 | 2021-12-29 11:34:59.567 [7427] main/160/applier/admin@localhost:13302 I> authenticated
483
storage-1 | 2021-12-29 11:34:59.567 [7419] main/166/applier/admin@localhost:13303 I> authenticated
484
storage-1 | 2021-12-29 11:34:59.567 [7419] main/166/applier/admin@localhost:13303 I> subscribed
485
storage-1 | 2021-12-29 11:34:59.567 [7419] main/166/applier/admin@localhost:13303 I> remote vclock {1: 3046} local vclock {1: 3046}
486
storage-1 | 2021-12-29 11:34:59.567 [7419] main/166/applier/admin@localhost:13303 I> RAFT: message {term: 1, state: follower} from 2
487
storage-1 | 2021-12-29 11:34:59.568 [7419] main/169/vshard.rebalancer_applier I> Apply rebalancer routes with 1 workers:
488
storage-1 | ---
489
storage-1 | cccccccc-0000-0000-0000-000000000000: 1500
490
storage-1 | ...
491
storage-1 | 
492
storage-1 | 2021-12-29 11:34:59.568 [7419] main/169/vshard.rebalancer_applier I> Rebalancer workers have started, wait for their termination
493
storage-1 | 2021-12-29 11:34:59.568 [7419] main/145/main I> subscribed replica 0b185aab-a6f0-480c-be29-afa0d9213374 at fd 1395, aka 127.0.0.1:13302, peer of 127.0.0.1:55566
494
storage-1 | 2021-12-29 11:34:59.568 [7419] main/145/main I> remote vclock {1: 3046} local vclock {1: 3046}
495
router-1 | 2021-12-29 11:34:59.568 [7411] main/146/main I> Backup of active config created: "/tmp/tmp.cartridge.gk5qAWQEZ9Zq/localhost-13301/config.backup"
496
router-1 | 2021-12-29 11:34:59.568 [7411] main/146/main I> Instance state changed: RolesConfigured -> ConfiguringRoles
497
router-1 | 2021-12-29 11:34:59.568 [7411] main/146/main I> Failover disabled
498
router-1 | 2021-12-29 11:34:59.568 [7411] main/146/main I> Reconfiguring vshard-router/default ...
499
router-1 | 2021-12-29 11:34:59.568 [7411] main/146/main I> Starting router configuration
500
router-1 | 2021-12-29 11:34:59.568 [7411] main/146/main I> Calling box.cfg()...
501
router-1 | 2021-12-29 11:34:59.568 [7411] main/146/main I> {"read_only":false}
502
router-1 | 2021-12-29 11:34:59.568 [7411] main/146/main I> Box has been configured
503
router-1 | 2021-12-29 11:34:59.568 [7411] main/161/lua I> Old replicaset and replica objects are outdated.
504
router-1 | 2021-12-29 11:34:59.568 [7411] main/146/main I> --- apply_config({is_master = true})
505
router-1 | 2021-12-29 11:34:59.568 [7411] main/146/main I> Roles configuration finished
506
2021-12-29 11:35:23.399 [3180] main I> tx_binary: stopped
507
router-1 | 2021-12-29 11:34:59.568 [7411] main/146/main I> Instance state changed: ConfiguringRoles -> RolesConfigured
508
router-1 | 2021-12-29 11:34:59.569 [7411] main/160/http/127.0.0.1:44362 twophase.lua:428 W> Committed patch_clusterwide at localhost:13301
509
router-1 | 2021-12-29 11:34:59.569 [7411] main/160/http/127.0.0.1:44362 twophase.lua:428 W> Committed patch_clusterwide at localhost:13302
510
router-1 | 2021-12-29 11:34:59.569 [7411] main/160/http/127.0.0.1:44362 twophase.lua:428 W> Committed patch_clusterwide at localhost:13303
511
router-1 | 2021-12-29 11:34:59.569 [7411] main/160/http/127.0.0.1:44362 twophase.lua:428 W> Committed patch_clusterwide at localhost:13304
512
router-1 | 2021-12-29 11:34:59.569 [7411] main/160/http/127.0.0.1:44362 twophase.lua:573 W> Clusterwide config updated successfully
513
storage-2 | 2021-12-29 11:34:59.568 [7427] main/160/applier/admin@localhost:13302 I> subscribed
514
storage-2 | 2021-12-29 11:34:59.568 [7427] main/160/applier/admin@localhost:13302 I> remote vclock {1: 3046} local vclock {1: 3046}
515
storage-2 | 2021-12-29 11:34:59.568 [7427] main/160/applier/admin@localhost:13302 I> RAFT: message {term: 1, state: follower} from 1
516
storage-2 | 2021-12-29 11:34:59.569 [7427] relay/127.0.0.1:57670/101/main I> recover from `/tmp/tmp.cartridge.gk5qAWQEZ9Zq/localhost-13303/00000000000000000040.xlog'
517
single-storage-1 | 2021-12-29 11:34:59.569 [7435] main/137/vshard.rebalancer I> Rebalance routes are sent. Schedule next wakeup after 10.000000 seconds
518
storage-1 | 2021-12-29 11:34:59.570 [7419] main/168/applierw/admin@localhost:13303 C> leaving orphan mode
519
storage-1 | 2021-12-29 11:34:59.571 [7419] main/171/localhost:13304 (net.box) I> connected to localhost:13304
520
storage-1 | 2021-12-29 11:34:59.571 [7419] relay/127.0.0.1:55566/101/main I> recover from `/tmp/tmp.cartridge.gk5qAWQEZ9Zq/localhost-13302/00000000000000000000.xlog'
521
storage-2 | 2021-12-29 11:34:59.573 [7427] main/163/applierw/admin@localhost:13302 C> leaving orphan mode
522

523

524
Ran 386 tests in 295.732 seconds, 384 successes, 1 xfail, 1 xsuccess, 1 skipped

**Comment by yngvar-antonsson** [comment]
Still fluking.

**Comment by filonenko-mikhail** [comment]
Still flucky with xsuccess.
