### ISSUE TITLE
Shortcut to switch all shards masters to another DC

### ISSUE THREAD

**Issue by sharonovd** [tarantool/cartridge#17]
In GitLab by @sharonovd on Oct 31, 2018, 12:05

Might be useful when switching the whole cluster to another DC (E. g. in some kind of emergency).

Must available both from console and UI.

**Comment by sharonovd** [comment]
In GitLab by @sharonovd on Oct 31, 2018, 12:05

changed the description

**Comment by sharonovd** [comment]
In GitLab by @rosik on Jan 10, 2019, 15:56

mentioned in commit bbcc8c94dd8b10e6fa1c6f3dcf3267d4d187456b

**Comment by sharonovd** [comment]
In GitLab by @sharonovd on Jul 4, 2019, 14:55

removed milestone

**Comment by filonenko-mikhail** [comment]
So, the thing will be done in stand-in cluster feature. Gently closing.
