### ISSUE TITLE
Allow provide vshard config options

### ISSUE THREAD

**Issue by negasus** [tarantool/cartridge#174]
Allow provide vshard options, for example:
- rebalancer_max_receiving

**Comment by Satbek** [comment]
Now user can set only bucket_count for all cluster or for a specific vshard-group. If param not set in vshard-group then will be used default param from main cartridge cfg.

For example:
```lua
cartridge.cfg({
    bucket_count = 20000,
    vshard_groups = {
        -- both notations are valid
        ['cold'] = {bucket_count = 2000},
        'hot', --bucket_count == 2000
    },
    roles = {
        'cartridge.roles.vshard-storage',
        'cartridge.roles.vshard-router',
    },
})
```
I suggest to provide the following options:
- collect_bucket_garbage_interval
- collect_lua_garbage
- sync_timeout
- rebalancer_disbalance_threshold
- rebalancer_max_receiving

And add ability to set them in the same way as bucket_count.

**Comment by rosik** [comment]
We've got 2 main sources of configuration values:

1. `cartridge.cfg()` and argparse params, which are then inherited by clusterwide config.
2. clusterwide config itself, which is usually edited with graphql or lua api

Will it be enough if we only add these options to the clusterwide config?
I'd like to avoid overloading `cartridge.cfg()` with additional options without a need.

The default values are already set by vshard, and cartridge could provide an API like this:

```graphql
mutation {
    cluster {
        edit_vshard_group_params(name: "default", rebalancer_max_receiving: 42)
    }
}
```

@negasus @sharonovd @knazarov your opinion?

**Comment by negasus** [comment]
It allow edit this options from Cartridge UI?

**Comment by sharonovd** [comment]
> We've got 2 main sources of configuration values:
> 
> 1. `cartridge.cfg()` and argparse params, which are then inherited by clusterwide config.
> 2. clusterwide config itself, which is usually edited with graphql or lua api
> 
> Will it be enough if we only add these options to the clusterwide config?
> I'd like to avoid overloading `cartridge.cfg()` with additional options without a need.
> 
> The default values are already set by vshard, and cartridge could provide an API like this:
> 
> ```graphql
> mutation {
>     cluster {
>         edit_vshard_group_params(name: "default", rebalancer_max_receiving: 42)
>     }
> }
> ```
> 
> @negasus @sharonovd @knazarov your opinion?

If all these settings are dynamic - could be set without restart - looks legit.

**Comment by rosik** [comment]
> It allow edit this options from Cartridge UI?

Yes. It should be be implemented in two PRs - one for the backend, and another one on the front

**Comment by rosik** [comment]
> If all these settings are dynamic - could be set without restart - looks legit.

Yes, all of them are dynamic. https://www.tarantool.io/en/doc/2.2/reference/reference_rock/vshard/#configuration-reference

Also `rebalancer_max_sending` parameter should be added to the list after we update vshard to v0.1.11: https://github.com/tarantool/doc/issues/881
