### ISSUE TITLE
Change logo 

### ISSUE THREAD

**Issue by Katedraw** [tarantool/cartridge#1746]
Необходимо заменить два логотипа: в верхнем правом углу в меню, и иконка пользователя. Все актуальные лого в интерфейсах по ссылке. 
https://www.figma.com/file/3OjRxIHFdWw4pusVVsvsoJ/TT_-Cartridge?node-id=4535%3A0

В также макет: 
![TTC_Main page_Cluster_compact_1](https://user-images.githubusercontent.com/67949016/152935302-a3891642-9347-4a6c-8964-5a9571c87e3c.png)

**Comment by usenko-timur** [comment]
PRs:
 - https://github.com/tarantool/front-ui-kit/pull/291

**Comment by OlgaYakovleva** [comment]
Verified
