### ISSUE TITLE
argparse.lua: 244: attempt to index a nil value

### ISSUE THREAD

**Issue by awekening2** [tarantool/cartridge#1747]
Error parsing arguments when running Tarantool with argparse if run via systemctl
OS: Centos:7
Tarantool 2.8
Cartridge: 2.7.3

1) add `main.lua` to `/etc/tarantool/instances.available` with the following content:
```lua
package.path = '<path to cartridge rock>;' .. package.path

local argparse = require('cartridge.argparse')
local args, err = argparse.get_box_opts()
```
2) run tarantool with systemctl
```sh
service tarantool@main start
```

**Comment by filonenko-mikhail** [comment]
- `/etc/tarantool/instances.available` is used by tarantoolctl
- unfortunately cartridge argparse does not support starting under tarantoolctl 

Possible solutions is to use
- `builtin argparse`
- custom systemd unit file
