### ISSUE TITLE
Allow to change server.uri

### ISSUE THREAD

**Issue by vasiliy-t** [tarantool/cartridge#176]
### Problem statement

One should be able to change instance advertise uri (host/port/host+port) clusterwide. Instance identity (instance_uuid, replicaset_uuid) does not changes.

### Steps to reproduce:

1. Stop running instance

1. Start intance with new advertise uri

1. Call join_server mutation with new advertise uri 

1. Observe error ```config apply failed``` because of ```topology.server[instance_uuid].uri``` does not matches join_server uri parameter.

### Expected behavior

1. Stop running instance

1. Start instance with new advertise uri

1. Call join_server mutation with new advertise uri

1. topology.servers[instance_uuid].uri changes cluster wide, instance joins cluster

**Comment by rosik** [comment]
Resolved in #1036 #1037 #1024 #971
