### ISSUE TITLE
Maintenance case: clashing failover when same etcd

### ISSUE THREAD

**Issue by filonenko-mikhail** [tarantool/cartridge#1765]
## Repro
- setup cluster1
- setup cluster2
- setup stateful failover on each
  - use the same prefix

Got:   full readonly replicaset on one of clusters without properly initialisation (for e.g. without spaces)

Expected: error on validation or at near runtime.

**Comment by yngvar-antonsson** [comment]
We could add validation by a hash of cluster cookie
