### ISSUE TITLE
Используется только N символов куки

### ISSUE THREAD

**Issue by Thorwinz** [tarantool/cartridge#1768]
Tarantool 2.7.3-0-gdddf926
Цель: Linux-x86_64-RelWithDebInfo

Разворачиваем два отдельных кластера приложений. Разворачиваем через ansible, у каждого из кластеров свой картридж_cluster_cookie.

Проблема:
При развертывании второго кластера является первым (несмотря на то, что кластер-куки имеет значение!), и в конечном итоге не может второй кластер забутстрапиться.

фатальный: [node_1d -> tarXX-маршрутизатор]: FAILED! => {"changed": false, "msg": "Членство содержит экземпляр node_1b, который не описан в инвентаре"}

Выявлено:

Для пары:
msx-secret-cookie
msy-secret-cookie
Оба кластера успешно применяются

Для такой пары:
message-storage-x-secret-cookie
message-storage-y-secret-cookie
Происходит FAILED

Проверили куки обоих кластеров
```
cl = require('cartridge.cluster-cookie')
cl.cookie()

$ tarantoolctl connect admin:message-storage-x-secret-cookie@tarantool-2-6:3351
connected to tarantool-2-6:3351
tarantool-2-6:3351> cl = require('cartridge.cluster-cookie')
---
...

tarantool-2-6:3351> cl.cookie()
---
- message-storage-x-secret-cookie
...

tarantool-2-6:3351>
$ tarantoolctl connect admin:message-storage-y-secret-cookie@tarXX-router:3353
connected to tarXX-router:3353
tarXX-router:3353> cl = require('cartridge.cluster-cookie')
---
...

tarXX-router:3353> cl.cookie()
---
- message-storage-y-secret-cookie
...
```

**Comment by filonenko-mikhail** [comment]
Seems that memberhip encryption uses only first 32 symbols
https://github.com/tarantool/membership/blob/master/membership/options.lua#L81

**Comment by panticonur** [comment]
could not reproduce.

**Comment by Thorwinz** [comment]
Нее, так дело не пойдет. Прошу вернуть ишью в работу.

**Comment by filonenko-mikhail** [comment]
У нас есть ограничение для кластер куки в 32 символа. Кажется в то время это было сделано для скорости.
https://github.com/tarantool/membership/blob/master/membership/options.lua#L89

Как проверять эту ситуацию:
require("membership").get_encryption_key()

Если значение одинаковое кластера будут пересекаться
