### ISSUE TITLE
Check that hotreload fiber.kill make thing right aroung net.box worker fiber

### ISSUE THREAD

**Issue by filonenko-mikhail** [tarantool/cartridge#1780]
There is possible error:

```
builtin/box/net_box.lua:546: the fiber is dead
```

It happens when someone kill netbox under-kapot worker fiber in reconnect state.

There is cartridge hot-reload which can make fiber.kill on any not whitelisted fibers. Sooo, it can be a problem.

https://github.com/tarantool/cartridge/blob/master/cartridge/hotreload.lua#L171

**Comment by filonenko-mikhail** [comment]
So, it's possible to know net.box fiber with regexp `ip:port (net.box)`
Discussed solution to leave net.box fiber alive, and after parent fiber killed gc drop it.

**Comment by yngvar-antonsson** [comment]
I think, killing net box fibers could break hotreloading of modules. The better way is kill everything and start over if it's needed.

**Comment by yngvar-antonsson** [comment]
I think, killing net box fibers could break hotreloading of modules. The better way is kill everything and start over if it's needed.

**Comment by filonenko-mikhail** [comment]
So, such thing have to be done in core
