### ISSUE TITLE
Configuration checksum mismatch issue does not affect the `tnt_cartridge_issues` metric

### ISSUE THREAD

**Issue by hackallcode** [tarantool/cartridge#1787]
Open any instance in cluster, run this Lua code:

```lua
local confapplier = require('cartridge.confapplier')
local cfg = confapplier.get_active_config():copy()
cfg:set_plaintext('todo1.txt', '- Test config mismatch')
cfg:lock()
confapplier.apply_config(cfg)
```

This code creates configuration checksum mismatch issue, but `tnt_cartridge_issues` metric will be equal to 0.

**Comment by yngvar-antonsson** [comment]
@panticonur 
Steps to reproduce:

- create and bootstrap a cluster with metrics
- eval the code above 
- look at the metric  `tnt_cartridge_issues` with `warning` label

**Comment by yngvar-antonsson** [comment]
Checksum mismatch is a global issue. tarantool/metrics gathers only local issues (https://github.com/tarantool/metrics/issues/211). If you want to manage checksum mismatch, you need to create a custom metric.

**Comment by hackallcode** [comment]
Checksum mismatch is not a global issue! Each instance has own issues of checksum mismatch. So, it can be in tnt_cartridge_issues

**Comment by yngvar-antonsson** [comment]
It gathers in `list_on_cluster` function - https://github.com/tarantool/cartridge/blob/de24d66e4209134756d697a04dfefa11b5523216/cartridge/issues.lua#L529
tnt_cartridge_issues aggregates from `list_on_instance`
