### ISSUE TITLE
Cartridge must return a comprehensive error to the client if it is not yet configured

### ISSUE THREAD

**Issue by akudiyar** [tarantool/cartridge#1789]
Steps to reproduce:
 1. Setup a Cartridge cluster with some topology (instances.yml)
 2. Do not proceed to creating nodes and bootstrapping it
 3. Try to connect to a router node using any client (CLI or some connector like cartridge-java)

Actual behavior:
A strange confusing error occurs. In the case of CLI it just says "connection is not established", in the connector case you'll just get a request timeout.
In the Cartridge logs you'll see something like this:
```
testapp.router | 2022-04-02 15:51:04.660 [81411] main/113/remote_control/127.0.0.1:51352 remote-control.lua:323 E> RemoteControlError: ...idge/.rocks/share/tarantool/cartridge/remote-control.lua:246: bad argument #1 to 'unpack' (table expected, got nil)
```
This is because the `call` operation from the connector somehow ends up with passing a function call without arguments to the `remote_control.lua` which leads to the above error (this case needs to be fixed separately).

Expected behavior:
If a Cartridge cluster is not configured, any user operations with Cartridge CLI and function calls result with a comprehensive error returned to the client, like "Cluster is not yet configured, do this <...>"

**Comment by filonenko-mikhail** [comment]
So, remote control is net.box server which can make function calls and eval — it's the workaround to user unconfigured tarantool over the network.
Iproto defines that empty args have to be passed as empty array not null.
So, I cant make expected behavior. Much sorry. Gently closing.
