### ISSUE TITLE
Get rid about kuber rolling update

### ISSUE THREAD

**Issue by filonenko-mikhail** [tarantool/cartridge#1790]
There is case when:
- kuber starts container with cartridge app
- kuber wants to understand is app alive
- before it, kuber does not setup ip addr resolving
- cartridge wants to ip addr resolving before become alive

So, the problem is about «egg and chicken»

**Comment by R-omk** [comment]
We use rolling update and everything is working as it should.

To do this, you need to correctly configure the internal communication between the cluster pods and correctly configure readiness probe.


For this purpose we wrote  some small role:

<details>
  <summary>tarantool@app-db-storage-0-0:/cartridge/app/roles$ cat k8s-helpers.lua </summary>

  ```lua

local cartridge = require('cartridge')
local confapplier = require('cartridge.confapplier')

local function init(opts)

  local httpd = assert(cartridge.service_get('httpd'), "Failed to get httpd service")
  httpd:route({method = 'GET', path = '/readiness_probe'}, function()
    if confapplier.get_state() == 'RolesConfigured' then
      return { status = 200 }
    else
      return { status = 400 }
    end
  end)

  httpd:route({method = 'GET', path = '/liveness_probe'}, function()
    return { status = 200 }
  end)

  return true
end

local function stop()
  return true
end

local function validate_config(conf_new, conf_old)
  return true
end

local function apply_config(conf, opts)
  if opts.is_master then
    box.ctl.promote()
  end
  return true
end

return {
  role_name = 'app.roles.k8s-helpers',
  init = init,
  stop = stop,
  validate_config = validate_config,
  apply_config = apply_config,
}
  ```
</details>

-----


> before it, kuber does not setup ip addr resolving

solution: 

for Service
`publishNotReadyAddresses: true`  

for StatefulSet
```

  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
```


related issue: https://github.com/tarantool/tarantool-operator/issues/37

**Comment by filonenko-mikhail** [comment]
Thanks a lot for info sharing!

**Comment by filonenko-mikhail** [comment]
So, the task is to make and export http status endpoints:

```
httpd:route({method = 'GET', path = '/readiness_probe'}, function()
  if confapplier.get_state() == 'RolesConfigured' then
    return { status = 200 }
  else
    return { status = 400 }
  end
end)

httpd:route({method = 'GET', path = '/liveness_probe'}, function()
  return { status = 200 }
end)
```

**Comment by filonenko-mikhail** [comment]
So, we think that such probes have to be done at user application layer, not in framework.
