### ISSUE TITLE
Add availability to load roles in runtime

### ISSUE THREAD

**Issue by hackallcode** [tarantool/cartridge#1794]
In our project, we needed to add the ability to load roles through the clusterwide config.

To do this, we patched the `cartridge.roles.apply_config` function to add new roles through `cartridge.roles.cfg` before config applying.

Therefore, it would be nice to add functionality to register the user handler before apply config (and possibly validate config), similar to the `on_patch` handler.

I would also like to export `cartridge.roles.cfg` to the public API (maybe as `add_role` and `remove_role` functions).

**Comment by filonenko-mikhail** [comment]
Sorry no plans for such thing this time. Gently closing.
