### ISSUE TITLE
Enable SSL in Cartridge

### ISSUE THREAD

**Issue by yngvar-antonsson** [tarantool/cartridge#1838]
- [ ] Setup Cartridge cluster and enable SSL (probably we should use the latest vshard)
- [ ] Check that everything works fine (e.g. vshard calls)

**Comment by filonenko-mikhail** [comment]
Example:

```
box.cfg{listen={uri="127.0.0.1:3301", params={transport="ssl", ssl_cert_file="ssl_cert/server.crt", ssl_key_file="ssl_cert/server.key"}}}
```

**Comment by filonenko-mikhail** [comment]
Netbox the same thing:
```
c = netbox.connect({uri='127.0.0.1:3301', params={transport='ssl'}})
```

**Comment by filonenko-mikhail** [comment]
So, there are 3 places to reconfigure:
- box.cfg.listen
- net.box.connect
- box.cfg.replication
