### ISSUE TITLE
Bug in UI when expelling last instance

### ISSUE THREAD

**Issue by kluevandrew** [tarantool/cartridge#1839]
Steps to reproduce:
ReplicaSet with zero weight
With the last instance in it, of course it's the master
All bucket a gone
Click Expel button in UI 

Actual behavior:
We see a message that the instance has successfully expelled 
We see how the instance disappears from the table along with the ReplicaSet
Wait about a minute
We see how the instance and ReplicaSet reappeared in the UI

Workaround:
First disable the instance, then expel it

Expected behavior:
The Expel button is either not available, or it successfully expels the instance, or (worst case) when clicked, it says that you must first disable the instance

**Comment by AlexandrLitkevich** [comment]
Привет к сожалению не получилось воспроизвести баг, подскажи пожалуйста какая у тебя версия cartridge?

**Comment by kluevandrew** [comment]
По странному стечению обстоятельств я больше не могу повторить это баг, в текущий момент нормально отображается ошибка при попытке удаления последнего инстанса из репликасета

**Comment by filonenko-mikhail** [comment]
Ok максимально нежно закрываем, как только появится вновь — сразу же тотчас переоткроем
