### ISSUE TITLE
Switch from Raft failover to Stateful switch instances to ro

### ISSUE THREAD

**Issue by yngvar-antonsson** [tarantool/cartridge#1854]
Steps to reproduce:

- Setup cluster with Raft failover
- Change failover to Stateful 
- Instances switched to read-only mode

**Comment by yngvar-antonsson** [comment]
It's should be done in #1372.
Quick fix: call `box.ctl.promote()` on a new leader manually

**Comment by filonenko-mikhail** [comment]
Will be done in #1372
