### ISSUE TITLE
Disable checkbox all_rw in case of sync replication

### ISSUE THREAD

**Issue by filonenko-mikhail** [tarantool/cartridge#1861]
In case of sync replication, there is only one master at the moment. So we can provide for user all_raw flag. 
Consider to disable or hide this checkbox `all_rw` on edit replicaset dialog.

There are backend and frontend parts.

Backend have to provide graphql api about sync replication enabled/disabled.

**Comment by yngvar-antonsson** [comment]
Need to discuss it before doing.

**Comment by yngvar-antonsson** [comment]
We should write a test for it. It would be also useful for #1858
