### ISSUE TITLE
Need feature: Tarantool and Cartridge version in UI

### ISSUE THREAD

**Issue by a1div0** [tarantool/cartridge#1864]
It would be great to see the current version of Tarantool and Cartridge in the admin panel somewhere in the admin panel.

Now, in order to find out the version of the Tarantool -- you need to connect to one of the instances. And the Cartridge version - it's easier to go into the project and see the dependencies.
At the moment of incidents, it is a pity to waste time on this.

**Comment by filonenko-mikhail** [comment]
https://user-images.githubusercontent.com/370551/177943062-6e5fd62f-d460-45d6-af16-235f5c5e30e3.mov

**Comment by a1div0** [comment]
Thanks a lot!
