### ISSUE TITLE
Tarantool binds to 0.0.0.0 despite advertise_uri settings

### ISSUE THREAD

**Issue by donatengit** [tarantool/cartridge#1890]
Hi Guys,

Thanks for your work. We have a problem with our cartridge/tarantool setup: tarantool binds both tcp/udp to 0.0.0.0 despite _advertise_uri_ setting in local/instances.lua (ip address changed):

```no-vshard.master:
  advertise_uri: 10.31.200.1:3301
  http_port: 8081
  http_host: 10.31.200.1
```
I've checked opened ports
```
>> sudo netstat -tulnp | grep 3301
tcp        0      0 0.0.0.0:3301            0.0.0.0:*               LISTEN      1926351/tarantool i
```

and _nc -v some.public.domain 3301_ from outer internet
```
Connection to some.public.domain port 3301 [tcp/*] succeeded!
Tarantool 2.11.0 (Binary) ....
```

Other than adopting [this patch](https://github.com/tarantool/cartridge/commit/228b25e24f23e77885a8bfccaf3a75cce54ec74f) partially, we tried hardcoding bind IP address right in _.rocks/share/tarantool/cartridge/confapplier.lua_ i.e.:
_local ok, err = remote_control.bind('10.31.200.1', vars.binary_port)_

and got no luck. Even though it logs specified port
_no-vshard.master | 2022-08-16 16:26:35.651 [1236913] main/109/remote_control/10.31.200.1:3301 I> started_

NB with a specific IP address hardcode in _membership.lua_ for udp it binds properly.

No need to say, I believe, that there is a potential risk to expose all tarantool data to the outer world if for any reason firewall is misconfigured or disabled at some moment. And thus why wouldn't anyone want to have additional protection by forcing db to bind to local interfaces. Any advise?  

Versions: 

> cartridge --version
> Tarantool Cartridge CLI
>  Version:	2.12.1
>  OS/Arch: 	linux/amd64
>  Git commit:	af99c20

> tarantool --version
> Tarantool Enterprise 2.11.0-entrypoint-1-g16694464a-r489-nogc64
> Target: Linux-x86_64-RelWithDebInfo

**Comment by filonenko-mikhail** [comment]
reproduced
