### ISSUE TITLE
Recalculate leaders after enable raft failover mode

### ISSUE THREAD

**Issue by R-omk** [tarantool/cartridge#1900]
Steps to reproduce problem:

1. Run nodes with raft enabled (`--election-mode candidate`)
2. Launching the cartridge via `cartridge replicasets setup`

The cartridge is now running with disabled failover. 
The first host in the list is selected as non-readonly. 
if we now switch the failover mode to raft, then no matter which node is the leader, the first one from the list will still be selected as non-readonly, in this case, only the force promote can explicitly change the leader.

**Comment by R-omk** [comment]
If enable raft failover before the bootstrap, then the bootstrap will almost certainly fail. And in some replicasets it may pass or not, it leads to partial bootstrap.
It also happens that the "is_master" option pass into apply_config, although in fact the node is in readonly due to another node is the leader.

**Comment by filonenko-mikhail** [comment]
So, it's seems that enabling raft from other than cartridge have to be prohibited.

**Comment by R-omk** [comment]
leader should be computed here (same as raft_term) when raft failover is turning on

https://github.com/tarantool/cartridge/blob/ec98fb9f97f45d2440d84f001cdf7b1fcb6f6b47/cartridge/failover/raft.lua#L128-L130

**Comment by R-omk** [comment]
I believe that all raft data should always be stored to the payload  as one indivisible object  (term number and leader at the same time), otherwise this may lead to the fact that on different nodes the term may change independently of the others.

This can lead to the fact that **different nodes of the same term may contain outdated and different data** about the leader.

https://github.com/tarantool/cartridge/blob/8e40d18d6daa0457268367fe446922ff0d1f09e9/cartridge/failover/raft.lua#L45-L56
