### ISSUE TITLE
Compression frontend

### ISSUE THREAD

**Issue by filonenko-mikhail** [tarantool/cartridge#1913]
## Motivation

There is graphql endpoint to get info about field compressions. Info are about:

```
- instance
  - space
    - field1: ratio
    - field2: ratio
  - space
    - field11: ratio
    - field222: ration
```

The task is to show info block with such info to user:

> Fields <name (30%), ...> in space <space_name> on instance <instance_id> can be compressed

**Comment by artur-barsegyan** [comment]
Мне кажется, что уточнение 
> "...on instance <instance_id> "

здесь лишнее. 

Мы если понимаем, что какое-то поле сжимается, то предлагаем сразу сжать его во всем кластере. Соответственно сообщение вижу здесь: 
> "Поле <name> в спейсе <space_name> может быть сжато на X%"

**Comment by usenko-timur** [comment]
<img width="1042" alt="image" src="https://user-images.githubusercontent.com/88880786/205335425-b3aabdb7-c6f2-4134-86da-309ddc08ba54.png">
