### ISSUE TITLE
Consider to create security hook for graphql endpoint

### ISSUE THREAD

**Issue by filonenko-mikhail** [tarantool/cartridge#1934]
## Motivation

There is case when someone wants to restrict access to some cartridge graphql endpoints. Consider to make a configurable hook to provide such functionality.

It is already possible:

```
graphql.on_resolve(function(operation, field_name) 
  if user restricted then
    error('restricted')
  end)
```

**Comment by NeraverinTarantool** [comment]
Task was done in TDG
