### ISSUE TITLE
Auto return of the master after the failover is triggered

### ISSUE THREAD

**Issue by a1div0** [tarantool/cartridge#1942]
# What are we doing?
This issue proposes a new feature for the failover-coordinator. The meaning of the feature is that the failover-coordinator would try to return the master back some time after the failover.

The feature should contain settings:
1. On/off
2. Time after which the system will try to return the master

The settings must be the same for the entire cluster, for all failover-coordinators. Settings should be placed here:
![image](https://user-images.githubusercontent.com/4862582/194851030-e05b3e43-37a9-439f-b2e8-3925c3878e99.png)

# What for?
It is necessary to reduce the traffic between data centers, in the case when the cluster is left without attention from the operation. This can happen at night and if only one instance fails.

# Posible work scenarios
It is proposed to implement one of two options for work.

## Option 1
The first scenario involves using "failover priority" - trying to switch to the first line of this list.
![image](https://user-images.githubusercontent.com/4862582/194851123-7eeef68a-c97e-4230-a395-2625e8e1f67f.png)

## Option 2
The second scenario may be smarter. The mechanism may try to return the master to the shoulder with the most masters. Since the goal is to minimize traffic, this is preferable. If the master is already on the shoulder with a large number of masters, then it is enough to leave a record about this in the log file.

In addition, this will allow you to more easily perform a gree-blue deployment (on the shoulders).

**Comment by yngvar-antonsson** [comment]
Discussed with @filonenko-mikhail : we could periodically try to promote instances if leaders are not in the right places
