### ISSUE TITLE
vshard  bootstrap process fail if it called before the actual topology is applied.

### ISSUE THREAD

**Issue by R-omk** [tarantool/cartridge#1945]
After enabling a raft failover, it may happen that the apply config  has not had time to occur, as a result of which the bootstrap of vshard can fail on several or all replicasets.

We always start the bootstrap process automatically in tests and when deploying the application, so after successfully applying the failover config, the bootstrap process immediately starts. I think that the bootstrap call should correctly handle this situation.

related:
https://github.com/tarantool/cartridge/issues/1623

https://github.com/tarantool/cartridge/issues/1900

**Comment by filonenko-mikhail** [comment]
Could you please what is the reason to enable failover before bootstrap process on 2pc distributed config system?

**Comment by R-omk** [comment]
During the bootstrap process, changes occur in the schema and in the dataset.

I believe that before any changes, the system should set the integrity preservation mode (set up synchronous replication, leader election,  split brain detection, etc.) and only after that make any changes.

Even if you look at it from the other side, setting up a failover is a system configuration, and usually the configuration takes place before the product is used.

**Comment by filonenko-mikhail** [comment]
Do you want to temporary pause failover while vshard bootstrap?

**Comment by R-omk** [comment]
> Do you want to temporary pause failover

No, I want to use the built-in raft. It cannot be suspended.

In fact, this ticket is not about the failover.

There are several reasons why a node might be in read-only mode, 
but the cartridge does not respect all this, it only takes into account ro flag that it set itself.

For the same reason, it often happens that when a role's apply_config function is called, the is_master  flag  is set to true, although it is actually in read-only mode, but there the user code can handle this situation, however, in other system places we cannot handle this,  as a consequence, the code that expects the write mode is fail.

**Comment by filonenko-mikhail** [comment]
So, I think the support for failover and bootstrap process have to start in vshard.storage.force_bucket_create. Today, the solution is only to setup stable cluster state before bootstrap.
