### ISSUE TITLE
Edit auth params in UI

### ISSUE THREAD

**Issue by sharonovd** [tarantool/cartridge#195]
Currently auth parameters (cookie_max_age, cookie_renew_age) are editable via API only.

This is not very convenient.

It would be very nice to have an ability to edit them from UI too.

**Comment by rvrsrec** [comment]
Scenario:
- click button 'auth setting';
- opens a modal window with parameters.

![TT_U - Main page](https://user-images.githubusercontent.com/22233143/67761122-b48ed580-fa53-11e9-84cd-147b66f2f5d9.png)

![TT_U - Auth Settings](https://user-images.githubusercontent.com/22233143/67761125-b6589900-fa53-11e9-8317-4eb771e912e7.png)

**Comment by rosik** [comment]
Is it still relevant?

**Comment by filonenko-mikhail** [comment]
I think it's stale ticket. Feel free to reopen.
