### ISSUE TITLE
Broken process of leader choosing for bootstrap/recovery node

### ISSUE THREAD

**Issue by R-omk** [tarantool/cartridge#1964]
The most serious problem occurs when trying to recover a node **that is first in the leader order list**. Instead of a bootstrap from a snapshot received from another node of replicaset, a new one is created. (This leads to errors `XlogGapError: Missing .xlog file between LSN`)

There are two problems in the current implementation:
1. The algorithm relies on the fact that the leader really exists, but this is misleading because there is a moment when the leader is temporarily not elected.
2. In practice, the payload (line 484) of member from  membership sometimes does not have time to appear (even if leader exists), so more stringent checks are needed as a source of truth.

https://github.com/tarantool/cartridge/blob/c4dc808d943747b3dd3a7e349aa1b86a71116fe1/cartridge/confapplier.lua#L472-L503

In any case, it should be forbidden to chose yourself (line 502) for the bootstrap if it is known that there are other nodes in the replicaset that are already configured. (line 493)
(also, It should not run the recovered node in rw mode, only for first bootstrap it can be) line 503

It is possible for bootstrap (mostly recovery) to select all nodes in the replicaset, and not just one, this is especially true if raft is enabled.

---

**Steps to reproduce**

- create and bootstrap cluster (vshard storage+router) with disabled swim broadcast (_maybe it doesn't matter_)
- enable raft failover
- stop or kill first node from replicaset
- delete all data (snap, xlog, yaml config)
- start the stopped node again
- apply config on any other configured node in the cluster

**Comment by R-omk** [comment]
One more case.

kill and clear two nodes out of three at once, one of which was the leader.

Since the raft will not be able to elect a new leader, the remaining node store (in membership payload) uuid of the last leader.
During recover one of the cleaned nodes, the snapshot **will not be restored** from the last survivor.

---

I consider that during node recovery  (first box.cfg call) **election mode should not be disabled** (if cartridge failover is enabled in raft mode), now this is not the case.

I also consider that it is necessary to **specify all the nodes** in the replicaset in replication at once, and not try to guess which one to restore from.

**Comment by filonenko-mikhail** [comment]
Sooo, have no correct ideas to fix

**Comment by R-omk** [comment]
this works in my case, we can discuss and adapt if necessary.

https://github.com/R-omk/cartridge/commit/b0e717bbb15a4aaa550ce10409dc00aecb7d37f7?diff=split

**Comment by yngvar-antonsson** [comment]
@R-omk thank you for the patch! I think you should open a PR with your code and we can discuss it there.
Two notes:
1) We should consider moving new code under the feature flag 
2) Please write tests for your solution
