### ISSUE TITLE
Will be a multimaster?

### ISSUE THREAD

**Issue by hackallcode** [tarantool/cartridge#1965]
We have three data centers. Each of them has Tarantool and ETCD instances for stateful failover.
In one data center there is a Tarantool master, in others there is a replicas.
Suddenly, at the data center with the master the network breaks with the other two data centers, etcd in this data center loses quorum.

As a result, a new master will be selected in one of the two data centers (since there is a etcd quorum, but there is no master).

But will the previous master instance become a replica if it is left without a quorum?

**Comment by R-omk** [comment]
https://www.tarantool.io/en/doc/latest/book/cartridge/cartridge_api/modules/cartridge/#automatic-failover-management

Option `fencing_enabled`

**Comment by kyukhin** [comment]
Question answered.
