### ISSUE TITLE
Create FAQ 

### ISSUE THREAD

**Issue by artur-barsegyan** [tarantool/cartridge#205]
**The Tarantool team** has real wide expertise in `cartridge` industrial usage which should be presented to the general public. 

I think we need a separate wiki section for this. In that wiki we can create:

-  common mistakes and misleadings
-  cookbook pages about any activity related to `cartridge` usage 
-  deploy/management

**Comment by rosik** [comment]
> В части применения решения на tarantul, интересны возможности и ограничения решения при работе в геораспределенном кластере. Среди существенных ограничений является тот факт, что в настоящий момент решение СПМ работает на кворумной технологии(Sync). В части надёжности и производительности интересны следующие возможности и нюансы работы  tarantula
a.       Поведение tarantul в случае выключения одной из площадок геораспределенного кластера длительностью более 30 минут
b.       Поведение Tarantul в случае, когда обе площадки геораспределенного кластера доступны, но между площадками нарушено сетевое сообщение длительностью более 30 минут.
c.       Поведение Tarantul при хаотичном выходе из кластера разных нод.
d.       Инструменты восстановления “целостности в итоге” при разрешении конфликта при split brain
e.       Интересны инструменты  работы tarantula обеспечивающие отказоустойчивость решения и производительность, высокую доступность;

**Comment by rosik** [comment]
> Михаил Филоненко, [28.07.20 11:42]
Troubleshooting
 • bad argument opts.roles to cfg (table expected, got nil)
 • Не задан аргумент со список ролей в cartridge.cfg.
 • Role "iluvatar" method validate_config() returned nil
 • В функции validate_config необходимо вернуть логическое значение.
 • 'RemoteCallError: Role "iluvatar" has no method "get_history"'
 • Роль не экспортирует указанную функцию. Проверить что и функция создана и из модуля она возвращается.
 • Instance entering failed state: ConfiguringRoles -> OperationError
 • Исполнение кода роли apply_config привело к ошибке.
 • LoadConfigError: Error parsing section "iluvatar.yml"
 • Yaml синтаксическая ошибка в конфигурационном yml файле.
 • В GUI отсутствуют роли
 • Перезагрузить GUI страницу в браузере
 • Проверить результат local _, err = cartridge.cfg(...).
 • No remotes with role "iluvatar" available
 • Или различаются имена ролей
 • Или роль не назначена ни на одну ноду.
 • "RegisterRoleError: module 'vshard-storage' not found
 • Неправильно названа роль в списке зависимостей
 • Total active bucket count is not equal to total. Possibly a boostrap is not finished yet. Expected 2, but found 0
 • Нажать кнопку Bootstrap vshard в GUI
 • module 'cartridge' not found:No LuaRocks module found for cartridge
 • Проверить что cartridge установлен tarantoolctl rocks install cartridge
 • Или указан в зависимостях *.rock
 • Также проверить init.lua должен делать package.setsearchroot()
 • Не запускается сервис после деплоя ansible
 • Проверить package.setsearchroot()
 • Проверить .cartridge.ignore
 • Не переустанавливается rpm
 • Необходимо нарастить версию, или удалить версию и установить её вновь

**Comment by rosik** [comment]
Note: https://github.com/tarantool/cartridge/issues/926#issuecomment-665834096

**Comment by rosik** [comment]
> как с cartridge делать обновление кода без перезапуска тарантулов?
> как менять схему данных без остановки/перезапуска? (миграции)
> как админам всем этим управлять? (сейчас паппет скриптов готовых нет)
> https://stackoverflow.com/questions/63032418/deploy-two-tarantool-clusters-based-on-tarantool-cartridge-in-same-subnet

**Comment by filonenko-mikhail** [comment]
Closing. There is no movement this direction. There are trainings, incl cartridge. Feel free to reopen kindly.
