### ISSUE TITLE
Do not rely on `cluster uuid` log line in tests

### ISSUE THREAD

**Issue by Gerold103** [tarantool/cartridge#2058]
You have a test `integration/logger_test.lua` with this case: `g.test_content_bootstrapped()`. It checks that the logs contain the row `I> cluster uuid <uuid value>`. This line is here for now, but in 3.0 we want to replace it with `replicaset uuid <uuid value>`.

Please, update the test not to depend on this line. And whatever other places you might have like this.

**Comment by kyukhin** [comment]
We're not going to support Cartridge in Tarantool 3.0.
