### ISSUE TITLE
Изменить текст сообщения после нажатия на кнопку Suggestions

### ISSUE THREAD

**Issue by artur-barsegyan** [tarantool/cartridge#2071]
Сейчас текст сообщения не отражает возможные риски при запуске процедуры в проде. Надо бы подсветить. 
Предлагаю так:

> Далее вы сможете узнать: сколько места можно освободить в кластере, если сжать часть полей. Алгоритм вычисляет это на основе данных в кластере. 
>
> Данная процедура может часть узлов перевести в состояние "Unreachable" от нескольких секунд до нескольких минут. Это может создать авто-инцидент в вашей алерт системе. Чтобы этого не случилось, рекомендуется запускать процедуру во время технического окна.

**Comment by filonenko-mikhail** [comment]
Данный ворнинг должен появиться по нажатию на клавишу suggestion
