### ISSUE TITLE
RPC: cdata tuple returned when calling db locally

### ISSUE THREAD

**Issue by RunsFor** [tarantool/cartridge#208]
`cartridge.rpc` module provides a simple way to call functions on other instances. It uses `net.box` module internally. There are some optimisations inside such as not to call instance remotely if is possible to call locally. `netbox` has simple helper to this - `netbox.self`

However, there may be distinct effects when you are calling a database though netbox. I.e. `netbox.self` will not cast cdata tuple to table, but remote netbox call does. This brings user to following issues which are difficult to maintain:

Remote call:
```
localhost:3301> task = rpc.call('app.roles.event_queue', 'take', {3})
---
...

localhost:3301> type(task)
---
- table
...
```

Local call:

```
localhost:3302> task = rpc.call('app.roles.event_queue', 'take', {3})
---
...

localhost:3302> type(task)
---
- cdata
...
```

**Comment by RunsFor** [comment]
https://github.com/tarantool/tarantool/issues/4513

**Comment by RunsFor** [comment]
Created issue on tarantool repo https://github.com/tarantool/tarantool/issues/4513

**Comment by rosik** [comment]
Suppressed by #422. Use `{prefer_local = false}` if you want to avoid netbox.self
