### ISSUE TITLE
all instances exited

### ISSUE THREAD

**Issue by Radik3451** [tarantool/cartridge#2113]
executed
`cartridge create --name=...
cartridge build`
by doing
`cartridge create`
get this:
`myapp/tmp/run/myapp.router.control: No such file or directory
`
and so with each instance
`[36971] main F> fatal error, exiting the event loop
   • myapp-stateboard... EXITED
   ⨯ myapp-stateboard: Process exited: Exited unsuccessfully: exit status 1
   • myapp.s1-master... EXITED
   ⨯ myapp.s1-master: Process exited: Exited unsuccessfully: exit status 1
   • myapp.s1-replica... EXITED
   ⨯ myapp.s1-replica: Process exited: Exited unsuccessfully: exit status 1
   • myapp.s2-master... EXITED
   ⨯ myapp.s2-master: Process exited: Exited unsuccessfully: exit status 1
   • myapp.s2-replica... EXITED
   ⨯ myapp.s2-replica: Process exited: Exited unsuccessfully: exit status 1
   • myapp.router... EXITED
   ⨯ myapp.router: Process exited: Exited unsuccessfully: exit status 1
   ⨯ All instances exited  `

**Comment by yngvar-antonsson** [comment]
Hi @Radik3451 !
Please provide more details about this issue:
```bash
tarantool --version
cartridge --version # in created folder
cat myapp-scm-1.rockspec
```

And which platform do you use?

**Comment by Radik3451** [comment]
Hi @yngvar-antonsson !
`tarantool --version`
`Tarantool 2.11.0-0-g247a9a418
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_BACKTRACE=TRUE
Compiler: GNU-11.2.0
C_FLAGS:-g -O2 -ffile-prefix-map=/build/tarantool-2.11.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -fopenmp -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/build/tarantool-2.11.0=. -std=c11 -Wall -Wextra -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type
CXX_FLAGS:-g -O2 -ffile-prefix-map=/build/tarantool-2.11.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -fopenmp -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/build/tarantool-2.11.0=. -std=c++11 -Wall -Wextra -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type
`
`cartridge --version`
`Tarantool Cartridge CLI
 Version:	2.12.5
 OS/Arch: 	linux/amd64
 Git commit:	98ecccc

Tarantool Cartridge
 Version:	2.7.9-1
`
`cat myapp-scm-1.rockspec`
`package = 'myapp'
version = 'scm-1'
source  = {
    url = '/dev/null',
}
-- Put any modules your app depends on here
dependencies = {
    'tarantool',
    'lua >= 5.1',
    'checks == 3.2.0-1',
    'cartridge == 2.7.9-1',
    'metrics == 0.16.0-1',
    'cartridge-cli-extensions == 1.1.1-1',
}
build = {
    type = 'none';
}
`
I use Ubuntu 22.04

**Comment by yngvar-antonsson** [comment]
🧐 No idea for now. Please send logs from `cartridge log` command

And then try to update cartridge to the latest version:
1) in .rockspec file `'cartridge == 2.7.9-1'` -> `'cartridge == 2.8.0-1'`
2) `cartrdige build`

**Comment by Radik3451** [comment]
`myapp-stateboard | 2023-06-27 17:41:26.924 [157818] main/103/stateboard.init.lua/box.upgrade I> Recovering snapshot with schema version 2.11.0
myapp-stateboard | 2023-06-27 17:41:26.928 [157818] main/103/stateboard.init.lua I> update replication_synchro_quorum = 1
myapp-stateboard | 2023-06-27 17:41:26.929 [157818] main/103/stateboard.init.lua I> instance uuid 73cb5f7b-ed53-486c-ac59-9b0e423134bc
myapp-stateboard | 2023-06-27 17:41:26.929 [157818] main/103/stateboard.init.lua I> instance vclock {}
myapp-stateboard | 2023-06-27 17:41:26.929 [157818] main/103/stateboard.init.lua I> recovery start
myapp-stateboard | 2023-06-27 17:41:26.929 [157818] main/103/stateboard.init.lua I> recovering from `./00000000000000000000.snap'
myapp-stateboard | 2023-06-27 17:41:26.930 [157818] main/103/stateboard.init.lua I> cluster uuid b0d68617-4b39-4bca-b70f-a20542449b93
myapp-stateboard | 2023-06-27 17:41:26.957 [157818] main/103/stateboard.init.lua I> assigned id 1 to replica 73cb5f7b-ed53-486c-ac59-9b0e423134bc
myapp-stateboard | 2023-06-27 17:41:26.958 [157818] main/103/stateboard.init.lua I> update replication_synchro_quorum = 1
myapp-stateboard | 2023-06-27 17:41:26.959 [157818] main/103/stateboard.init.lua I> ready to accept requests
myapp-stateboard | 2023-06-27 17:41:26.959 [157818] main/103/stateboard.init.lua I> leaving orphan mode
myapp-stateboard | 2023-06-27 17:41:26.959 [157818] main/104/gc I> wal/engine cleanup is resumed
myapp-stateboard | 2023-06-27 17:41:26.960 [157818] main/105/checkpoint_daemon I> scheduled next checkpoint for Tue Jun 27 18:59:54 2023
myapp-stateboard | 2023-06-27 17:41:26.960 [157818] main utils.c:610 E> LuajitError: builtin/box/console.lua:937: Usage: console.listen("[host:]port")
myapp-stateboard | 2023-06-27 17:41:26.960 [157818] main F> fatal error, exiting the event loop
myapp.router | 2023-06-27 17:41:26.837 [157807] main/103/init.lua/membership I> Membership BROADCAST sent to 127.0.0.1:3301
myapp.router | 2023-06-27 17:41:26.837 [157807] main/103/init.lua/membership I> Membership BROADCAST sent to 192.168.0.255:3301
myapp.router | 2023-06-27 17:41:26.839 [157807] main/103/init.lua/membership I> Membership BROADCAST sent to 172.17.255.255:3301
myapp.router | 2023-06-27 17:41:26.840 [157807] main/103/init.lua/membership I> Membership BROADCAST sent to 172.18.255.255:3301
myapp.router | 2023-06-27 17:41:26.840 [157807] main/103/init.lua/membership I> Membership BROADCAST sent to 127.0.0.1:3300
myapp.router | 2023-06-27 17:41:26.841 [157807] main/103/init.lua/membership I> Membership BROADCAST sent to 192.168.0.255:3300
myapp.router | 2023-06-27 17:41:26.842 [157807] main/103/init.lua/membership I> Membership BROADCAST sent to 172.17.255.255:3300
myapp.router | 2023-06-27 17:41:26.842 [157807] main/103/init.lua/membership I> Membership BROADCAST sent to 172.18.255.255:3300
myapp.router | 2023-06-27 17:41:26.844 [157807] main/107/http/0.0.0.0:8081/socket I> started
myapp.router | 2023-06-27 17:41:26.845 [157807] main/103/init.lua/cartridge I> Listening HTTP on 0.0.0.0:8081
myapp.router | 2023-06-27 17:41:26.847 [157807] main utils.c:610 E> LuajitError: /home/radik/Рабочий стол/polygon/myapp/init.lua:48: ConsoleListenError: unix/:/home/radik/Рабочий стол/polygon/myapp/tmp/run/myapp.router.control: No such file or directory
myapp.router | stack traceback:
myapp.router | 	...�ол/polygon/myapp/.rocks/share/tarantool/cartridge.lua:829: in function 'cfg'
myapp.router | 	/home/radik/Рабочий стол/polygon/myapp/init.lua:39: in main chunk
myapp.router | 2023-06-27 17:41:26.848 [157807] main F> fatal error, exiting the event loop
myapp.s1-master | 2023-06-27 17:41:27.127 [157816] main/103/init.lua/membership I> Membership BROADCAST sent to 127.0.0.1:3301
myapp.s1-master | 2023-06-27 17:41:27.128 [157816] main/103/init.lua/membership I> Membership BROADCAST sent to 192.168.0.255:3301
myapp.s1-master | 2023-06-27 17:41:27.128 [157816] main/103/init.lua/membership I> Membership BROADCAST sent to 172.17.255.255:3301
myapp.s1-master | 2023-06-27 17:41:27.129 [157816] main/103/init.lua/membership I> Membership BROADCAST sent to 172.18.255.255:3301
myapp.s1-master | 2023-06-27 17:41:27.130 [157816] main/103/init.lua/membership I> Membership BROADCAST sent to 127.0.0.1:3302
myapp.s1-master | 2023-06-27 17:41:27.131 [157816] main/103/init.lua/membership I> Membership BROADCAST sent to 192.168.0.255:3302
myapp.s1-master | 2023-06-27 17:41:27.132 [157816] main/103/init.lua/membership I> Membership BROADCAST sent to 172.17.255.255:3302
myapp.s1-master | 2023-06-27 17:41:27.133 [157816] main/103/init.lua/membership I> Membership BROADCAST sent to 172.18.255.255:3302
myapp.s1-master | 2023-06-27 17:41:27.135 [157816] main/107/http/0.0.0.0:8082/socket I> started
myapp.s1-master | 2023-06-27 17:41:27.137 [157816] main/103/init.lua/cartridge I> Listening HTTP on 0.0.0.0:8082
myapp.s1-master | 2023-06-27 17:41:27.138 [157816] main utils.c:610 E> LuajitError: /home/radik/Рабочий стол/polygon/myapp/init.lua:48: ConsoleListenError: unix/:/home/radik/Рабочий стол/polygon/myapp/tmp/run/myapp.s1-master.control: No such file or directory
myapp.s1-master | stack traceback:
myapp.s1-master | 	...�ол/polygon/myapp/.rocks/share/tarantool/cartridge.lua:829: in function 'cfg'
myapp.s1-master | 	/home/radik/Рабочий стол/polygon/myapp/init.lua:39: in main chunk
myapp.s1-master | 2023-06-27 17:41:27.138 [157816] main F> fatal error, exiting the event loop
myapp.s1-replica | 2023-06-27 17:41:26.867 [157809] main/103/init.lua/membership I> Membership BROADCAST sent to 127.0.0.1:3301
myapp.s1-replica | 2023-06-27 17:41:26.868 [157809] main/103/init.lua/membership I> Membership BROADCAST sent to 192.168.0.255:3301
myapp.s1-replica | 2023-06-27 17:41:26.868 [157809] main/103/init.lua/membership I> Membership BROADCAST sent to 172.17.255.255:3301
myapp.s1-replica | 2023-06-27 17:41:26.869 [157809] main/103/init.lua/membership I> Membership BROADCAST sent to 172.18.255.255:3301
myapp.s1-replica | 2023-06-27 17:41:26.869 [157809] main/103/init.lua/membership I> Membership BROADCAST sent to 127.0.0.1:3304
myapp.s1-replica | 2023-06-27 17:41:26.870 [157809] main/103/init.lua/membership I> Membership BROADCAST sent to 192.168.0.255:3304
myapp.s1-replica | 2023-06-27 17:41:26.886 [157809] main/103/init.lua/membership I> Membership BROADCAST sent to 172.17.255.255:3304
myapp.s1-replica | 2023-06-27 17:41:26.887 [157809] main/103/init.lua/membership I> Membership BROADCAST sent to 172.18.255.255:3304
myapp.s1-replica | 2023-06-27 17:41:26.890 [157809] main/107/http/0.0.0.0:8083/socket I> started
myapp.s1-replica | 2023-06-27 17:41:26.893 [157809] main/103/init.lua/cartridge I> Listening HTTP on 0.0.0.0:8083
myapp.s1-replica | 2023-06-27 17:41:26.894 [157809] main utils.c:610 E> LuajitError: /home/radik/Рабочий стол/polygon/myapp/init.lua:48: ConsoleListenError: unix/:/home/radik/Рабочий стол/polygon/myapp/tmp/run/myapp.s1-replica.control: No such file or directory
myapp.s1-replica | stack traceback:
myapp.s1-replica | 	...�ол/polygon/myapp/.rocks/share/tarantool/cartridge.lua:829: in function 'cfg'
myapp.s1-replica | 	/home/radik/Рабочий стол/polygon/myapp/init.lua:39: in main chunk
myapp.s1-replica | 2023-06-27 17:41:26.894 [157809] main F> fatal error, exiting the event loop
myapp.s2-master | 2023-06-27 17:41:26.868 [157808] main/103/init.lua/membership I> Membership BROADCAST sent to 127.0.0.1:3301
myapp.s2-master | 2023-06-27 17:41:26.869 [157808] main/103/init.lua/membership I> Membership BROADCAST sent to 192.168.0.255:3301
myapp.s2-master | 2023-06-27 17:41:26.870 [157808] main/103/init.lua/membership I> Membership BROADCAST sent to 172.17.255.255:3301
myapp.s2-master | 2023-06-27 17:41:26.870 [157808] main/103/init.lua/membership I> Membership BROADCAST sent to 172.18.255.255:3301
myapp.s2-master | 2023-06-27 17:41:26.880 [157808] main/103/init.lua/membership I> Membership BROADCAST sent to 127.0.0.1:3304
myapp.s2-master | 2023-06-27 17:41:26.882 [157808] main/103/init.lua/membership I> Membership BROADCAST sent to 192.168.0.255:3304
myapp.s2-master | 2023-06-27 17:41:26.882 [157808] main/103/init.lua/membership I> Membership BROADCAST sent to 172.17.255.255:3304
myapp.s2-master | 2023-06-27 17:41:26.886 [157808] main/103/init.lua/membership I> Membership BROADCAST sent to 172.18.255.255:3304
myapp.s2-master | 2023-06-27 17:41:26.888 [157808] main/107/http/0.0.0.0:8084/socket I> started
myapp.s2-master | 2023-06-27 17:41:26.889 [157808] main/103/init.lua/cartridge I> Listening HTTP on 0.0.0.0:8084
myapp.s2-master | 2023-06-27 17:41:26.890 [157808] main utils.c:610 E> LuajitError: /home/radik/Рабочий стол/polygon/myapp/init.lua:48: ConsoleListenError: unix/:/home/radik/Рабочий стол/polygon/myapp/tmp/run/myapp.s2-master.control: No such file or directory
myapp.s2-master | stack traceback:
myapp.s2-master | 	...�ол/polygon/myapp/.rocks/share/tarantool/cartridge.lua:829: in function 'cfg'
myapp.s2-master | 	/home/radik/Рабочий стол/polygon/myapp/init.lua:39: in main chunk
myapp.s2-master | 2023-06-27 17:41:26.890 [157808] main F> fatal error, exiting the event loop
myapp.s2-replica | 2023-06-27 17:41:27.017 [157810] main/103/init.lua/membership I> Membership BROADCAST sent to 127.0.0.1:3301
myapp.s2-replica | 2023-06-27 17:41:27.017 [157810] main/103/init.lua/membership I> Membership BROADCAST sent to 192.168.0.255:3301
myapp.s2-replica | 2023-06-27 17:41:27.018 [157810] main/103/init.lua/membership I> Membership BROADCAST sent to 172.17.255.255:3301
myapp.s2-replica | 2023-06-27 17:41:27.018 [157810] main/103/init.lua/membership I> Membership BROADCAST sent to 172.18.255.255:3301
myapp.s2-replica | 2023-06-27 17:41:27.019 [157810] main/103/init.lua/membership I> Membership BROADCAST sent to 127.0.0.1:3305
myapp.s2-replica | 2023-06-27 17:41:27.020 [157810] main/103/init.lua/membership I> Membership BROADCAST sent to 192.168.0.255:3305
myapp.s2-replica | 2023-06-27 17:41:27.021 [157810] main/103/init.lua/membership I> Membership BROADCAST sent to 172.17.255.255:3305
myapp.s2-replica | 2023-06-27 17:41:27.022 [157810] main/103/init.lua/membership I> Membership BROADCAST sent to 172.18.255.255:3305
myapp.s2-replica | 2023-06-27 17:41:27.024 [157810] main/107/http/0.0.0.0:8085/socket I> started
myapp.s2-replica | 2023-06-27 17:41:27.026 [157810] main/103/init.lua/cartridge I> Listening HTTP on 0.0.0.0:8085
myapp.s2-replica | 2023-06-27 17:41:27.027 [157810] main utils.c:610 E> LuajitError: /home/radik/Рабочий стол/polygon/myapp/init.lua:48: ConsoleListenError: unix/:/home/radik/Рабочий стол/polygon/myapp/tmp/run/myapp.s2-replica.control: No such file or directory
myapp.s2-replica | stack traceback:
myapp.s2-replica | 	...�ол/polygon/myapp/.rocks/share/tarantool/cartridge.lua:829: in function 'cfg'
myapp.s2-replica | 	/home/radik/Рабочий стол/polygon/myapp/init.lua:39: in main chunk
myapp.s2-replica | 2023-06-27 17:41:27.027 [157810] main F> fatal error, exiting the event loop
   • myapp-stateboard... OK
   • myapp.router... OK
   • myapp.s1-master... OK
   • myapp.s1-replica... OK
   • myapp.s2-master... OK
   • myapp.s2-replica... OK
`

**Comment by yngvar-antonsson** [comment]
Glad to hear that!
Closed.
