### ISSUE TITLE
bug: unreleased lock during reapply config 

### ISSUE THREAD

**Issue by R-omk** [tarantool/cartridge#2132]
If an error occurs, the function exits without releasing the lock.

line 289
line 310

https://github.com/tarantool/cartridge/blob/97a4629dcbbef99183bb178d40db0c91417eff21/cartridge/twophase.lua#L286-L324

**Comment by d-enk** [comment]
> It's expected behaviour

After trying to call reapply,
for example, at the moment when the instance in `ConfiguringRoles` state,
the lock remains and the only way to remove it is to restart instance.
Doesn't seem like expected behavior
