### ISSUE TITLE
Support new vshard cfg parameters

### ISSUE THREAD

**Issue by RunsFor** [tarantool/cartridge#2185]
In the [version of 0.1.25](https://github.com/tarantool/vshard/releases/tag/0.1.25) vshard has introduced several new configuration options, such as `rebalancer`, `rebalancer_mode` and `identification_mode`.

It seems it is not possible right now to bypass these options to vshard:

https://github.com/tarantool/cartridge/blob/7ebaa1a690e1d9ee79d8143038decded62276a0a/cartridge/vshard-utils.lua#L548-L563

Could you please support it too, so I can configure those in vshard through cartridge cfg.

Thanks in advance!

**Comment by yngvar-antonsson** [comment]
We can't support `identification_mode` since cartridge doesn't have names for replicasets (and won't have).
I'll add `rebalancer` and `rebalancer_mode` to the settings.
