### ISSUE TITLE
Cartridge should handle http request auth by itself

### ISSUE THREAD

**Issue by knazarov** [tarantool/cartridge#219]
Currently application authors have to manually check user authorization on all incoming requests. This is not convenient, because they will have to handle many special cases, like cookie expiration. 

Instead of this, I propose that cartridge handles incoming http requests itself, checks if the user is authorized, and then calls any backend methods.

**Comment by rosik** [comment]
GraphQL handles auth errors as http status 200 + error message in json payload. It is incompatible with your proposal.

To simplify handling authentication there is a function `cartridge.auth.check_request(req)`:
https://github.com/tarantool/cartridge/blob/3d57bba6db54351306dd92dd68fce89491b7be87/cartridge/auth.lua#L638-L647

I suggest to focus on the API instead of designing implicit checks.

**Comment by rosik** [comment]
### Proposal

Let's implement the following API and make it public:

```lua
--- Authorize http request.
-- @returns true/false 
cartridge.auth_check_http_request(request)

--- Render http response.
-- Inject set-cookie headers into response in order to renew or reset the cookie.
-- @tparam ?table template
cartridge.auth_render_http_response(response)

--- Get username for the current HTTP session.
-- @return string or nil if no user is logged in
cartridge.auth_get_http_username()
```

`auth_check_http_request` already stores credentials in `fiber.storage`, and it'll also store set-cookie headers to be rendered later.

**Comment by knazarov** [comment]
Storing authorization in fiber.storage like you do is dangerous, because the other side can loose authorization. Think about nginx: it establishes one connection to your app, and then uses this connection to multiplex requests from different clients.

**Comment by rosik** [comment]
I'm handling this situation. Every new `authorize_request` (even within single session) resets `fiber.storage`.
