### ISSUE TITLE
Support "rebalancer_mode" and "rebalancer" options on web UI level

### ISSUE THREAD

**Issue by RunsFor** [tarantool/cartridge#2194]
There is new functionality in the [latest vshard versions](https://github.com/tarantool/vshard/releases/tag/0.1.25) - options, which controls the rebalancer behaviour.

In the #2186 it's been supported on backend level. Now it would be great to reflect these changes in the web UI.

I.e. it would be great to be able to:
- see/set rebalancer_mode option globally. It can be one of 3 options - `off`, `manual` or `auto`
- see/set rebalancer option for each replicaset/storage

**Comment by yngvar-antonsson** [comment]
I think we should alsp show rebalancer_enabled field on the main cluster page

**Comment by yngvar-antonsson** [comment]
1) `rebalancer_mode` on the same level as failover
Graphql request should be the same as the "change replicaset weight request"
2) `rebalancer` (true, false, null) on `edit replicaset` page and somewhere on edit server page, which we don't have.

```graphql
mutation($replicasets: [EditReplicasetInput]) {
  cluster {
    edit_topology(replicasets: $replicasets) {
      replicasets {
        uuid
        rebalancer
      }
    }
  }
}

----

replicasets = {{
    uuid = replicaset_uuid,
    rebalancer = true,
}}

```

```graphql
mutation($servers: [EditServerInput]) {
  cluster {
    edit_topology(servers: $servers){
      servers {
        uuid
        rebalancer
      }
    }
  }
}
---
 servers = {
    {uuid = uuid, rebalancer = true},
}
```
3) On the main page, near the instance nave we should see a pictogram of `rebalancer enabled`. 
```graphql
{
   servers {
     uri
     boxinfo {
       vshard_storage {
       rebalancer_enabled
     }
   }
 }
}
```
