### ISSUE TITLE
Show state provider status on cluster main page

### ISSUE THREAD

**Issue by yngvar-antonsson** [tarantool/cartridge#2200]
Basic design:

- it should look like replicaset frame
- shown only when failover mode is stateful 
- each stateprovider instance frame should have uri and status (OK/error)

Above "Replicasets" list
"Replicaset" name == State provider name (tarantool or etcd)
"Instance" name == State provider name (tarantool or etcd) + number of instance (e.g. tarantool-1, etcd-1)
"Instance" uri == URI from graphql request
"Instance" status == status from graphql request (Healthy if status is true, Unhealthy if status if false)

```graphql
{
  cluster {
    failover_state_provider_status {
      uri
      status
    }
  }
}
```

<img width="1162" alt="Screenshot 2024-03-20 at 16 12 19" src="https://github.com/tarantool/cartridge/assets/63460867/efe5c449-b6dd-40ce-a4a0-9bb383c0e454">

**Comment by usenko-timur** [comment]
The final version looks slightly different after discussion.

<img width="618" alt="image" src="https://github.com/tarantool/cartridge/assets/88880786/879f409a-2668-4aa7-9a61-1a9a022caf88">
