### ISSUE TITLE
The active failover coordinator does not switch over

### ISSUE THREAD

**Issue by AndreyOrlovSP** [tarantool/cartridge#2209]
The script:
there are two routers in the cluster with the failover-coordinator role
disable the router with the active failover-coordinator role
disable one of the storage master in the replicaset

The actual result:
The master does not switch to another storage in the replicaset

Expected result:
storage replica became master during the failover time

![изображение](https://github.com/tarantool/cartridge/assets/161468894/acbbc21c-2c28-4737-b9b3-b975de8efb7c)

versionCartridge version 2.9.0

Tarantool Enterprise 2.11.2-0-g94f8b6aad-r621-gc64

**Comment by yngvar-antonsson** [comment]
Additional discovered scenarios:

1) Disabling a leader (even if none of the coordinators are disabled) doesn't switchover 
2) When the first instance in the list is stopped, none of the instances can be disabled (only via force apply)  -- seems like a WebUI problem
