### ISSUE TITLE
RFC: WAL failures handler

### ISSUE THREAD

**Issue by yngvar-antonsson** [tarantool/cartridge#2212]
Main issue: https://github.com/tarantool/tarantool/issues/9383

Overview:
When Tarantool faces filesystem errors (e.g. unable to write WAL, disk outage) we should do something to prevent replicaset outage (because Tarantool instance is still working, failover won't switch leadership, and requests still be routed to leader).

Proposed solutions and concerns about them:

1) [Spawn a fiber that checks disk availability](https://github.com/tarantool/tarantool/issues/9383#issuecomment-1819435418). The same solution is already used at least in one cartridge-based cluster system (dm me for details). 
Obvious concern: common tarantool architecture is two bare-metal servers with one half of cluster on each server, all instances controlled by systemd. If the disk is dead on one server, code snippet above provokes an exit of half instances in the cluster. Those instances will be restarted by systemd and then will enter a loop "check - stopped because of disk failure - stated by systemd". In the meantime, other instances in the cluster are receiving tons of membership suspect/dead messages which can lead to more failures on alive instances. Another concern is the usage of `fio.lstat`. I believe it can return an error even if the disk is ok, but a folder is dead. 
 
2) Don't kill anyone and spawn an issue (based on the check from the previous solution). Anyway, disk outage will lead to write failures in the cluster. When someone decides to check webUI/grafana, they'll see a correspondent issue like "Disk failure. Change the leadership manually".
Again, the obvious concern about this one is that part requires a human to change leadership. But disk outage itself requires human presence anyway.

3) Change the instance membership status to dead when a disk error occurs. Quite the same as the first solution, but won't lead to continuous restarting of failing instances. That is against current failover rules (none of the failover calls is made by the dying instance itself), so might need some restructuring and incompatible changes.
_Note:_ There is a [new API](https://github.com/tarantool/tarantool/pull/9422) for such situations. But only for Tarantool 3.0.

4) Don't touch Tarantool at all. Disk failure is not a Tarantool problem, and Tarantool doesn't support switching to read-only mode in such situations. One of many ways to avoid problems - make changed in systemd settings and stop all tarantool instances on the server with a failed disk.

**Comment by AfanasievE** [comment]
Я чайник в проектировании таких систем. На мой взгляд, при обнаружении проблемы с диском экземпляр Тарантула должен перейти в некий "призрачный" режим. Если он умрет, то будет куча перезапусков рассылкой ошибок (первый вариант). То есть он должен остаться запущенным, но сложить с себя полномочия и мастера, и реплики (так как данные на нем будут неактуальными и при чтении.
Может быть, возможно отключить на нем роли storage и router (тут вопрос, может ли узел Тарантула полноценно исполнять роль роутера при невозможности писать на диск, наверное, нет)?
Если мы не сделаем ничего, то кластер станер неработоспособным  вообще. Человек будет реагировать на событие в лучше случае минуты. При том, что для вывода узла из экплуатации и восстановления работоспособности кластера в автоматическом режиме, нужны секунды.

**Comment by yngvar-antonsson** [comment]
Еще один вариант с учетом комментария:
Учитывая, что при сломанном диске нет никакой возможности загрузить на испорченные инстансы новый конфиг, предлагаю тогда автоматически делать disable на сломанных узлах. 
Отвалился диск -> по триггеру из ссылки делаем disable (на стораджах можно делать еще vshard.storage.disable, роутеры stateless, им от отказа диска ни горячо, ни холодно) + issue о сломанном кластере -> вторая половина становится мастерами, запросы на сломанные узлы не идут
Тогда проверка должна происходить централизованно на одном узле, чтобы не создавать лишнюю нагрузку на кластер
Надо еще подумать, как правильно будет сделать.
