### ISSUE TITLE
Allow changing admin password

### ISSUE THREAD

**Issue by rosik** [tarantool/cartridge#222]
Cluster cookie is used as admin password today to connect cluster over both net.box and http. This approach isn't secure enough. It should be possible to change admin password.

### Requirements

1. Password should not be stored in plain text
2. Plain text password should not  be transmitted over network.

**Comment by rosik** [comment]
### Proposal

First of all, cluster cookie should not be used for anything but membership encryption.
Though it can be used as a default password to access uninitialized instance.

Admin credentials will be stored in clusterwide config. We will store `password_hash` instead of plain text password. Thus, plain text will never be transferred over netbox connection.

```lua
password_hash = box.schema.user.password(password)
```

To change tarantool built-in user credentials having `password_hash` the following snippet can be used:

```lua
auth = box.space._user.index.name:get('admin').auth
auth['chap-sha1'] = password_hash
box.space._user.index.name:update('admin', {{'=', 'auth', auth}})
``` 

The same `box.schema.user.password(password)` will be used to check http auth - it'll be compared to the hash stored in clusterwide config.

**Comment by knazarov** [comment]
Do not use sha1 for anything

**Comment by rosik** [comment]
Previous proposal has a flaw: netbox password has to be stored unhashed, otherwise instances could't acces each other.

So here is another proposal:

1. Built-in tarantool user remains unchanged. Netbox password is always equal to cluster cookie.
1. Password to access http interface differs from built-in netbox user. Salted hash is stored in clusterwide config.
1. Password management code should be borrowed from `cartridge.auth-backend`. So we can use any algorithm we like.

**Comment by rosik** [comment]
No demand atm, closing.

**Comment by rosik** [comment]
@no1seman said they need it

**Comment by filonenko-mikhail** [comment]
Inactual now. So gently closing.

**Comment by no1seman** [comment]
Close it!
