### ISSUE TITLE
Implement rpc.map functionality

### ISSUE THREAD

**Issue by rosik** [tarantool/cartridge#235]
It seems that it would be very helpful to have a function, that could perform the same call on multiple servers and gather call results.

**Comment by rosik** [comment]
I think of something like this:

```console
tarantool> rpc.map(
         >     {'localhost:3301', 'localhost:3302'},
         >     '_G.__do_some_math',
         >     {2, 2},
         >     {timeout = 5}
         > )
---
- localhost:3301:
  - 4
  localhost:3302:
  - null
  - connection refused
...
```

**Comment by filonenko-mikhail** [comment]
let's the signature style battle begins

```
-- the simplest
rpc.map('get-the-video-subtitles') -- all subtitles of all video

-- args of target function
rpc.map('get-the-video-subtitles', {'drama'})

rpc.map('get-the-video-subtitles', {'drama', {between={'01-01-1980', '01-01-2000'}}})

-- opts of rpc
rpc.map('get-the-video-subtitles', {}, {timeout=5})
rpc.map('get-the-video-subtitles', {'drama'}, {timeout=5})
rpc.map('get-the-video-subtitles', {'drama'}, {timeout=5, only={'192.168.0.2:3301'}})

rpc.map('get-the-video-subtitles', {'drama'}, {timeout=5, only={'storage-set-na-kanalle-griboedova'}})

rpc.map('get-the-video-subtitles', {'drama', {between={'01-01-1980', '01-01-2000'}}},
    {timeout=5, only={'storage-set-na-kanalle-griboedova', 'storage-set-na-anichkovom-mostu'}})

```

**Comment by rosik** [comment]
First of all, I think this method should belong to `cartridge.pool` module, not `cartridge.rpc`: internally i need it to call global functions, but RPC is only suitable for calling roles.

Going further, my proposal is to make `cartridge.pool` API public:

```lua
cartridge.connpool_connect('uri') -- or should we call it connpool_get?
cartridge.connpool_map_call(fn_name, args, {timeout = x, uri_list = {}})
cartridge.connpool_map_eval() -- similar to call
```

Also I'd like to tune connection options for internal use:
* Set default `reconnect_after = 5`, `wait_connected = 1`, `connect_timeout = 1`
* Make it editable with something like `pool.set_connection_opts()`
* Get rid of opts parameter in `connpool_connect()`.

**Comment by printercu** [comment]
What if provide method for getting map of netboxes instead? User can later decide to use call or eval. Running this requests in parallel should not be in scope of cluster. I think it should be solved by promise-like lib (at least `fiber.wait_all`), or like everything else in lua it can be inlined:

```lua
local results = {}
fibers = fun.iter(net_boxes):map(function(_, net_box)
  f = fiber.new(...)
  set_joinable..
  return f
end):totable()
fun.iter(fibers):each(function(x) j:join() end)
```

**Comment by rosik** [comment]
Well. Internal `pool.map_call` has already been merged in #332:

```lua
pool.map_call(
    '_G.print', {'Hello, Cartridge!'},
    {uri_list = {'localhost:3301', 'localhost:3302'}}
)
```

So, now my proposal is to implement similar public API for the roles:

```lua
local ret_map, err_map = cartrtridge.rpc_map_call(
    'myrole', 'function', {args},
    {leader_only = true/false, healthy_only = true/false}
)
-- ret_map == {['localhost:3301'] = ret, ['localhost:3302'] = nil}
-- err_map == {['localhost:3301'] = nil, ['localhost:3302'] = err}
```

An attempt to call `healthy_only = false` when some candidates are unavailable will result in corresponding errors in `err_map`.

**Comment by knazarov** [comment]
I don't like that we diverge from our regular error handling style here. Because if some error happens before we get to net_box, then err_map will not be a map, but an error object. And `ret_map` could as well become nil.

So, either:

- return `res, err ` where `res` contains result objects _and_ error objects, and consider a failure one of the net.box sub-calls to not be an error condition for this particular function
- return `nil, err` where `err` is an error object, and pack all sub-errors as a separate field of this error

If you pick the first approach, I'd like to see a separate function that allows the user to check if there are errors in the resulting array.

**Comment by rosik** [comment]
We've discussed it IRL, and I agree that `return nil, err` should be compatible with default error handling style. I prefer the second approach, so we need to wrap multiple errors in this particular case.

**Comment by filonenko-mikhail** [comment]
So, this time there is vshard map_call. Seems that it's enough for 99% user stories. Feel free to reopen kindly.
