### ISSUE TITLE
cartridge does not respect tarantool upgrade procedure

### ISSUE THREAD

**Issue by olegrok** [tarantool/cartridge#253]
Subj: https://github.com/tarantool/tarantool/issues/4552

Originally, tarantool launches box.schema.upgrade procedure automatically `if not box.cfg.read_only and not box.cfg.replication`
(https://github.com/tarantool/tarantool/blob/c7a382af0d35a36f8e2b05a09faeb9d877df947c/src/box/lua/load_cfg.lua#L522)

@rosik said that is correct behaviour of cartridge when cluster is bootstrapped from snapshot. But it breaks replication and causes e.g. `Oct 04 13:03:25 server02 tarantool[89961]: 2019-10-04 13:03:25.306 [89961] main/126/applier/admin@server:3306 applier.cc:256 E> error applying row: {type: 'INSERT', replica_id: 1, lsn: 30672, space_id: 280, index_id: 0, tuple: [328, 1, "_trigger", "memtx", 0, {}, [{"name": "name", "type": "string"}, {"name": "space_id", "type": "unsigned"}, {"name": "opts", "type": "map"}]]}`

As w/o we can try to use `replication_skip_conflict = true`. But it's a bug. Please fix it.

**Comment by sharonovd** [comment]
I'd propose to start with box.cfg.read_only=true until configuration is applied, it looks only logical.

**Comment by olegrok** [comment]
Yes, but in this case we should describe in documentation that user should call box.schema.upgrade() explicitly

**Comment by olegrok** [comment]
note: However, you can't bootstrap master at first in read_only = true https://github.com/tarantool/doc/issues/905
