### ISSUE TITLE
consider renaming rpc_call into rpc

### ISSUE THREAD

**Issue by olegrok** [tarantool/cartridge#261]
RPC is "remote procedure call"

rpc_call is "remote procedure call call" that is a clear tautology. Let's rename it as in source files into "rpc"

**Comment by rosik** [comment]
You shouldn't be afraid of tautology, since `rpc_` is a module name. Look, even IBM uses it: https://www.ibm.com/support/knowledgecenter/en/ssw_ibm_i_74/apis/rpc_call.htm

Moreover, how are you going to rename `rpc_get_candidates`?
