### ISSUE TITLE
Make more friendly error message `Please call box.cfg{} first`.

### ISSUE THREAD

**Issue by filonenko-mikhail** [tarantool/cartridge#277]
In case when cartridge not bootstraped yet, there is webui actions (e.g. Users/auth) which try to modify cluster state.

In such case there is error `Please call box.cfg{} first`.

Consider to make better checks with informative message in appropriate places.

**Comment by filonenko-mikhail** [comment]
duplicate of https://github.com/tarantool/cartridge/issues/244

**Comment by rosik** [comment]
All (I hope) these webui actions were protected when triggering two-phase commit.
