### ISSUE TITLE
Wizard for configuration

### ISSUE THREAD

**Issue by KlonD90** [tarantool/cartridge#285]

**Comment by rvrsrec** [comment]
![TT_C - wizard-01](https://user-images.githubusercontent.com/22233143/67202784-2a6ebd80-f412-11e9-9caf-59f74c341d93.png)
![TT_C - wizard-01 1](https://user-images.githubusercontent.com/22233143/67202799-2d69ae00-f412-11e9-8a89-b579b2d2ed13.png)
![TT_C - wizard-02](https://user-images.githubusercontent.com/22233143/67202803-2fcc0800-f412-11e9-837f-327613ac7c35.png)
![TT_C - wizard-03](https://user-images.githubusercontent.com/22233143/67202806-3195cb80-f412-11e9-8c16-6553fad57de7.png)
![TT_C - wizard-04](https://user-images.githubusercontent.com/22233143/67202808-335f8f00-f412-11e9-83c1-332d8eb6f710.png)

**Comment by rvrsrec** [comment]
### Last Scenario
![TT_C - wizard-01](https://user-images.githubusercontent.com/22233143/67278175-25247800-f4d1-11e9-93df-f3c08fcc7c91.png)
![TT_C - wizard-02](https://user-images.githubusercontent.com/22233143/67278177-25247800-f4d1-11e9-941f-6d226a185b27.png)
![TT_C - wizard-03](https://user-images.githubusercontent.com/22233143/67278178-25247800-f4d1-11e9-99dc-6268307d8942.png)

**Comment by rosik** [comment]
Closing along with #244
