### ISSUE TITLE
Code / Schema screens

### ISSUE THREAD

**Issue by rvrsrec** [tarantool/cartridge#287]
New section 'Tarantool Cartridge'

### Code:
![TT_C - Code (first)](https://user-images.githubusercontent.com/22233143/67278758-489bf280-f4d2-11e9-86fb-acb7728bdad8.png)
Main screen "Code"

![TT_C - Code (console)](https://user-images.githubusercontent.com/22233143/67278757-48035c00-f4d2-11e9-8595-4c03b1ed38aa.png)
Console Screen

### Schema:
![TT_C - Schema (first)](https://user-images.githubusercontent.com/22233143/67278765-489bf280-f4d2-11e9-8e01-82fbc171e9af.png)
Main screen "Schema"

![TT_C - Schema (copied)](https://user-images.githubusercontent.com/22233143/67278762-489bf280-f4d2-11e9-8c17-9ad66efa08b1.png)
Copy demo-address to clipboard

![TT_C - Schema (applied)](https://user-images.githubusercontent.com/22233143/67278761-489bf280-f4d2-11e9-8b39-356d7190075d.png)
Version applied

![TT_C - Schema (warning)](https://user-images.githubusercontent.com/22233143/67278766-49348900-f4d2-11e9-960b-45313796c9b2.png)
Warning. Version incompatibility.

**Comment by rosik** [comment]
Related to #312

**Comment by rosik** [comment]
Resolved in #408, #364
