### ISSUE TITLE
Indicate replication problems in WebUI (est: 2)

### ISSUE THREAD

**Issue by rvrsrec** [tarantool/cartridge#289]
Current:
- replication information is located in 'detail server' window/ 'replication' tab/ 'replication info' field  and it contains json

Behavior:
- if a replication error occurs, an error icon is displayed in the replica set status;
- when you click the icon, a modal window opens with a text field and error description;

### Replication Error

![TT_C - Replication Error](https://user-images.githubusercontent.com/22233143/67380296-c4f60a80-f592-11e9-83a1-a7c4c3c6017c.png)
![TT_C - Replication Error (modal)](https://user-images.githubusercontent.com/22233143/67380302-c6273780-f592-11e9-91b4-0b413db0dcb0.png)

**Comment by mnpotetyuev** [comment]
![09 01 00 TT_C - Replication Error](https://user-images.githubusercontent.com/61145957/75763754-ceb42980-5d4d-11ea-9325-511137d7004f.png)
![09 01 01 TT_C - Replication Error (modal)](https://user-images.githubusercontent.com/61145957/75763755-cfe55680-5d4d-11ea-9137-268cd977552b.png)

**Comment by rosik** [comment]
Resolved in #690
