### ISSUE TITLE
Add all_rw replicaset checkbox in webui

### ISSUE THREAD

**Issue by rosik** [tarantool/cartridge#306]
Since the first public release v1.0.0 cartridge implements `replicaset.all_rw` parameter, which makes all instances in the replicaset writable. It would be nice to see this option configurable and displayed in the WebUI.

We need:

- indicator on the cluster page
- checkbox in the "Edit replicaset" dialog

Things to be done:
- [ ] design
- [ ] frontend implementation
- [ ] cypress tests

**Comment by rvrsrec** [comment]
Added checkbox "all_rw" in the "Add / Edit replicaset" dialog
![TT_C - All_RW (modal)](https://user-images.githubusercontent.com/22233143/69868052-ba2d4480-12b9-11ea-85d6-c62dd111f2de.png)

**Comment by rosik** [comment]
To be honest, it looks messy

**Comment by rvrsrec** [comment]
Based on the results of joint discussions on Dec 2
![TT_C - All_RW (modal)](https://user-images.githubusercontent.com/22233143/70065643-807f7500-15fc-11ea-852c-351941a4e85c.png)

**Comment by rosik** [comment]
Resolved in #366
