### ISSUE TITLE
RPC: Allow foo.bar:buzz syntax

### ISSUE THREAD

**Issue by RunsFor** [tarantool/cartridge#308]
Right now, `cartridge.rpc` supports only plain method calls in the module:

```
  class_name: RemoteCallError
  err: Role "queue" has no method "events:put"
```

Imaging I need to wrap some library with a role. I.e. tarantool/queue. Its API has instance methods, which user calls like this:

```lua
queue.events:put('task_1')
```

Moreover, it allows to create multiple tubes inside one instance. Together it makes pretty tedious to export that API from role. In order to make this all work I need to create a wrapper function:

```lua
local function queue_method_wrapper(method)
    return function(name, ...)
        return queue[name][method](queue[name], ...)
    end
end
```

and then export for each method:

```lua
return {
  init = init,
  validate_config = validate_config,
  apply_config = apply_config,
  take = queue_method_wrapper('take'),
  put = queue_method_wrapper('put'),
  ack = queue_method_wrapper('ack'),
  ...
}
```

It would be much easier to just export whole queue api:

```lua
return {
  init = init,
  validate_config = validate_config,
  apply_config = apply_config,
  queue = queue,
}
```

**Comment by filonenko-mikhail** [comment]
It seems that rpc module does not take into account role state in current implementation.

So, such code will be `cut-glass`

```
rpc.call('role.queue.new,' {"kukumba"})
rpc.call('role.kukumba:put', {1})
```

because rpc can't guarantee that it will be called on same node

**Comment by rosik** [comment]
> It seems that rpc module does not take into account role state in current implementation.
> 
> So, such code will be `cut-glass`
> 
> ```
> rpc.call('role.queue.new,' {"kukumba"})
> rpc.call('role.kukumba:put', {1})
> ```
> 
> because rpc can't guarantee that it will be called on same node

What if we implement #235 first? Then it would be

```lua
rpc.map_call('role.queue', 'new', {"kukumba"})
rpc.call('role.queue', 'kukumba:put', {1})
```

**Comment by filonenko-mikhail** [comment]
No current thoughts this time. Decrease info noise. Feel free to reopen.
