### ISSUE TITLE
API for setting and querying DDL

### ISSUE THREAD

**Issue by rosik** [tarantool/cartridge#312]

**Comment by rosik** [comment]
## RFC

DDL [schema](https://github.com/tarantool/ddl/blob/dev/README.md) is stored as a section in clusterwide config (with the same name - `schema`). Being a part of clusterwide config, it's updated with two-phase commit. Validation stage calls `ddl.check_schema()` (which checks space existence and checks creation of dummy space). Apply phase calls `ddl.set_schema()` and creates spaces.

Cartridge provides HTTP methods for managing the schema. They work similar to clusterwide config [GET](https://github.com/tarantool/cartridge/blob/df444c93d533a82387a999080c83838648de4810/cartridge/webui/api-config.lua#L40) / [PUT](https://github.com/tarantool/cartridge/blob/df444c93d533a82387a999080c83838648de4810/cartridge/webui/api-config.lua#L69), but operates the `schema` section only.

* HTTP GET: retrieves current schema from clusterwide config in yaml format
* HTTP PUT: accepts yaml schema as multipart form-data and triggers `confapplier.patch_clusterwide()`


### Example clusterwide config

```
schema:
  spaces:
    A: {"format": ..., "indexes": ...}
    B: ...
```

Schema specification is described [here](https://github.com/tarantool/ddl/blob/dev/README.md)

**Comment by rosik** [comment]
@knazarov comment, please

**Comment by knazarov** [comment]
I didn't understand the HTTP GET/PUT part. Do you mean that there should be separate HTTP-only method (not GraphQL). Why?

Additionally it will be a good idea to specify a global function in Lua that is exposed through net.box, that allows to set/retrieve the schema. It will be very useful for tarantool in the cloud.

**Comment by rosik** [comment]
> I didn't understand the HTTP GET/PUT part. Do you mean that there should be separate HTTP-only method (not GraphQL). Why?

I designed it similar to the config management, which is implemented with GET/PUT nowadays (and I even provided links to the code). GraphQL is not a problem, we can do it if you think it's better.

> Additionally it will be a good idea to specify a global function in Lua that is exposed through net.box, that allows to set/retrieve the schema. It will be very useful for tarantool in the cloud.

It's ok too, but I've got another question: usually there are spaces, which a created automatically and not listed in clusterwide config (i.e. `_buckets` internal vshard space). Should this global method list it, or it should retrieve clusterwide schema section?

**Comment by knazarov** [comment]
> I designed it similar to the config management, which is implemented with GET/PUT nowadays

I understand the general logic of this, but I can't follow why we need an HTTP endpoint instead of GraphQL in this particular case. The configuration endpoint works through plain HTTP because there is a file upload mechanism behind the scenes.

> Should this global method list it, or it should retrieve clusterwide schema section?

It seems logical if it will only return what's been last set through the DDL.

**Comment by rosik** [comment]
@knazarov I've updated RFC according to your comments, please check it again.

**Comment by knazarov** [comment]
Last edition LGTM
