### ISSUE TITLE
Prohibit joining an instance to a replicaset with all replicas disabled

### ISSUE THREAD

**Issue by sharonovd** [tarantool/cartridge#32]
In GitLab by @rosik on Dec 10, 2018, 00:00

**Comment by sharonovd** [comment]
In GitLab by @rosik on Dec 10, 2018, 00:12

changed title from **Prohibit joining {-the vshard-storage to a replicaset with all server-}s disabled** to **Prohibit joining {+an instance to a replicaset with all replica+}s disabled**

**Comment by filonenko-mikhail** [comment]
This time we decide to close this ticket, because of poor info in it. So such theme is definetely popup in product roadmap. Feel free to reopen.
