### ISSUE TITLE
Show application name in admin panel

### ISSUE THREAD

**Issue by printercu** [tarantool/cartridge#327]
For better experience in operation teams.

aaa: у картриджа написан заголовок Cluster. Если тут сконфигурить, будет написано REPLICA SETS, а неплохо бы "Our mega-cluster-name".
aaa: У админа открыто сто кластеров и не видно, про что текущий открытый кластер.
bbb: ну тут опять название раздела. наверное лучше в самой верхней строке название приложения писать

**Comment by knazarov** [comment]
This is actually a very nice idea. I needed it myself a few times.

**Comment by mnpotetyuev** [comment]
![04 01 00 Configure server TT_C - Main page (BL-01)](https://user-images.githubusercontent.com/61145957/75423261-692bfb80-594f-11ea-8d01-56d11fee741c.png)

"*PROJECT NAME* CLUSTER/SCHEMA/USERS/CODE"

**Comment by rosik** [comment]
### RFC

We define project name as `app_name` from argparse (`TARANTOOL_APP_NAME` environment variable or `--app-name` command line argument).

We'll make it accessible through graphql api:

```graphql
query {
  cluster {
    self {
      app_name
      instance_name
    }
  }
}
```

**Comment by mnpotetyuev** [comment]
![01 01 00  TT_C - wizard-01a](https://user-images.githubusercontent.com/61145957/76607558-2fe5b500-6525-11ea-93b4-4f94428b3751.png)
