### ISSUE TITLE
Expelling nodes when other nodes are down

### ISSUE THREAD

**Issue by edam** [tarantool/cartridge#328]
IIUC, when you expel a node, the two-phase commit of conf changes across the cluster requires confirmation from all nodes except the one bing expelled.  This means that when two nodes (even two in unrelated replicasets) go down, you can no longer expel *any nodes*!  E.g., if for some reason beyond your control two irecoverably lost two nodes, expelling any nodes ever again becomes impossible! 

Is this really the case? Or am I missing something?

**Comment by rosik** [comment]
With `edit_topology` mutation you can. See #200.
Also you can disable them first, and then expel one by one.

Although I admin that WebUI is still missing many useful features, they will be resolved within #38, #50
