### ISSUE TITLE
Forward an error from new replicaset if it fails to bootstrap_from_membership

### ISSUE THREAD

**Issue by sharonovd** [tarantool/cartridge#33]
In GitLab by @rosik on Dec 10, 2018, 16:53

**Comment by sharonovd** [comment]
In GitLab by @rosik on Jan 15, 2019, 13:34

marked this issue as related to #44

**Comment by sharonovd** [comment]
In GitLab by @rosik on Apr 4, 2019, 14:36

marked this issue as related to #75

**Comment by rosik** [comment]
Resolved in #331, irrelevant since 2.0.0
