### ISSUE TITLE
Implement LSP support in Cartridge

### ISSUE THREAD

**Issue by KlonD90** [tarantool/cartridge#333]
We want integrate Tarantool LSP inside Cartridge.
But don't want integrate really LSP inside of main thread.

**Comment by knazarov** [comment]
We actually do want to integrate LSP into the main thread

**Comment by KlonD90** [comment]
@artur-barsegyan 

# Connect LSP to Cartridge

## Library way

Use LSP as library connect it to http handler. Work to do: make from current LSP bin library: add options for configuration like luacheck, what is root, ignore root from client and use some layer for provide files, optional conditions?

## Binary way

Start instance of lsp ws and use it as binary on special tmp folder with copy files. Just crazy idea. WS in cartridge proxying it to lsp with change initialize section.

**Comment by artur-barsegyan** [comment]
It was difficult for me to understand your ideas. Please write in Russian (:

It's too brief for the RFC feature. 

**Library way:** What the http handler? What the name of your new endpoint? Will it the cartridge default http port or not? Other part of your RFC left unrecognized for me.  

**Binary way:** Who will start the LSP? cartridge?

**Comment by knazarov** [comment]
We need both. The library will be used as part of cartridge to get auto-complete in the web UI. The binary will be used as a stand-alone way to get auto-complete in VS Code and other editors.

**Comment by knazarov** [comment]
At this moment, the "library way" should be a priority.

**Comment by KlonD90** [comment]
@knazarov it's already work as standalone decision, it's just for connecting with cartridge possible way.

# RFC Try 2

LSP should be library so we need add option to it like module:

```
local handler_ws = lsp.handleWS({
luacheckrc = 'content of rc',
luacompleterc = 'content of complete',
file_handler = function (path) return file.read(path) end,
})

httpd:get('/lua-ws', handler_ws)
```

**Comment by artur-barsegyan** [comment]
LGTM.

**Comment by rosik** [comment]
My proposal is to use `pcall(require, 'lsp')` and set up all handlers basing on its availability.

cartridge rockspec will not declare lsp as mandatory dependency, but it can be installed optionally.

**Comment by knazarov** [comment]
Why optional dependency?

**Comment by rosik** [comment]
To be able run cartridge without it when it's not needed

**Comment by knazarov** [comment]
What's the problem with starting it on-demand, when we switch to IDE tab? What's the problem in shipping it with cartridge all the time?

**Comment by artur-barsegyan** [comment]
@rosik if you do not include `lua-lsp` into the dependencies we will have a lot of problems:
- explain to users how to install this dependency
- create the problem with versions and API compatibility between the `cartridge` and scm `lua-lsp`

**Comment by rosik** [comment]
Ok, then I retreat with my proposal. Let the dependency be mandatory.

**Comment by rosik** [comment]
Stale. Feel free to reopen.
