### ISSUE TITLE
Add support download/upload for cypress

### ISSUE THREAD

**Issue by Errora** [tarantool/cartridge#351]
https://github.com/abramenal/cypress-file-upload
cypress-io/cypress: Issue #949

**Comment by rosik** [comment]
A lot of time passed since this issue was open. Please, take a look at cypress features once again - maybe it's already implemented.

**Comment by Errora** [comment]
На текущий момент сайпресс не поддерживает нужную нам загрузку файлов. Сейчас  результат такой: 

1) В Электроне не получается взаимодействовать с окном, которое спрашивает про место для скачивания:

![изображение](https://user-images.githubusercontent.com/12095303/86395667-4d43b800-bca9-11ea-9486-77ab30dcdfe7.png)

2) В Хроме, если отключить вопрос про место скачивания, то файл скачивается, но запрос все равно виснет и по истечению 60 секунд выдает ошибку:

![изображение](https://user-images.githubusercontent.com/12095303/86396700-1b335580-bcab-11ea-999f-a4cf2f587fbd.png)

Задача https://github.com/cypress-io/cypress/issues/949 открыта. Последний ответ для нашей ситуации, который удалось найти, был в задаче https://github.com/cypress-io/cypress/issues/7576 4 июня: File download is not fully supported in Cypress out of the box.

**Comment by rosik** [comment]
Closing till the better times

**Comment by rosik** [comment]
Let's give it one more try with a newer cypress version
