### ISSUE TITLE
cluster: show info on backend unavailability

### ISSUE THREAD

**Issue by Errora** [tarantool/cartridge#357]

**Comment by rosik** [comment]
To implement the test you'll have to shutdown the instance while cypress is running. Is there a way to connect tarantool binary protocol from js? Or execute `kill -9` by PID?

**Comment by rosik** [comment]
```js
cy.exec('kill -9 $(lsof -sTCP:LISTEN -i :3301 -t)')
```

**Comment by rosik** [comment]
Related to #508

**Comment by rosik** [comment]
Resolved in #547
