### ISSUE TITLE
Design validation warnings inside Schema editor

### ISSUE THREAD

**Issue by rgbabaev** [tarantool/cartridge#359]
Currently in schema editor we use system notifications to show validation error or success message.

![telegram-cloud-photo-size-2-5386717012090268729-y](https://user-images.githubusercontent.com/27233703/69425734-8ba0ee00-0d3c-11ea-8a78-9715d641a46c.jpg)

It's bad practice and validation messages must be shown in schema editor page.

**Comment by rvrsrec** [comment]
- Click on the button " Validation"
- Label with "Validation error" appears in the line with buttons
![TT_C - Schema (validation)](https://user-images.githubusercontent.com/22233143/70059974-c0d9f580-15f2-11ea-9f2f-96d3d7886674.png)

**Comment by rosik** [comment]
@rvrsrec Where will a user see error details?

![image](https://user-images.githubusercontent.com/2205188/70063540-039ecc00-15f9-11ea-96b0-43751d4e1f24.png)
