### ISSUE TITLE
Create report button in UI

### ISSUE THREAD

**Issue by artur-barsegyan** [tarantool/cartridge#362]
## Motivation
When a user struggle with a problem, he needs to have a way to quickly tell about that and get appropriate help. The user may know about the problem via Web UI or via any setting alarm system. In the case of Web UI, we can help the user with the problem reporting.

It helps to:
- get problems done for the end-user
- faster product evolution by getting new issues for Tarantool & Cartridge

## How to achieve it
It will be very convenient to have a button like "Report a bug" in our GUI because we can get more feedback: suggestions, bug requests and etc.  

### Help asking
Reports are not the only one thing that needed for users during some failure. That user needs to understand: where to ask help.

- Ability to dump error details into the file
_User may haven't Internet access because the infrastructure is isolated_
- Ability to open the Github issue page at `tarantool/cartridge` with a partly filled template about the error details.

**Comment by artur-barsegyan** [comment]
We need two types of this button.

1. **Generic issue button:** should be placed at any visible place at Cartridge UI. Their purpose is to be a helpful mechanism.
2. **On-demand button:** should be placed at the modal window with a cluster error description. We could add a button to error pages that'd report a bug on GitHub with the stack trace user saw. 

An optimal mechanic is described here: https://github.com/kubernetes/dashboard/pull/1461

**Comment by artur-barsegyan** [comment]
Button: Find at Stackoverflow

**Comment by rosik** [comment]
Stale. Feel free to reopen.
