### ISSUE TITLE
Enhance UX of expelled instance

### ISSUE THREAD

**Issue by sharonovd** [tarantool/cartridge#38]
In GitLab by @rosik on Dec 25, 2018, 13:10

Web UI of expelled instance should indicate the fact it was expelled

**Comment by sharonovd** [comment]
In GitLab by @rosik on Dec 25, 2018, 13:34

Blockers:

https://github.com/tarantool/tarantool/issues/3159

Also we need something like `relay_stop()` or `relay_delete()` api to force stop replication

**Comment by sharonovd** [comment]
In GitLab by @rosik on Apr 4, 2019, 14:35

marked this issue as related to #75

**Comment by sharonovd** [comment]
In GitLab by @rosik on Jul 18, 2019, 19:44

Also related: https://github.com/tarantool/tarantool/issues/3939

**Comment by sharonovd** [comment]
In GitLab by @rosik on Jul 18, 2019, 19:44

This isn't a 'ui' issue.

**Comment by filonenko-mikhail** [comment]
This time we have to choose right ui direction. So closing now. Feel free to reopen.
