### ISSUE TITLE
Console window for "Code" screen

### ISSUE THREAD

**Issue by rvrsrec** [tarantool/cartridge#384]
- If you click the "Console" button in the upper right corner, the console window will open;
- The "Console" window opens on top of all content on the page;
- If you click on the cross in the upper right corner of the "Console" window, the console will close;

![TT_C - Code (console)](https://user-images.githubusercontent.com/22233143/70067056-c3424c80-15fe-11ea-817b-da508a828e70.png)

**Comment by rgbabaev** [comment]
@artur-barsegyan do we still need this?

**Comment by rosik** [comment]
Stale.
