### ISSUE TITLE
The URL of the demo screens Code / Schema

### ISSUE THREAD

**Issue by rvrsrec** [tarantool/cartridge#385]
- The demo has a URL that the user can access;
- There is an icon next to the URL;
- Click on the icon-copy the URL to the clipboard

![TT_C - Code (first)](https://user-images.githubusercontent.com/22233143/70067638-9cd0e100-15ff-11ea-8af2-05ef7233c687.png)
![TT_C - Schema (first)](https://user-images.githubusercontent.com/22233143/70067617-97739680-15ff-11ea-959e-8b97cabce467.png)
![TT_C - Schema (copied)](https://user-images.githubusercontent.com/22233143/70067634-9b071d80-15ff-11ea-908a-7ab4c6f80d4d.png)

**Comment by rosik** [comment]
### Backend integration RFC

* try.cartridge sets environment variable `TARANTOOL_DEMO_URI` when running cartridge instances.
* Cartridge provides new graphql query: `cluster { self { demo_uri } }`.
* (doubtful) Cartridge provides graphql mutation `cluster { self(demo_uri: String) }` which allows to change it dynamically.

**Comment by artur-barsegyan** [comment]
What needs for that:
> Cartridge provides new graphql query: cluster { self { demo_uri } }.
And that:
> (doubtful) Cartridge provides graphql mutation cluster { self(demo_uri: String) } which allows to change it dynamically.

We don't have any needs for including demo functionality into the master branch. 
I see some other ways for that:
- create external closed repo
- create another branch in the current repo

**Comment by rosik** [comment]
> We don't have any needs for including demo functionality into the master branch.

Maintaining separate branch/repo would require additional resources. This functionality doesn't impede normal cartridge operation, so I can't see a reason to waste time on unnecessary isolation.

**Comment by artur-barsegyan** [comment]
Yes, I agree with you.
