### ISSUE TITLE
Misleading "Connection lost" error message

### ISSUE THREAD

**Issue by rosik** [tarantool/cartridge#395]
In #344 we introduced frontend notifications deduplication, but "connection lost" message behavior is still inappropriate: it doesn't disappear when connection comes back to life.

My proposal is to redesign this particular error.

**Comment by rosik** [comment]
Related to #197

**Comment by rvrsrec** [comment]
- user open window;
- the connection to the backend breaks;
- the status bar with the error "connection lost" appears at the top of the window;
- the status bar disappears when the connection is restored
![TT_C - Connection Lost](https://user-images.githubusercontent.com/22233143/70516015-4a377d80-1b47-11ea-9253-9af94da55d43.png)
