### ISSUE TITLE
utils.table_setro is totally worthless

### ISSUE THREAD

**Issue by rosik** [tarantool/cartridge#401]
Read-only tables simply don't work:

```lua
local t = {x = 5}
utils.table_setro(t)
t.x = 6 -- ok
```

The reason is that `table_setro` is implemented with `__newindex` metamethod, but according to lua spec it's not triggered if the key already exists.

In order to make it work one should implement so-called "proxy table" (see [here](https://www.lua.org/pil/13.4.5.html)), but it would break `pairs()` iteration.

See also https://github.com/tarantool/tarantool/issues/4770

**Comment by filonenko-mikhail** [comment]
It's seems dead end for situation. Feel free to reopen kindly.
