### ISSUE TITLE
Routing page for file in code page

### ISSUE THREAD

**Issue by KlonD90** [tarantool/cartridge#410]

**Comment by rosik** [comment]
In Github trose URIs are implemented as following:

https://github.com/tarantool/cartridge/blob/master/cartridge/VERSION.lua#L3

But in PR diff the URI is slightly different:

https://github.com/tarantool/cartridge/pull/633/files#diff-877744ba9f8828536c499a1d59205089R11

**Comment by rosik** [comment]
No demand atm, feel free to reopen
