### ISSUE TITLE
Avoid netbox.self in rpc_call({prefer_local = false})

### ISSUE THREAD

**Issue by rosik** [tarantool/cartridge#422]
Using `netbox.self` is full of problems: see #377, #208, https://github.com/tarantool/tarantool/issues/4657, https://github.com/tarantool/tarantool/issues/4602, https://github.com/tarantool/tarantool/issues/4540, https://github.com/tarantool/tarantool/issues/4513.

We can't stop using it because it's essential for `prefer_local=true`, but I think it would be fair to avoid it when user specifies `prefer_local = false` explicitly.

**Comment by olegrok** [comment]
My main motivation of https://github.com/tarantool/cartridge/issues/377 is to allow use standard net.box options as `is_async`, `on_push`, `on_push_ctx`.

I like your suggestion, but I want that rpc_call allows to pass net.box options

Second point is to check the presence of this "unsupported options" and in this case perform usual net.box (not self) call implicitly

**Comment by rosik** [comment]
If `prefer_local = false` could promise to never use `netbox.self` then all of `is_async`, `on_push`, `on_push_ctx` can be added easily.

And the combination of `prefer_local = true` with any of them would raise an error

**Comment by olegrok** [comment]
> And the combination of `prefer_local = true` with any of them would raise an error

But what happens if I forget to explicitly specify `prefer_local = false` option? Undefined behaviour?

**Comment by RunsFor** [comment]
There will make no sense for this option if you would choose to avoid `netbox.self`, when option is `false`. Consider example, when you have a role setup only on 1 instance and it happen to be local. Will such `rpc_call` with `{prefer_local = false}` option fail?

**Comment by rosik** [comment]
> Consider example, when you have a role setup only on 1 instance and it happen to be local. Will such `rpc_call` with `{prefer_local = false}` option fail?

No, `{prefer_local = false}` will perform call over real netbox connection to self, like `netbox.connect(box.listen)`. And at the same time `{prefer_local = true}` will use `netbox.self`



> > And the combination of `prefer_local = true` with any of them would raise an error
> 
> But what happens if I forget to explicitly specify `prefer_local = false` option? Undefined behaviour?

It would be an error similar to one produced by `checks`

**Comment by olegrok** [comment]
> It would be an error similar to one produced by `checks`

Okey, may be it makes sense if we shows to user clear error message.

**Comment by knazarov** [comment]
I dont like the idea to have to specify prefer_local explicitly in any call. I'd like it to be false by default.

**Comment by rosik** [comment]
We've discussed it on Friday. Default `prefer_local` value is true, and it's ok. But there is another proposal to make `return nil, err` compatible with default error handling style, so we need to wrap multiple errors in this particular case.
