### ISSUE TITLE
Implement specifying uri for rpc_call

### ISSUE THREAD

**Issue by rosik** [tarantool/cartridge#423]
Cartridge API has an `rpc_get_candidates` method, but its return value is almost useless since it can't be passed to `rpc_call`. 

Let's extend the `rpc_call` options with the new one - `{uri = ...}`.

This may be useful to retain the executor, like this

```lua
local leaders = cartridge.rpc_get_candidates('myrole', {leader_only = true, healthy_only = true})
local pinned_uri = leaders[math.random(#leaders)]
cartridge.rpc_call('myrole', 'task_start', {args}, {uri = pinned_uri})
cartridge.rpc_call('myrole', 'task_stop', {args}, {uri = pinned_uri})
```

**Comment by knazarov** [comment]
Nice
