### ISSUE TITLE
Implement the ability to parse a config file with module 'argparse'

### ISSUE THREAD

**Issue by hackallcode** [tarantool/cartridge#430]
Now it is possible to parse the config file with module `argparse` by specifying the path in arguments or environment variables.

Let's implement the ability to parse the config file by specifying the path through the code. It may be function `parse_file(filename)` in module `argparse`.

**Comment by rosik** [comment]
Function `argparse.parse()` doesn't take any arguments. Do you want to be able to parse different filename and spread your config files all across the filesystem? I don't think it's a good idea.
