### ISSUE TITLE
"You are here" marker in webui

### ISSUE THREAD

**Issue by rosik** [tarantool/cartridge#431]
I'd like to see a mark on topology page indicating which instance i'm looking at.

**Comment by rosik** [comment]
Motivation: when I open `localhost:8081` I usually see topology with some servers, e.g. `localhost:3301` and `localhost:3302`. This information doesn't allow me to guess which server serves the webui, but it should.

**Comment by mnpotetyuev** [comment]
There are two options UI elements to solve the problem.


first
![01 01 00  TT_C - wizard-01_01](https://user-images.githubusercontent.com/61145957/75992836-a113df80-5f09-11ea-895e-17f076861768.png)
![01 01 00  TT_C - wizard-01_02](https://user-images.githubusercontent.com/61145957/75992837-a1ac7600-5f09-11ea-970b-674de06cffea.png)

second
![01 01 00  TT_C - wizard-02_01](https://user-images.githubusercontent.com/61145957/75992871-ae30ce80-5f09-11ea-98ae-0fd7163c4f05.png)
![01 01 00  TT_C - wizard-02_02](https://user-images.githubusercontent.com/61145957/75992872-affa9200-5f09-11ea-8965-460f25601ce2.png)

**Comment by mnpotetyuev** [comment]
with "leader"

![01 01 00  TT_C - wizard-01_01](https://user-images.githubusercontent.com/61145957/75994641-547dd380-5f0c-11ea-885e-0ec0a28ef6ce.png)
![01 01 00  TT_C - wizard-01_02](https://user-images.githubusercontent.com/61145957/75994646-56479700-5f0c-11ea-8686-4887793a93f5.png)
![01 01 00  TT_C - wizard-02_01](https://user-images.githubusercontent.com/61145957/75994649-5778c400-5f0c-11ea-99e6-134a60af4bcd.png)
![01 01 00  TT_C - wizard-02_02](https://user-images.githubusercontent.com/61145957/75994655-58115a80-5f0c-11ea-89c2-778a99745b40.png)

**Comment by mnpotetyuev** [comment]
update marker location
<img width="477" alt="Снимок экрана 2020-03-05 в 19 27 44" src="https://user-images.githubusercontent.com/61145957/76003240-d2e07280-5f18-11ea-81b1-e7ac295bf6bd.png">
