### ISSUE TITLE
Change box.cfg dynamic params with graphql

### ISSUE THREAD

**Issue by rosik** [tarantool/cartridge#442]
Some options can be changed on the fly. Some of them may be useful to configure in webui - memtx memory, log level.

**Comment by artur-barsegyan** [comment]
It seems nice, but I see a lot of questions here. For example, what will the target group for changing parameters: one instance, one replica set, all cluster?

The second question is: is this really need for somebody? I mean, I don't see current needs for this but maybe we need to get more experience from the production guys.

**Comment by rosik** [comment]
my proposal is to add a few inputs to the server details dialog, so it'll be managed per instance.

as for needs, an ability to change log level was asked recently in chats. memtx memory is my guess.

**Comment by knazarov** [comment]
Don’t do this. We can only persist such parameters in /etc/tarantool/conf.d. It will only confuse people who won’t know that these functions are transient.

Well, maybe except for log level, which looks rather safe to dynamically change.

**Comment by rosik** [comment]
Obsolete. Closing.
