### ISSUE TITLE
Use app_name in default cluster_cookie

### ISSUE THREAD

**Issue by printercu** [tarantool/cartridge#447]
This prevents different cartridge apps with default config from conflict on development setup.

**Comment by rosik** [comment]
It's already set up in cartridge-cli (`cartridge create`) when template is rendered, what else do you need?

**Comment by printercu** [comment]
I want cartridge to work this way without relying on cartridge-cli. Cartridge provides default value. Either it should not be provided or it should have reliable value (having same cookie for different apps creates problems).

**Comment by rosik** [comment]
I've thought about your proposal, and I still think it's a bad idea.

We usually receive complaints about troubles connecting to a newly set up cluster. The idea to use cluster cookie as a password isn't obvious enough. I have no idea how to make it more user-friendly (we can't drop cookie at all), but complicated cookie value will definitely make it even worse.
