### ISSUE TITLE
Implement single failover switching

### ISSUE THREAD

**Issue by sharonovd** [tarantool/cartridge#47]
In GitLab by @rosik on Jan 15, 2019, 15:25

It is proposed to implement an alternative algorithm:

1. When master becomes unavailable, promote a replica.
2. When old master returns, do NOT switch it back.

**Comment by sharonovd** [comment]
In GitLab by @RunsFor on May 14, 2019, 15:10

Should this behaviour be configurable/default?

**Comment by sharonovd** [comment]
In GitLab by @rosik on May 14, 2019, 15:20

It should be configurable. Now we have a parameter in clusterwide config:

```
topology:
  failover: true
```

We can extend it with other stateful failover params

**Comment by rosik** [comment]
Closing in favor of #148
