### ISSUE TITLE
DDL schema migrations

### ISSUE THREAD

**Issue by rosik** [tarantool/cartridge#485]

**Comment by rosik** [comment]
The old note from Alexey Kuzin:

https://gitlab.com/tarantool/enterprise/central/-/issues/119

Цель
----

Получить общий механизм миграций схем спейсов и данных, пригодный для использования в продакшене для проектов на Tarantool Cartridge.

Описание
--------

Продукты, как правило, развиваются итеративно и требуют изменения моделей данных. Поэтому возникает вопрос безопасного изменения схем спейсов и самих данных для обновления на новые версии, когда продукт уже работает с реальными данными на проде или продлайке. Tarantool Cartidge необходим общий механизм безопасного применения изменений в схеме хранения данных и индексах для любого спейса в кластере.

Миграции -- широко известный паттерн безопасного изменения схем хранения данных с поддержкой версионности.

Типовые операции изменения схемы хранения данных:
 - Создание спейса
 - Удаление спейса
 - Добавление поля
 - Изменение типа данных поля
 - Удаление поля
 - Добавление индекса
 - Удаление индекса

В SQL подобные операции относятся к семейству DDL.

Исследование
------------

 - [ActiveRecord migrations](https://guides.rubyonrails.org/v3.2/migrations.html)
 - [Migrations in Yii2](https://www.yiiframework.com/doc/guide/2.0/en/db-migrations)
 - [Asynchronous migrations in MongoDB](https://www.npmjs.com/package/migrate-mongo)
 - [Asynchronous schema change (paper)](https://static.googleusercontent.com/media/research.google.com/ru//pubs/archive/41376.pdf) -- F1, база для Google AdWords, 2013

Требования
----------

 - Миграции должны быть идемпотентны (может решаться с помощью механизма проверок применимости миграции)
 - Миграции должны быть атомарны (может решаться с помощью внешних относительно кода миграции инструментов обеспечения транзакционности)
 - Процедуры изменения данных во время наката и отката миграции должна задаваться пользователем
 - При накате миграции должны следовать явно заданному порядку применения
 - Миграции должны поддерживать откат в порядке, обратном порядку применения
 - При создании спейсов обычным образом для них неявно должна инициализироваться нулевая миграция для поддержки миграций в дальнейшем
 - Кластер должен обслуживать клиентские запросы во время наката миграций (минимальный даунтайм, асинхронное применение миграции)
 - Должна быть возможность инициализации миграций на работающем кластере с данными

**Comment by filonenko-mikhail** [comment]
Я бы хотел расширить «Типовые операции»:
  - Переименование:
    - спейса
    - поля
    - индекса

**Comment by rosik** [comment]
We've got https://github.com/tarantool/migrations/ now
