### ISSUE TITLE
[UI] Code: Empty saved file removes after Reload

### ISSUE THREAD

**Issue by Errora** [tarantool/cartridge#496]
**Шаги:**
1. Перейти на страницу Code
2. Создать файл (пустой)
3. Нажать Apply
4. Нажать Reload

**Ожидаемый результат:**
Сохраненный файл, даже если он пустой, должны сохраняться в системе.
(это не относится к папкам)

**Полученный результат:**
Файл удалился

**Comment by rosik** [comment]
Если после создания открыть файл, то он апплаится нормально

А если создать и не открывать, то он при апплае исчезает
