### ISSUE TITLE
☂️ Implement disabling instances and showing their status

### ISSUE THREAD

**Issue by sharonovd** [tarantool/cartridge#50]
In GitLab by @rosik on Jan 16, 2019, 15:42

Design is to be discussed. I think it may be somethink like this:

![image](/uploads/989443c4466d9b1be1e7a99ed22f0479/image.png)

PLus a button "Disable servers" next to "Bootstrap vshard".

Or it may be a new dialog with checkboxes

Grqphql: 

```
mutation {
    cluster { disable_servers(uuids: ["uuid-1", "uuid-2"]) }
}
```

**Comment by sharonovd** [comment]
In GitLab by @yakov.dalinchuk on Feb 6, 2019, 12:00

mentioned in merge request !47

**Comment by rosik** [comment]
Просто мысли вслух:

Когда кластер был маленьким мы ввели такое правило:

**Двухфазный коммит обновляет конфигурацию на всех 100% инстансов, перечисленных в топологии.**

Мотивация была такая:
1. Конфиг должен быть консистентным.
1. А то как же мы конфликты разруливать будем.

Правило оказалось слишком строгим. Иногда, когда железяка уходит оффлайн, сохранить консистентность не остаётся никакой возможности. А управлять топологией всё-таки хочется (очень).

Попробуем зайти с другой стороны. Пора признать, что консистентность конфига на всём кластере мы обеспечить не можем (да и не хотим уже). Пусть так, но мы все еще хотим за этой неконсистентностью следить и осознанно ей управлять.

Была попытка завести в топологии флаг disabled, но он оказался не очень. Основная проблема - источником правды о статусе инстанса не является он сам, но кто-то другой. 

Предлагаю пойти другим путём. Пусть мы не можем обеспечить консистентность на 100% инстансов. Но ведь можем на некотором подмножестве. И даже хотим. Так **давайте введём понятие субкластера** со своим айдишником. Таким образом мы будем не "дизейблить половину кластера", а "создавать новый субкластер" (с новым юидом, например). С такой формулировкой каждый инстанс будет точно знать айди своего субкластера и ему не придётся гадать на кофейной гуще "считает ли меня кто-то задизейбленным".

**Comment by rosik** [comment]
Несмотря на все старания, неконсистентность так и останется неконсистентностью. Но есть и другой способ от неё избавиться: полностью перенести конфигурацию топологии во внешнее хранилище (в рамках #91)

Как вы считаете?

/polls "Картридж должен работать даже без внешнего хранилища" "Без внешнего хранилища жизни нет"

**Comment by rosik** [comment]
/polls "Картридж должен работать даже без внешнего хранилища" "Без внешнего хранилища жизни нет"

**Comment by rosik** [comment]
Фокус с голосованием не удался, ставьте по старинке 👍 или 👎

**Comment by Kasen** [comment]
> Фокус с голосованием не удался, ставьте по старинке 👍 или 👎

Ты бы хоть написал, какой палец что означает. Я считаю, что без внешного хранилища жизни нет.

**Comment by filonenko-mikhail** [comment]
So such feature can be done only with external config storage. Gently closing.
