### ISSUE TITLE
Combine Join and Create buttons into a single dialog

### ISSUE THREAD

**Issue by sharonovd** [tarantool/cartridge#51]
In GitLab by @rosik on Jan 16, 2019, 15:45

This issue is copied from cluster_ui#15

It should look something like this:

![image](/uploads/df1eaf5a53f4575a21199bafee79cb14/image.png)

All choices gonna sent the same graphql request:

```
mutation {
    join_server(
        uri: "localhost:3305"
        replicaset_uuid: "existing-uuid" or Null
    )
}
```

The server is initialized without roles.
User will select it later in "edit replicaset" dialog

**Comment by rosik** [comment]
Done in 1.0.0
