### ISSUE TITLE
Show error details in WebUI (sp:4)

### ISSUE THREAD

**Issue by rosik** [tarantool/cartridge#510]
Recently (in #491) we've extended GraphQL errors with stack trace and error class name. It would be nice to see it in the WebUI.

**Comment by mnpotetyuev** [comment]
![1_1](https://user-images.githubusercontent.com/61145957/81351896-f4530b80-90cd-11ea-83c4-470b58fe2b88.png)
![1_2](https://user-images.githubusercontent.com/61145957/81351910-f6b56580-90cd-11ea-8fe9-04975c802470.png)

**Comment by iv-ov** [comment]
Формировать плашку нотификации как в дизайне не стал
![изображение](https://user-images.githubusercontent.com/7147989/83763086-fedad380-a680-11ea-86fe-8dee6ac4fa99.png)

 — тут используется     `error['extensions']['io.tarantool.errors.class_name']` ("NetboxCallError") и `error.message` ("Peer closed"),
но по-моему эти поля не всегда содержат такие аккуратные данные, чтобы их исползовать как заголовок нотификашки.

Пример:
![изображение](https://user-images.githubusercontent.com/7147989/83767181-fd5fda00-a685-11ea-8302-868e78bac971.png)
вроде бы уже длинновато и некрасиво, а могут быть и длиннее тексты.
