### ISSUE TITLE
Upload/download archived config

### ISSUE THREAD

**Issue by rosik** [tarantool/cartridge#523]
Some time ago (in #404, #402) multi-file clusterwide configuration was introduced, but HTTP GET/PUT still handles single-file YAML. It's time to upgrade /admin/config endpoint and start handling archives (tar I guess). Yet backward compatibility should still be preserved

**Comment by rosik** [comment]
### RFC

Current HTTP API:

- `GET /admin/config` download YAML
- `PUT /admin/config` upload YAML

Proposed changes

- `GET /admin/config` -> `301 /admin/config.yml`
- `GET /admin/config.yml` download YAML (as before)
- `GET /admin/config.tar` download TAR

- `PUT /admin/config` upload both YAML and TAR (guess format automatically)

**Comment by Satbek** [comment]
Please support this changes in ``cartridge.test-helpers``

**Comment by HustonMmmavr** [comment]
For backward compatibility we can add query param `config_type` for requests

Something like that: ```http://.../admin/config?config_type={yaml/tar}```

If there is no query param `config_type` at the request, then return old-style config (yaml)

**Comment by RunsFor** [comment]
What about supporting `zip` archives as well?

**Comment by filonenko-mikhail** [comment]
Sorry, no capacity for such feature right now. Much gently closing.
