### ISSUE TITLE
[UI] Ability to show/hide pages 

### ISSUE THREAD

**Issue by olegrok** [tarantool/cartridge#529]
Proposal from @KlonD90 

New endpoint that returns white/black list of pages
```
{
pageVisiblity {
   mode: 'blacklist' | 'whitelist'
   paths [{
     path: '/api/repair',
   }, {
      path: '/cluster/users'
    }]
  }
}

```

**Comment by rosik** [comment]
### RFC 1

Cartridge frontend will set
[menu-filter](https://github.com/tarantool/frontend-core#menufilter),
which is triggered when the page is loaded and upon login/logout.

Every time menu-filter is triggered it performs the GraphQL request:

```graphql
query {
    page_visiblity {mode paths}
}
```

The response looks as follows:

```json
{
    "page_visiblity": {
        "mode": "whitelist"|"blacklist",
        "paths": [
            "/cluster/schema",
            "/cluster/code"
        ]
    }
}
```

In whitelist mode frontend displays only given pages.
In blacklist mode frontend displays all pages except given ones.

To control the page list we'll implement another Cartridge public API:
```lua
cartridge.webui_set_pages_visiblity({
    mode = "whitelist",
    paths = {'/cluster/dashboard'},
})
```

Argument `paths` may be either an array of strings, or a function
(callback, if developer wants to implement more complex logic).

**Comment by rosik** [comment]
### RFC 2

Cartridge frontend will set
[menu-filter](https://github.com/tarantool/frontend-core#menufilter),
which is triggered when the page is loaded and upon login/logout.

Every time menu-filter is triggered it performs the GraphQL request:

```graphql
query {
    webui_capabilities
}
```

The response looks as follows:

```json
{
    "webui_capabilities": [
        "/cluster/dashboard",
        "/cluster/dashboard?edit_topology",
        "/cluster/users",
        "/cluster/users?add_user",
        "/cluster/users?edit_user",
        "/cluster/users?edit_user",
        "/cluster/code",
        "/cluster/schema",
        "/cluster/configuration",
        "..."
    ]
}
```

Depending on capabilities WebUI shows or hides pages and other elements.

To control this list we'll add another Cartridge public API:
```lua
cartridge.webui_capabilities_list()
cartridge.webui_capabilities_add({'/tdg/tasks'})
cartridge.webui_capabilities_remove({'/cluster/schema'})
```

The list of capabilities is constant, but if an application developer
wants to implement more complex logic (e.g. ACL-based), he can
monkeypatch the corresponding graphql handler:

```lua
local webui_caps = require('cartridge.webui.capabilities')
webui_caps.get_capabilities = function()
    if cartridge.http_get_username() == 'admin' then
        return everything
    else
        return nothing
    end
end
```

**Comment by rosik** [comment]
### RFC 3 (blacklist only)

Cartridge frontend will set
[menu-filter](https://github.com/tarantool/frontend-core#menufilter),
which is triggered when the page is loaded and upon login/logout.

Every time menu-filter is triggered it performs the GraphQL request:

```graphql
query {
    webui_blacklist
}
```

The response looks as follows:

```json
{
    "webui_blacklist": [
        "/cluster/dashboard?edit_topology",
        "/cluster/users?add_user",
        "/cluster/users?edit_user",
        "/cluster/users?edit_user",
        "/cluster/code",
        "/cluster/schema",
        "..."
    ]
}
```

Which means that WebUI doesn't provide controls for editing topology and
users, and also hides code and schema pages.

To control this list we'll add another option in `cartridge.cfg`:
```lua
cartridge.cfg({
    webui_blacklist = {
        "/cluster/code",
        "/cluster/schema",
    }
})
```

**Comment by knazarov** [comment]
ok
