### ISSUE TITLE
No way to set DDL schema through lua API

### ISSUE THREAD

**Issue by knazarov** [tarantool/cartridge#536]
Currently there are graphql calls that can set the DDL, but there is no their lua counterpart.
Please expose DDL functionality through cartridge API as with other stuff, like managing topology.

**Comment by rosik** [comment]
Here it is https://www.tarantool.io/en/rocks/cartridge/1.0/modules/cartridge/#g-cartridge-get-schema

**Comment by knazarov** [comment]
This is not suitable, as it is only present as a global function. There should be a function that is exposed through `cartridge.` as well.
