### ISSUE TITLE
Implement cartridge.app_root() 

### ISSUE THREAD

**Issue by knazarov** [tarantool/cartridge#537]
I find myself frequently googling how to figure out current file's directory, in order to load various stuff like project resources, schema, etc. It will be a lot nicer to have a built-in function that tells you the path to current application root directory, like `cartridge.app_root()`

**Comment by rosik** [comment]
Do you mean [debug.sourcedir](https://www.tarantool.io/en/doc/2.3/reference/reference_lua/debug_facilities/#lua-function.debug.sourcedir)? Or [package.searchroot](https://www.tarantool.io/en/doc/2.3/reference/reference_lua/other/#lua-function.package.searchroot)?

I could agree it's a documentation flaw, but I don't think we need another function.

**Comment by filonenko-mikhail** [comment]
I think it's good feature and propose that app_root == cartridge.cfg caller file location

**Comment by rosik** [comment]
Stale. Feel free to reopen.
