### ISSUE TITLE
Describe cartridge error handling gudelines

### ISSUE THREAD

**Issue by rosik** [tarantool/cartridge#542]
How are errors usually reported (in lua/graphql/http/internally)?
How should I check errors returned from cartridge public API?

Short answer:

Cartridge uses https://github.com/tarantool/errors module. Cartridge doesn't throw exceptions (except for two cases: contract violation in function calls, and bugs).

GraphQL errors: see #491 and https://spec.graphql.org/June2018/#sec-Errors

HTTP: [RTFS](https://github.com/tarantool/cartridge/blob/master/cartridge/webui/api-config.lua#L60)

**Comment by rosik** [comment]
Also it would be nice to mention different APIs: GraphQL, Lua, HTTP.

Debt: describe GraphQL error extensions and how they can be specified in error objects.

**Comment by olegrok** [comment]
> Debt: describe GraphQL error extensions and how they can be specified in error objects.

Example: https://github.com/tarantool/cartridge/pull/575/files#diff-cf7848a656b50a8b4ce2cc926bef5205R205

**Comment by rosik** [comment]
Also related: https://github.com/tarantool/errors
