### ISSUE TITLE
Add validate_config, apply_config and init to cartridge.cfg

### ISSUE THREAD

**Issue by knazarov** [tarantool/cartridge#550]
Not everyone needs cluster roles in their code. Sometimes they just want a better version of tarantool management and deployment in different environments.

I propose to allow cartridge to work without roles in simple scenarios. Here's how:

- add validate_config, apply_config and init parameters to cartridge.cfg
- call them as though they belonged to a role (but not show that role in UI)
- make `roles` parameter to cartridge.cfg optional

**Comment by rosik** [comment]
Stale. Feel free to reopen.
