### ISSUE TITLE
Disable the admin UI by default

### ISSUE THREAD

**Issue by knazarov** [tarantool/cartridge#551]
Currently the admin UI is enabled by default. But many users in traditional scenarios may not need it. Let's add a parameter to cartridge.cfg like `admin_gui_enabled` and set it to false by default.

**Comment by opomuc** [comment]
Is `http_enabled` parameter in `cartridge.cfg` what you need?

https://github.com/tarantool/cartridge/blob/14e98a08a84a2506139bf2a093463cf1c08ecbc8/cartridge.lua#L189-L204

**Comment by rosik** [comment]
This feature request is rather popular. Some users want to keep HTTP enabled, but disable the WebUI only.
