### ISSUE TITLE
Make cartridge a good replacement for box.cfg in simple scenarios

### ISSUE THREAD

**Issue by knazarov** [tarantool/cartridge#553]
This is a meta-feature.

Rationale:

Currently there is a high barrier to entry into cartridge for existing tarantool users, who are forced to learn about roles and other stuff, when they may just have a rather simple lua script for their application code. They may not even have tests or a project layout.

What I want to do is to make it easy for current users to just replace box.cfg() with cartridge.cfg() with as little rewrite as possible.

Child issues:

- #552 
- #550 
- #551 
- #554

**Comment by artur-barsegyan** [comment]
> Currently there is a high barrier to entry into cartridge for existing tarantool users
Do you really have that kind of information? Of course, it's a new one, but I don't catch the same opinions.

Yes, it should be a soft move from the plain usage to the framework. Easy and benefits. 
I like it. I think about it the last couple of weeks. I took deeper and thought about the removing `cartridge.cfg` call as is. But we don't have this opportunity without the core support.

**Comment by rosik** [comment]
Stale and obscure. Closing along with #550
