### ISSUE TITLE
Enhance server details dialog

### ISSUE THREAD

**Issue by artur-barsegyan** [tarantool/cartridge#562]
- Clickable server rows
- Single-page server details dialog (??)
- Error message layout in server details dialog (#510)
- Show cartridge version in server details dialog (#489)

**Comment by artur-barsegyan** [comment]
@rosik  What are the arguments to 
> single-page server details dialog

?

What the problem you want to solve?

**Comment by rosik** [comment]
I want this information (server details) to be more reachable and easy to find.

**Comment by rosik** [comment]
This is what a user sees when he clicks on "Server details" today:

![Screenshot from 2020-02-11 12-34-50](https://user-images.githubusercontent.com/2205188/74226580-dabc4680-4ccd-11ea-9b29-fb24fce9302a.png)

And this is the concept of how I want it to look like in future.

![Screenshot from 2020-02-11 12-43-19](https://user-images.githubusercontent.com/2205188/74226644-f6bfe800-4ccd-11ea-89c1-10e3201eb815.png)

I want it to include more info: instance state (e.g. OperationError), error details. And later we'll add here replication warnings.

**Comment by artur-barsegyan** [comment]
Do you have some UX approvements for your concept? Maybe for users more needed feature will be a button for exporting all details to a YAML file or smth?

**Comment by artur-barsegyan** [comment]
Maybe we need to get some inspiration from other cluster UIs...

**Comment by rosik** [comment]
Resolved in #1098
