### ISSUE TITLE
Implement callback to cancel graphql execution if needed

### ISSUE THREAD

**Issue by mtrempoltsev** [tarantool/cartridge#568]
#### My proposal

User code:

```
local function allow_execution(is_mutation, prefix, name, req)
    ...
    return true
end
```

Cartridge:

```
local function set_execution_callback(callback)
    ...
end

local function execute_graphql(req)
    ...
    if execution_permission_callback ~= nil then
        local _, err = execution_permission_callback(...)
        if err ~= nil then
            ...
        end
    ...
end

return {
    ...
    set_execution_callback = set_execution_callback,
    ...
}
```

**Comment by rosik** [comment]
## RFC

We declare new concept - `permission`. Permission is uniquely identified
by its name, and also has a level - 0 (none) / 1 (read-only) / 2 (read-write).
For every user we can compose a map of permissions:

```lua
{
    ['cartridge.users'] = 0,
    ['cartridge.topology'] = 1,
    ['cartridge.config'] = 2,
    ['tdg.jobs'] = 2,
    ...
}
```

Auth backend provides (optionally) an API to answer questions:
* What `permissions` are granted to the current session?
* Is the `permission` granted to the current session?

### Secure graphql API

GraphQL module provides an API to set up relations:
* `{op, prefix, name}` -> `permission`

For example, frontend says: 
```graphql
query {
    cluster {
        schema { as_yaml }
    }
}
```

Backend (GraphQL) algorithm:

- Is permission required for `{op = 'query', prefix = 'cluster', name = 'schema'}`?
- If yes, look if user permission level is enough for performing the request.
- Either proceed or return an error.

### Set up pages visiblity based on permissions

Hiding pages (and UI elements) is based on checking permissions:

```graphql
frontend: query {
    cluster {
        auth_params{
            check_permission('cartridge.topology') // returns number 0/1/2
        }
    }
}
```

### Open questions

* What should the auth backend know about cartridge-level permissions?
* Who is responsible for handling unknown permissions?

**Comment by olegrok** [comment]
Please, separate read access and write access. Cases then user should have write-only access are possible (without read-access)
