### ISSUE TITLE
Describe the clusterwide config concept

### ISSUE THREAD

**Issue by rosik** [tarantool/cartridge#569]
What clusterwide config is? How is it represented? How is it stored? How is it applied? Mention 2pc. How can it be modified (http/graphql/luatest)? Provide API usage examples. 

https://www.tarantool.io/en/doc/2.2/book/cartridge/cartridge_admin/#updating-the-configuration

**Comment by lenkis** [comment]
TODO: config representation on disk/in lua/in dev code/in tests
