### ISSUE TITLE
[1pt] investigation [JS] Proposal: Improve `core.dispatch('cluster:set_welcome_message')` functionality

### ISSUE THREAD

**Issue by iv-ov** [tarantool/cartridge#573]
For now, we can only dispatch a string (or anything appropriate for React render)
`window.tarantool_enterprise_core.dispatch('cluster:set_welcome_message', 'some text')`
and Cartrige frontend will show the checkbox and block login button according to that chackbox.

My proposal: if we will also expect a callback like "validate()", we can control the login button more flexibly, and pass not only static (or "ignorant") text/component, but any interactive elements and to determine any requirements for user.

If `validate()` returns true, the login button is enabled, if false — it's disabled.

Think about what arguments to pass to this function (maybe, entered username and password?)

**Comment by rosik** [comment]
@rgbabaev please close or triage this issue.

**Comment by usenko-timur** [comment]
We can add a new dispatch action and it will work like this:
<img width="648" alt="_" src="https://user-images.githubusercontent.com/88880786/146777889-82d09e7c-13e9-4dc1-957e-849687a7b4ee.png">

https://user-images.githubusercontent.com/88880786/146779142-6ec5c9b1-6a7d-4d58-8760-4df376d7fd76.mov

This will allow you to do anything on this form.
