### ISSUE TITLE
Remove "Configuration files" page

### ISSUE THREAD

**Issue by opomuc** [tarantool/cartridge#583]
Current "Code" page fulfills the role for upload_config. Add "Download" button to that page and "configuration files" is redundant

**Comment by RunsFor** [comment]
In the context of multi-file config, "UPLOAD CONFIGURATION" section becomes obsolete

**Comment by RunsFor** [comment]
> In the context of multi-file config, "UPLOAD CONFIGURATION" section becomes obsolete

Mostly because it still works with one-file config

**Comment by filonenko-mikhail** [comment]
This time I decide that price of such UX feature does not match with real resource situation.
