### ISSUE TITLE
Controlled instance/replicaset maintenance 

### ISSUE THREAD

**Issue by vasiliy-t** [tarantool/cartridge#586]
Scenario: application upgrade 
We have cluster consisting of masters and replicas. There are continuous writes to master.

Upgrade consists of several steps:
1. switch each replicaset master to replica
1. upgrade and restart 'old' masters
1. wait until replication catch up after restart
1. switch masters back
1. upgrade replicas

Masters and replicas must be in sync before performing master switch to ensure clients consumes convergent data. To perform consistent master switch one should be able to temporarily block writes wait until replication catch up and then switch master. I propose to introduce consistent master switch with write block on master via graphql api call.

**Comment by rosik** [comment]
Under development in a separate milestone: https://github.com/tarantool/cartridge/milestone/4
