### ISSUE TITLE
Describe tarantool 1.10->2.x migration process

### ISSUE THREAD

**Issue by rosik** [tarantool/cartridge#587]
Suppose i'm a user, and I have cartridge (scm-1) + tarantool (1.10). How do I upgrade tarantool to 2.x?

Related: https://github.com/tarantool/tarantool/issues/4691

- [ ] Describe the process of migration
- [ ] Choose a place for publishing this information

**Comment by olegrok** [comment]
I think it could be useful - https://github.com/tarantool/cartridge/issues/253#issuecomment-538905814
