### ISSUE TITLE
Show login page in case when /admin/api returns 401 status code

### ISSUE THREAD

**Issue by olegrok** [tarantool/cartridge#592]
I want to use general auth mechanism for my api and cartridge api. Therefore I suggest to make frontend considers 401 HTTP codes and show login page in such cases.

Now it looks:
![image](https://user-images.githubusercontent.com/8830475/74827880-31093500-531f-11ea-8c11-81bc62ea5f83.png)

**Comment by rosik** [comment]
Could you provide more information on reproducing it, please.
I see a banner about networking problems on your screenshot, but I can't get how it's related to authentication. Normally cartridge does show login screen:
![image](https://user-images.githubusercontent.com/2205188/74986230-31eab580-544a-11ea-9ebf-7eec02d46a03.png)

**Comment by olegrok** [comment]
> Could you provide more information on reproducing it, please.

It's not a bug, it's a feature request.

Just monkeypatch http server to return 401 instead of `{"status": 200, "body": "Unauthorized"}`

**Comment by rosik** [comment]
It also seems to be related to #346
