### ISSUE TITLE
Sometimes on_resolve trigger doesn't work

### ISSUE THREAD

**Issue by olegrok** [tarantool/cartridge#594]
Simple piece of code:
```lua
    local _, err = auth.has_access()
    if err ~= nil then
        local err_obj = cartridge_graphql_access_error:new(err)
        err_obj.graphql_extensions = {code = 403, message = 'Unauthorized'}
        error(err_obj)
    end
```

works fine for bootstrap_vshard/auth_params/failover/edit_topology...

But for e.g. join_server returns:
```log
WARNING  root:server.py:295 [{'message': '...s/tdg/.rocks/share/tarantool/cartridge/graphql/rules.lua:69: Scalar values cannot have subselections'}]
```

**Comment by olegrok** [comment]
edit_replicaset, edit_server, expel_server, probe_server affected as well

**Comment by rosik** [comment]
Show me your query. I guess it looks like
`mutation { probe_server(...) {} }`,
while it should be
`mutation { probe_server(...) }` (without excess braces).

**Comment by olegrok** [comment]
Yes, thanks

It helped
