### ISSUE TITLE
[UI] Proposal: auth setup improvements

### ISSUE THREAD

**Issue by rgbabaev** [tarantool/cartridge#598]
I propose to notify user immediately when he tries to enable authorization without logging in.

Current behavior:
User not logged in.
He clicks "Auth" switcher then clicks "Enable" in modal. Only then he gets notification *"You must log in to enable authentication"*.

Proposed behavior:
User not logged in.
He clicks "Auth" switcher and here he gets notification *"You must log in to enable authentication"*.

**Comment by rosik** [comment]
I'm OK with it

**Comment by rosik** [comment]
Closing due to the low demand and I favor of more important issues.
