### ISSUE TITLE
[2pt] Inappropriate error message in WebUI login dialog

### ISSUE THREAD

**Issue by rosik** [tarantool/cartridge#600]
Steps to reproduce:

1. Setup the cluster
1. Log in
1. Enable auth
1. Log out
1. Shut down cluster
1. Try to log in

![image](https://user-images.githubusercontent.com/2205188/75019637-4eb2d780-54a2-11ea-9dbe-b191dc8763cf.png)

**Comment by OlgaYakovleva** [comment]
Verifeid on the branch improve-login-error-message https://github.com/tarantool/cartridge/pull/1607

With steps:
1. Cartridge start
2. Log in with a user
3. Set up "Enable auth"
4. Log out as the user from the step2
5. Cartridge stop
6. Try to log in

Get correct error message: "Cannot connect to server. Please try again later."
