### ISSUE TITLE
Updating custom role code clusterwide

### ISSUE THREAD

**Issue by no1seman** [tarantool/cartridge#601]
Hi,

the documentation is quite clear about how to update the cluster configuration, but I did not find a description of how to update the code with a custom role (both from console and from lua code).
It's not a problem to copy new lua files to all cluster servers, but how to fire Tarantool Cartirdge to reload new code clusterwide?

I mean: 'cartridge reload' (smth like: 'nginx -s reload')

I'm using cartidge 2.0.1 + tarantool  2.3.1 + cartridge-cli 1.4.0

Thanks in advance

**Comment by knazarov** [comment]
We don't yet support reloading the code of cartridge roles. This is not impossible, but needs some special care.

What you can do right now, is to try out https://github.com/tarantool/cartridge-extensions, that's been created with specific need to reload business logic. You can move most of your business logic to extensions, and leave only bare minimum code in your roles that performs initialization.

The logic that allows to push new code to the cluster via API without preparing new packages is already there.

**Comment by knazarov** [comment]
But the idea of reloading all cartridge code from disk with `cartridge reload` looks interesting.

**Comment by no1seman** [comment]
@knazarov,
thank you for quick answer. 

I will look at cartridge-extentions, but 'cartridge reload <app-role-name>| all' wiil be great solution for developing and also for production.

**Comment by rosik** [comment]
Resolved in #1100
