### ISSUE TITLE
Memory usage text layout

### ISSUE THREAD

**Issue by rosik** [tarantool/cartridge#603]
It's misplaced if numbers are big enough

![image](https://user-images.githubusercontent.com/2205188/75244635-319d4200-57dd-11ea-8cf8-6d4e616d6ef5.png)

**Comment by mnpotetyuev** [comment]
The solution is to expand the width of the indicator to 220 pt

<img width="969" alt="Снимок экрана 2020-03-06 в 17 16 21" src="https://user-images.githubusercontent.com/61145957/76091563-de8e7080-5fce-11ea-8ed9-f227afe59e15.png">
