### ISSUE TITLE
Humanize fatal errors in WebUI

### ISSUE THREAD

**Issue by rosik** [tarantool/cartridge#634]
Sometime there may be backend problems (most likely bugs) which result in the following picture:

![image](https://user-images.githubusercontent.com/2205188/75898708-811de680-5e4b-11ea-8d45-4786a662497f.png)

@mtrempoltsev proposes to make it neater.

P.S.

To simulate this behavior it's one can modify `cartridge/graphql.lua`:

```diff
diff --git a/cartridge/graphql.lua b/cartridge/graphql.lua
index 60b167f..95a358f 100755
--- a/cartridge/graphql.lua
+++ b/cartridge/graphql.lua
@@ -223,6 +223,12 @@ local function http_finalize(obj)
 end
 
 local function _execute_graphql(req)
+    do
+        return http_finalize({
+            errors = {{message = "Artificial error"}},
+        })
+    end
+
     if not auth.authorize_request(req) then
         return http_finalize({
             errors = {{message = "Unauthorized"}},

```

**Comment by olegrok** [comment]
There is a way to demonstrate an error without any injections:
* Open webui in browser
* Stop server

Result:
![image](https://user-images.githubusercontent.com/8830475/76943073-d1974880-690f-11ea-9015-048a23f861ca.png)

**Comment by rgbabaev** [comment]
To show this error, use https://tarantool.github.io/front-ui-kit/#!/NonIdealState

**Comment by mnpotetyuev** [comment]
![1_1](https://user-images.githubusercontent.com/61145957/77073646-a4769300-6a00-11ea-8c13-f562abd11d3b.png)
![1_2](https://user-images.githubusercontent.com/61145957/77073652-a6d8ed00-6a00-11ea-94ef-6a178733a803.png)
![2_1](https://user-images.githubusercontent.com/61145957/77073656-a7718380-6a00-11ea-80a7-b38a84a4f967.png)
![3_1](https://user-images.githubusercontent.com/61145957/77073659-a80a1a00-6a00-11ea-8b75-0a585242e350.png)

**Comment by iv-ov** [comment]
Designs are here https://www.figma.com/file/hG6R4cB8WP1jeheyEK2iKN/TT%3A-Cartridge?node-id=3398%3A0
