### ISSUE TITLE
Misleading UX at Cluster page

### ISSUE THREAD

**Issue by artur-barsegyan** [tarantool/cartridge#635]
**The problem:** why I can't configure any other instances besides the first one? I understand that no difference between them in this case, but I had a strange feeling at first sec.

![The GUI](https://user-images.githubusercontent.com/11336358/75918028-0913e880-5e6c-11ea-969a-5bbaa22d1c2e.png)

**Probably solution:** any instance should have the own button.

**Comment by rosik** [comment]
Even if you could bootstrap the other instance you're still unable to control it. The instance you're looking at isn't bootstrapped - it doesn't have clusterwide configuration, there is no subject to edit.

**Comment by artur-barsegyan** [comment]
Technically, it's not possible now. But I think that #431 can help a user to understand what's going on.
