### ISSUE TITLE
"You are here" marker in webui 

### ISSUE THREAD

**Issue by mnpotetyuev** [tarantool/cartridge#641]
<img width="477" alt="Снимок экрана 2020-03-05 в 19 27 44" src="https://user-images.githubusercontent.com/61145957/76085353-ea743580-5fc2-11ea-9808-b7976eadd0f2.png">
<img width="603" alt="Снимок экрана 2020-03-06 в 10 05 57" src="https://user-images.githubusercontent.com/61145957/76085355-eba56280-5fc2-11ea-8a09-2ff0fa68a566.png">

https://github.com/tarantool/cartridge/issues/431

**Comment by rosik** [comment]
Keep tracking #431
