### ISSUE TITLE
Indicate replication problems in WebUI

### ISSUE THREAD

**Issue by mnpotetyuev** [tarantool/cartridge#642]
https://github.com/tarantool/cartridge/issues/289

![75763754-ceb42980-5d4d-11ea-9325-511137d7004f](https://user-images.githubusercontent.com/61145957/76086201-ae41d480-5fc4-11ea-89c4-2562c6456333.png)
![Uploading 75763755-cfe55680-5d4d-11ea-9137-268cd977552b.png…]()

**Comment by rosik** [comment]
Keep tracking #289
