### ISSUE TITLE
Support 2FA

### ISSUE THREAD

**Issue by olegrok** [tarantool/cartridge#657]
It would be nice to extend current "check_password" implementation and support 2FA based on TOTP (https://en.wikipedia.org/wiki/Time-based_One-time_Password_algorithm)

Seems that we should extend our current `check_password` implementation from:
`check_password(login, password)` to `check_password(login, password, code)` - where code - is a "TOTP value".

The proposed flow is following:
* check_password accept 3 args and user could return following structure: `{ state = 'allowed/prohibited/continue', reason = 'smth' }` where 'allowed' is an equivalent of "true", 'prohibited' - "false" and "continue" means "check TOTP value"
* If check password returns "continue" it calls a new callback that accept TOTP value (generated by cartridge) and could sends it for the user e.g. via email or sms.
* User makes additional request to `/login` with {"username": '...', "password": '...', "code": "..."}.
* If "code" is correct TOTP value we should authorize this user and returns "Unauthorized" otherwise.

**Comment by rosik** [comment]
Not demanded anymore
