### ISSUE TITLE
Redesign membership payload dissemination

### ISSUE THREAD

**Issue by rosik** [tarantool/cartridge#660]
Membership payload was designed to carry useful information, but it's size is limited by UDP packet size (1472). The more data cartridge puts there - the less free space is left for anti-entropy sync messages. So it slows down state propagation and negatively affect gossip dissemination.

We should think up another way for payload propagation.
It may be an intermediate layer between cartridge and membersip, but I believe it shouldn't be UDP.

**Comment by rosik** [comment]
We've brainstormed it a little.

Membership payload is used in many places

* eventual failover (uuid, state) - every instance
* stateful failover (uuid, state) - coordinator only 
* issues (alias) - every instance
* get_topology (uuid, state, alias) - single instance
* lua-api.proxy (uuid) - single instance
* rpc.healthcheck (uuid, state) - every instance 
* topology.refine_servers_uri (uuid) - every instance
* suggestions (state) - single instance

The most tricky usecases are `rpc` and `refine_servers_uri`. They need this information on every instance. Without UDP payload dissemination it would require setting up tcp full mesh (which is expensive).

Also the `cartridge.remote-control` module doesn't support `box.session.push`.

AFAICS this issue has no solution for today.

**Comment by filonenko-mikhail** [comment]
Still dead end today. Feel free to reopen kindly.
