### ISSUE TITLE
Edit failover params in WebUI

### ISSUE THREAD

**Issue by rosik** [tarantool/cartridge#666]
Failover configuration is changed in #604. Soon we'll have three modes disabled / eventual / stateful instead of boolean true/false. These changes should be adopted in WebUI - a user should be able to edit all these params.

Related to #651

**Comment by mnpotetyuev** [comment]
v1
<img width="1364" alt="Снимок экрана 2020-03-20 в 11 44 08" src="https://user-images.githubusercontent.com/61145957/77148218-2bc71380-6aa0-11ea-8964-072b8385caed.png">
v2
<img width="1440" alt="Снимок экрана 2020-03-20 в 11 44 21" src="https://user-images.githubusercontent.com/61145957/77148229-2ec20400-6aa0-11ea-8f78-495a88a93cd2.png">

**Comment by KlonD90** [comment]
Could we add some more info about what the difference between in interface?
