### ISSUE TITLE
Fix empty replicaset list during config comparison

### ISSUE THREAD

**Issue by sharonovd** [tarantool/cartridge#71]
In GitLab by @rosik on Mar 22, 2019, 03:29

Steps to reproduce:

1. Assemble a cluster of 2 or more instances
2. Stop all instances
3. Start only one
4. Open WebUI and watch an empty page

**Comment by sharonovd** [comment]
In GitLab by @filonenko-mikhail on May 14, 2019, 12:19

Reproduced

**Comment by rosik** [comment]
Related to #293

**Comment by rosik** [comment]
It's already fixed, but we should check that it's covered with a test
