### ISSUE TITLE
Make stateboard.lua self-sufficient

### ISSUE THREAD

**Issue by olegrok** [tarantool/cartridge#711]
Currently stateboard.lua depends on cartridge argparse. But since it an external storage that knows nothing about cartridge it would be great to remove such dependency and allow to copy and run only stateboard.lua as self-sufficient executable file.

One possible solution is to reuse cartridge-cli build script (https://github.com/tarantool/cartridge-cli/blob/master/compile_executable.lua) that allows to copy the whole cartridge/argparse.lua file at build time in stateboard.lua and use it then without any dependencies.

**Comment by RunsFor** [comment]
Why not extract `argparse` into a rock, so `kingdom` only depends on it.

**Comment by olegrok** [comment]
Because we want to ship single executable file and untie from any dependencies. Your variant is closer to "move kingdom to separate rock".

**Comment by olegrok** [comment]
I think it's no longer relevant
