### ISSUE TITLE
Add fullname field to graphql authParams

### ISSUE THREAD

**Issue by mtrempoltsev** [tarantool/cartridge#726]
We need to show username (like Tom Chase) instead of username (in cartridge it is email) so I propose to add the fullname field into graphql request. This field we can set to value that the get_user callback returns.

**Comment by olegrok** [comment]
My proposal is to add new callback "get_fullname". As cartridge users have this property: 
https://github.com/tarantool/cartridge/blob/0b97f1f0ea2506d83b76a9f043a49b53eabff28b/cartridge/auth.lua#L399

And show `fullname` (if it was specified) in UI and `username` otherwise.

**Comment by rosik** [comment]
I've got another proposal:

Here is the code that returns username, which in turn is displayed on frontend:

https://github.com/tarantool/cartridge/blob/0b97f1f0ea2506d83b76a9f043a49b53eabff28b/cartridge/webui/api-auth.lua#L75-L80

Let's change it as follows:

```lua
local username = auth.get_session_username()
local user = auth.get_user(username)

return {
    username = user.fullname or username
}
```
