### ISSUE TITLE
☂️ [RFC] Consistent leader promotion

### ISSUE THREAD

**Issue by rosik** [tarantool/cartridge#749]
## Problem statement

Manual leader switching is still asynchronous even in stateful failover mode. Instances fetch appointments by longpolling state provider. So a new leader can become writable before the old one becomes read-only. Since Tarantool doesn't implement synchronous replication it may result in replication conflicts in some cases.

## RFC

Консистентный свичовер не зависит от режима фейловера. Это две ортогональные фичи, хотя обе они используют внешний координатор. С появлением консистентного свичовера к фейловеру можно относиться как к неконсистентному автоматическому промоуту.

При консистентном свичовере каждый инстанс защищается от преждевременного перехода в состояние rw. Инстанс, который вправе вести запись мы будем называть [vclockkeeper](https://en.wikipedia.org/wiki/Clockkeeper) (люблю каламбур, см. также https://hanakokun.fandom.com/wiki/No.1_The_Clock_Keepers).

Для этого используется тот же самый внешний стейт провайдер. В нём хранятся записи вида `replicaset_uuid, instance_uuid, vclock`.

После назначения инстанса новым лидером, он выполняет `wait_lsn` относительно vclockkeeper. Когда у него получится, он перезаписывает себя в качестве нового vclockkeeper. Реально переход в rw происходит только после синхронизации и после успешной записи текущего vclock во внешнее хранилище.

Vclock в данном описании нужен больше для аудита, чем для чего-либо ещё. Конкретные значения lsn в вычислениях не участвуют.

Если во внешнем хранилище отсутствует информация о vclock, то wait_lsn не выполняется, любой лидер при желании может взять лидерство неконсистентно.

При срабатывании фейловера координатор самостоятельно записывает vclock назначаемого инстанса.

### FAQ

Q: В каких случаях консистентный свичовер может обломаться? И какие будут последствия?
A: В disabled режиме новый лидер может не успеть догнать старого, если старый лидер упадёт вскоре после переключения. Тогда мы останемся без лидера. Дальше мы либо починим старого лидера, либо придётся его дизейблить / экспелить.

Q: А если фейловер включён?
A: В stateful режиме преждевременная смерть старого лидера приведёт к срабатыванию настоящего фейловера, неконсистентного. Ожидание lsnов оборвётся и новый лидер принудительно перейдёт в rw.

Q: Ну а как работает консистентный промоут с eventual фейловером?
A: Как-то средне. Если приоритет лидеров меняется с двухфазным комитом, то инстанс попытается дождаться lsn. Но eventual фейловер очень капризный. Любое срабатывание фейловера прервёт ожидание и переключение произойдёт неконсистентно.

Q: А что, если ожидание lsn займёт слишком много времени? Например если репликация сдохла?
A: Это жопа независимо от того включен консистентный промоут или нет. Новый лидер попробует дождаться синка, у него не получится. В таком случае можно либо переключить лидера обратно и попытаться починить репликацию, либо смириться с неконсистентностью и заказать лубрикант.

### Вопросы для обсуждения

1. Сейчас уже есть ручной промоут при стейтфул феловере (на сегодняшний день неконсистентный, очевидно). Должен ли он стать консистентным или у нас должен остаться выбор?

1. В комбинации с eventual фейловером внешнее хранилище становится новой точкой отказа. Запись vclock'ов будет только мешать фейловеру, который и так хрупкий. Стоит ли забанить эту комбинацию?

### Идеи на будущее

1. С данной архитектурой у нас есть возможность реализовать ещё один режим фейловера: ручной. От стейтфула он будет отличаться только тем, что никакие решения не будут приниматься автоматически (кроме первого назначения лидеров, пожалуй). Зато переключить лидеров можно будет даже при отсутствии кворума, при условии что координатор жив.

1. При текущей реализации ручное переключение лидера возможно только при наличии активного координатора. От этого ограничения не сложно избавиться, если оно кому-то мешает. Инстанс с вебмордой может сам захватить лок, запромоутить кого надо и тут же отпустить.

1. На сегодняшний день форматирование стейтборда сопряжено с переключением лидера на первого по приоритету, даже если в стейтборде хранилось другое значение. Даже если мы реализуем сейчас консистентное переключение лидеров, данный кейс всё равно останется неконсистентным. Мы можем это исправить и перепроверять состояние всех инстансов даже после форматирования стейтборда.

**Comment by rosik** [comment]
## RFC (v1)

Консистентный свичовер не зависит от режима фейловера. Это две
ортогональные фичи, хотя обе они используют внешний координатор.
С появлением консистентного свичовера к фейловеру можно относиться как
к неконсистентному автоматическому промоуту.

При консистентном свичовере каждый инстанс защищается от
преждевременного перехода в состояние rw. Инстанс, который вправе вести
запись мы будем называть [vclockkeeper](https://en.wikipedia.org/wiki/Clockkeeper)
(люблю каламбур, см. также https://hanakokun.fandom.com/wiki/No.1_The_Clock_Keepers).

Для этого используется тот же самый внешний стейт провайдер. В нём
хранятся записи вида `replicaset_uuid, instance_uuid, vclock`.

После назначения инстанса новым лидером, он выполняет `wait_lsn`
относительно vclockkeeper. Когда у него получится, он перезаписывает
себя в качестве нового vclockkeeper. Реально переход в rw происходит
только после синхронизации и после успешной записи текущего vclock во
внешнее хранилище.

Vclock в данном описании нужен больше для аудита, чем для чего-либо ещё.
КОнкретные значения lsn в вычислениях не участвуют.

Если во внешнем хранилище отсутствует информация о vclock,
то wait_lsn не выполняется, любой лидер при желании может взять
лидерство неконсистентно.

При срабатывании фейловера координатор самостоятельно записывает vclock
назначаемого инстанса.

### FAQ

Q: В каких случаях консистентный свичовер может обломаться? И какие
   будут последствия?
A: В disabled режиме новый лидер может не успеть догнать старого, если
   старый лидер упадёт вскоре после переключения. Тогда мы останемся
   без лидера. Дальше мы либо починим старого лидера, либо придётся его
   дизейблить / экспелить.

Q: А если фейловер включён?
A: В stateful режиме преждевременная смерть старого лидера приведёт к
   срабатыванию настоящего фейловера, неконсистентного. Ожидание lsnов
   оборвётся и новый лидер принудительно перейдёт в rw.

Q: Ну а как работает консистентный промоут с eventual фейловером?
A: Как-то средне. Если приоритет лидеров меняется с двухфазным комитом,
   то инстанс попытается дождаться lsn. Но eventual фейловер очень
   капризный. Любое срабатывание фейловера прервёт ожидание.

Q: А что, если ожидание lsn займёт слишком много времени? Например
   если репликация сдохла?
A: Это жопа независимо от того включен консистентный промоут или нет.
   Новый лидер попробует дождаться синка, у него не получится. В таком
   случае можно либо переключить лидера обратно и попытаться починить
   репликацию, либо смириться с неконсистентностью и заказать лубрикант.

### Вопросы для обсуждения

1. Сейчас уже есть ручной промоут при стейтфул феловере (на сегодняшний
   день неконсистентный, очевидно). Должен ли он стать консистентным или
   у нас должен остаться выбор?

Идеи на будущее:

1. С данной архитектурой у нас есть возможность реализовать ещё один
   режим фейловера: ручной. От стейтфула он будет отличаться только тем,
   что никакие решения не будут приниматься автоматически (кроме первого
   назначения лидеров, пожалуй). Зато переключить лидеров можно будет
   даже при отсутствии кворума, при условии что координатор жив.

1. При текущей реализации ручное переключение лидера возможно только при
   наличии активного координатора. От этого ограничения не сложно
   избавиться, если оно кому-то мешает. Инстанс с вебмордой может сам
   захватить лок, запромоутить кого надо и тут же отпустить.

1. На сегодняшний день форматирование стейтборда сопряжено с
   переключением лидера на первого по приоритету, даже если в стейтборде
   хранилось другое значение. Даже если мы реализуем сейчас консистентное
   переключение лидеров, данный кейс всё равно останется неконсистентным.
   Мы можем это исправить и перепроверять состояние всех инстансов даже
   после форматирования стейтборда.

**Comment by knazarov** [comment]
Даже в ситуации когда тарантул будет иметь синхронную репликацию, он будет "уязвим" к ситуации когда есть несколько мастеров, принимающих транзакции на запись. Так что такой же механизм будет нужен и для "синхрона".

**Comment by R-omk** [comment]
По мне так везде нужномаксимально стремиться к консистентному свичоверу,  хоть при ручном переключении хоть при каком.  Если проподает координатор,  то пусть все быстренько на всякий случай переходят в ro, во всяком случе чтобы точно небыло такого что ктото захотел стать мастером не дождавшись что  старый мастер точно отвалился.

Кроме того я думаю такая фича как надежная стейт машина записывающая все истории переключения мастеров не будет лишней, тоесть чтобы каждый мастер у себя в транзакциях мог извлечь "генерацию мастера" и приложить при необходимости к своим данным в транзакции. Это может как нибудь помочь при разруливании конфликтов. 

"Генерация мастера" может вестись только в raft , поэтому просто eventual фейловер не  сможет такое.  В любом случае, чем  однозначней стейт машина  тем меньше возможно проблем в распределенной системе.

Далее, чтоможно сделать если крайне желателен консистентный свичовер, а узел неотвечает.

Насчет случаев когда старый мастер потерялся и мы не знаем что с ним (gossip от него не приходит):  нужно договориться о каком то относительно большом t_max таймауте, (например 20-60 секунд), при этом старый мастер если потерял кворум должен:
-   через короткое время t_min ( например 2 -  15 с)   быстро стать ro чтобы не натровить бед, ( при этом клиенты сами себе обеспечивают подобие синхронной репликации путем простого wait_lsn)
-  через среднее время t_mid (15- 40 секунд )  самоизолироваться, а именно не дать своим неподтвержденным wal логам уехать на реплику, для этого он пишет себе на диск флаг о том что данные снапшота и wal нужно временно спрятать при следующем запуске. И делает os.exit(). Если его платформа поднимеет (systemd, k8s )  то узел не сможет  своми wal запороть возможно уже новые данные на другом мастере и при этом сможет с него восстановиться  или самому  вновь  стать мастером если координатор разрешит.

-  через время t_max   если старый мастер не подтвердил что он жив координатор может назначать нового мастера, поскольку мы занем что через  t_max секунд старый мастер точно сложился чтобы не произошло.

t_max > t_mid > t_min

Это что то типа fencing  основанного на таймаутах, если координатору доступен какойто другой режим fencing (например аппаратное отключение питания)  то можно не ждать  t_max, а уже через t_mid смело гасить узел и назначать нового мастера.

Еще возможен мануальный fencing, допустим в платформе есть свой механизм fencing,   тогда можно просто позвать api координатора и он произведет не консистентный свичовер.
Собственно способы описанные выше это как автоматические  модули к мануальному fencing, просто fencing на таймаутах лучше сразу брать на борт.

**Comment by sergos** [comment]
Я вижу обсуждение как попытку реализовать замену алгоритма выбора лидера. 
Если такой алгоритм - естественно, как автоматический, так и с возможностью мануальной интервенции - будет поддержан в синхронной репликации, это решит поставленную задачу?

**Comment by knazarov** [comment]
@sergos это не решит проблему для асинхронной репликации
