### ISSUE TITLE
Hanging warning message 'Instance is not in config' when configuring a new cluster

### ISSUE THREAD

**Issue by sharonovd** [tarantool/cartridge#75]
In GitLab by @opomuc on Mar 25, 2019, 19:23

Start some instances and create cluster in some part of them. Next, go to admin interface one of the left ones and create a cluster there. New replicaset will answer requests and config manipulations do work, but warning message still stands

![image](/uploads/09595745523d5fe7b65ae09f38393ac6/image.png)

**Comment by sharonovd** [comment]
In GitLab by @opomuc on Mar 25, 2019, 19:24

changed the description

**Comment by rosik** [comment]
Related to #293

**Comment by rosik** [comment]
Irrelevant since 2.0.0
