### ISSUE TITLE
Implement a module for managing the current instance status

### ISSUE THREAD

**Issue by sharonovd** [tarantool/cartridge#76]
In GitLab by @rosik on Mar 26, 2019, 15:58

We usually discuss scenarios like "degraded instance" and how to repair it manually, but this logic is spread all over the cluster code. Our ubiquitous language includes terms which are not reflected in project.

I guess we should gather this logic in a single module.

**Comment by sharonovd** [comment]
In GitLab by @rosik on Apr 4, 2019, 14:35

marked this issue as related to #37

**Comment by sharonovd** [comment]
In GitLab by @rosik on Apr 4, 2019, 14:36

marked this issue as related to #32

**Comment by sharonovd** [comment]
In GitLab by @sharonovd on Jul 4, 2019, 14:25

removed milestone

**Comment by rosik** [comment]
Implemented in #331
