### ISSUE TITLE
ConnectingFullmesh probably hangs tarantool

### ISSUE THREAD

**Issue by olegrok** [tarantool/cartridge#764]
In my tests I try to terminate an instance with SIGINT but it hangs sometimes.

I can connect to it, it doesn't consume 100% of CPU and last message that I see in logs:
```
WARNING  localhost:11003:server.py:40 2020-04-09 19:34:58.251 [83605] main/113/lua I> Instance state changed: ConnectingFullmesh -> ConnectingFullmesh
WARNING  localhost:11003:server.py:40 2020-04-09 19:34:58.251 [83605] main/113/lua confapplier.lua:498 W> Replication setup failed, instance orphaned
```

Seems that infinite loop [here](https://github.com/tarantool/cartridge/blob/3b16e44607d8ebb36406b263b7ccb440fc95e243/cartridge/confapplier.lua#L509) doesn't allow to do it.

**Comment by rosik** [comment]
I can't see how it's possible. Since connection remains alive, could you collect more info? Like `fiber.top`, for example. Does the first `kill -SIGINT` succeed (i.e. do you check it's return status)? Or the second manual attempt?

**Comment by olegrok** [comment]
It's only hypothesis, I'll try to investigate a problem deeper.

fiber.top doesn't contain anything interesting. process.send_signal doesn't return nothing. It's really looks like instance doesn't receive a signal - after the second attempts my instance successfully stops.

**Comment by olegrok** [comment]
My bad. Seems I tried to stop instance that haven't started yet.
