### ISSUE TITLE
Compact server list in WebUI

### ISSUE THREAD

**Issue by rosik** [tarantool/cartridge#767]
Idea from @printercu to discuss: implement compact servers list 

> а были уже идеи сделать компактный вид страницы кластера?
табличка, где 1 строка на серв, репликасет - строка разделитель. в стиле обычных не хипстерских админок

**Comment by rosik** [comment]
The issue is stuck due to retirement of @mnpotetyuev

Here's an intermediate version:

![image](https://user-images.githubusercontent.com/2205188/86032876-b379d200-ba40-11ea-9a8d-6fdba2f854ea.png)

**Comment by rosik** [comment]
Under development in https://github.com/tarantool/ux_ui/issues/8

**Comment by yngvar-antonsson** [comment]
Closed in favor of https://github.com/tarantool/cartridge/issues/1390
