### ISSUE TITLE
Replicasets/Servers filters enhancement

### ISSUE THREAD

**Issue by KlonD90** [tarantool/cartridge#775]
We add 2 additional filters like at github issues filters to replicasets filters:
* Role filters: show all available roles
* Statuses: unhealthy(include all unhealthy statuses), unconfigured, healthy, warning, error, unreachable, not found

These filters should be accessible by users near the filter input.

We save previous behaviour with tags like a click proceed to filter all replicasets with servers with that tags.

You could choose any combination of these filters like any count roles and any statuses and any tags. That should work like logical AND combinations.

All filters should be visible by search string.

When we work with filters we should add more feedback for user when he activated any of these filters. Now it's not obvious that it affect search string.

Basic search should find the same thing exclude roles and statuses, tags.

**Comment by rosik** [comment]
Resolved in #846
