### ISSUE TITLE
Add metrics into Cartridge

### ISSUE THREAD

**Issue by artur-barsegyan** [tarantool/cartridge#803]
We want to have a standard way to push the default set of metrics to the client. We can add `metrics` like a dependency in Cartridge and also pass some default Cartridge metrics.

**Comment by olegrok** [comment]
Please describe a set of metrics that you want to see in cartridge?

I don't see any serious reasons to collect third party dependencies inside cartridge.
If user wants to use metrics - it could simply install this module.
I hope we shouldn't impose anything if it's not really important.

**Comment by rosik** [comment]
Please, refer to https://github.com/tarantool/metrics (it provides cartridge role since 0.3.0)
