### ISSUE TITLE
Implement the Sharding API

### ISSUE THREAD

**Issue by artur-barsegyan** [tarantool/cartridge#804]
At now we have an API proposal about the new generalized Sharding API [at here](https://github.com/dimoffon/vshard-cluster-api).

We need to implement it. Firstly, for internal Mail.Ru customers. 

**For PoF I suggest starting from:**
- CRUD operations
- register/call functions

**Comment by rosik** [comment]
Resolved in the [crud](https://github.com/tarantool/crud/) module
