### ISSUE TITLE
Performance test

### ISSUE THREAD

**Issue by olegrok** [tarantool/cartridge#806]
Sometimes our customers ask us about cartridge performance. And it should be useful to compare access time to data via iproto, http and graphql.

Also it could be useful for several reasons:
- We could check performance increase/degradation for different cartridge or tarantool version;
- We will have snippets for our customers/users that could write their own performance tests;
- It could be also useful to inspect the impact of cartridge as abstraction over vshard and pure tarantool.

**Comment by rosik** [comment]
I don't get it, what do you want to compare. As you know, cartridge adds nothing over vshard APIs. I think this issue should be moved somewhere else.

**Comment by olegrok** [comment]
Vshard has appropriate task https://github.com/tarantool/vshard/issues/224

But it's not about vshard. Cartridge has its own abstractions over iproto (rpc_calls), https/graphql parsers, handlers, etc.
So, my main idea was to implement such benchmarks. But ok, feel free to close this issue.
