### ISSUE TITLE
Access Token Management And WorkFlow

### ISSUE THREAD

**Issue by sharonovd** [tarantool/cartridge#81]
In GitLab by @filonenko-mikhail on Apr 16, 2019, 13:22

# Motivation

There are third-party systems that have to be authorised while accessing cluster and built app server api.

# Task

Token Structure:
  - name (user defines name as  Application Name, or thridparty System Name or any other reason)
  - token hash (sha256 or better or the same as user password hashing)
  - created timestamp
  - modified timestamp
  - enabled flag (token access can be paused by admin)
  - hash algorythm (for downloading/uploading feature) 
  - access list (for future, will be used in next cluster releases)
    - entity
    - read/write flags (both possible)

Tokens API:

 - list tokens
 - generate new token (place where user can see text token, right after system save the only hash) 
 - remove token
 - change token name
 - disable/enable token
 - regenerate token (place where user can see text token, right after system save the only hash)
 - download/upload all tokens

# Token Middleware

Get token from request calculates appropriate hash, checks access.

Token source fields:

 - header names `auth-token`
 - query param `auth-token`

# «Вот правки по макету...»

![Token](/uploads/1665c4a22e71f5e60e6475c6ac9dbf94/Token.jpg)

# GraphQL API

## Add token
```
type AccessItem {
  entity: String!,
  type: String!
}

type AccessToken {
    uid: String
    name: String
    token: String
    created_at: number
    modified_at: number
    enabled: boolean
    allowed: [AccessItem]
}

mutation addToken {
    cluster {
        add_token(name: String!, accessList: [AccessItem]) AccessToken
    }
}
```

## List tokens

```
query fetchTokens {
    cluster{
        tokens [AccessToken]
    }
}
```

## Update token

```
type UpdateTokenObject = {
    name: String,
    enabled: Boolean
}

mutation updateToken {
    cluster {
        update_token(uid: String!, updateObj: UpdateTokenObject!) AccessToken
    }
}
```

## Remove token

```
mutation removeToken {
    cluster{
        remove_token(uid: String!) AccessToken
    }
}
```

## Fetch access entities and types

```
query fetchAccessEntities {
    cluster {
        access_rules [AccessItems]
    }
}
```

**Comment by sharonovd** [comment]
In GitLab by @filonenko-mikhail on Apr 16, 2019, 13:23

changed the description

**Comment by sharonovd** [comment]
In GitLab by @filonenko-mikhail on Apr 16, 2019, 13:32

changed the description

**Comment by sharonovd** [comment]
In GitLab by @filonenko-mikhail on Apr 16, 2019, 13:32

changed the description

**Comment by sharonovd** [comment]
In GitLab by @KlonD90 on May 22, 2019, 15:50

changed the description

**Comment by sharonovd** [comment]
In GitLab by @KlonD90 on May 22, 2019, 15:54

changed the description

**Comment by sharonovd** [comment]
In GitLab by @KlonD90 on May 22, 2019, 16:05

changed the description

**Comment by sharonovd** [comment]
In GitLab by @rosik on May 22, 2019, 16:57

What exactly `update` updates? Can token name be updated? access list? does it generate new token?

I think it can be simplified to something like
`update(name:"Application name", enabled?: true)`

**Comment by sharonovd** [comment]
In GitLab by @KlonD90 on May 23, 2019, 06:04

```
type UpdateTokenObject = {
    name: String,
    enabled: Boolean
}
```

It could be renamed or enabled.

**Comment by sharonovd** [comment]
In GitLab by @rosik on May 23, 2019, 12:12

Do you really want to perform renaming and disabling in a single request?

**Comment by sharonovd** [comment]
In GitLab by @rosik on May 23, 2019, 12:13

Also, you need a request to regenerate a token

**Comment by sharonovd** [comment]
In GitLab by @KlonD90 on Jun 11, 2019, 22:28

assigned to @KlonD90

**Comment by sharonovd** [comment]
In GitLab by @KlonD90 on Jun 13, 2019, 13:58

А как его регенерировать?

**Comment by sharonovd** [comment]
In GitLab by @KlonD90 on Jun 13, 2019, 14:25

changed the description

**Comment by sharonovd** [comment]
In GitLab by @rosik on Jun 13, 2019, 14:33

Имеется в виду перегенерировать секретную строку.

**Comment by sharonovd** [comment]
In GitLab by @KlonD90 on Jun 13, 2019, 16:43

То есть новая но с теми же доступами?

**Comment by sharonovd** [comment]
In GitLab by @KlonD90 on Jun 13, 2019, 16:49

Ну вообще не вижу противоречия.
Но можно разнести

**Comment by sharonovd** [comment]
In GitLab by @rosik on Jun 13, 2019, 17:10

Нет, `type AccessToken` как целый агрегат остаётся. Его поле token меняется.

**Comment by sharonovd** [comment]
In GitLab by @rosik on Jun 13, 2019, 17:12

И переименуй это поле в "secret" пока мы не запутались

**Comment by sharonovd** [comment]
In GitLab by @rosik on Jun 13, 2019, 17:12

Конечно разнеси, так не потребуется `UpdateTokenObject`

**Comment by sharonovd** [comment]
In GitLab by @KlonD90 on Jun 18, 2019, 12:49

mentioned in merge request !120

**Comment by rosik** [comment]
Obsolete
