### ISSUE TITLE
Implement a Grafana dashboard  

### ISSUE THREAD

**Issue by artur-barsegyan** [tarantool/cartridge#812]
Any cluster solution needs to have a Grafana dashboard with vital cluster metrics for maintenance purposes.

**Comment by R-omk** [comment]
Related https://github.com/tarantool/cartridge/issues/803  https://github.com/tarantool/cartridge/issues/92

**Comment by rosik** [comment]
Please, refer to https://github.com/tarantool/grafana-dashboard
