### ISSUE TITLE
[1pt] Fix messages in CreateReplicasetForm

### ISSUE THREAD

**Issue by lenkis** [tarantool/cartridge#820]
Please change the message text here: https://github.com/tarantool/cartridge/blob/master/webui/src/components/CreateReplicasetForm.js#L74 and #L75

I suggest this:

```
const vshardTooltipInfo = <span>Group choice is available only if the role "<b>vshard-storage</b> is enabled"</span>;
const allRwTooltipInfo = 'If disabled, only the leader of the replica set is writeable';
```

**Comment by OlgaYakovleva** [comment]
Verified correct messages on Create and Edit replicaset forms
