### ISSUE TITLE
Implement etcd-client to replace stateboard

### ISSUE THREAD

**Issue by rosik** [tarantool/cartridge#826]
It should be covered with unit tests similar to [`stateboard_test.lua`](https://github.com/tarantool/cartridge/blob/2d6a8d864ea94aa7a91d218976ca71e44e76b0c8/test/integration/stateboard_test.lua) with

**Comment by olegrok** [comment]
May be useful - https://github.com/moonlibs/config/blob/master/config/etcd.lua
