### ISSUE TITLE
Cleanup sphinx documentation

### ISSUE THREAD

**Issue by rosik** [tarantool/cartridge#839]
This is a follow-up for #838

- [ ] import tarantool styles
- [x] Convert doc topics to rst
- [ ] Cleanup ToC stucture:
  - [x] readme should be top-level
  - [x] changelog should be top-level
  - [ ] hide internal modules which are necessary for ldoc references only
- [ ] Fix "see also" links in `cartridge.test-helpers`
- [ ] Fix layout: images are sqeezed, text is misplacaed

![image](https://user-images.githubusercontent.com/2205188/81433293-ffa94400-916c-11ea-8caf-5ccc7e7dfb26.png)

**Comment by filonenko-mikhail** [comment]
Need to recalculate our resources to solve this things. Feel free to reopen kindly.
