### ISSUE TITLE
Code reload: RFC

### ISSUE THREAD

**Issue by artur-barsegyan** [tarantool/cartridge#842]
Make an action for manual code reloading. That feature will be helpful for the code updating process.

**Comment by artur-barsegyan** [comment]
# RFC [Draft]

Code-reload в Cartridge позволит перезагружать код в кластере, без перезагрузки инстансов Tarantool.

## Introduction

Перезагрузка кода должна уметь происходить в [следующих состояниях кластера](https://github.com/tarantool/cartridge/blob/2924ef9ee53502aa8716e07c81e52c2ca1e3f237/topics/state-machine.md):

- **BoxConfigured**: инстансы сконфигурированы в топологию. Роли не применены.
- **RolesConfigured**: роли применены и запущены. Переходим в это состояние после любого применения обновления.

### Что не учитывается в этом RFC

- обновление кода с миграцией схемы данных
- возврат на предыдущую версию кода
- прерывание процедуры перезагрущки кода

### Что учитывается

- поддержка релоада кластерных ролей
- выкатка на один инстанc
- выкатка на весь кластер сразу
- выборочная перезагрузка модулей
- верификация кода по хэш-сумме
- перевод мутабельных HTTP эндпоинтов инстанса в 503 статус код

## Code update

Прежде всего, новый код необходимо залить по узлам кластера.

В идеале, стоит сверять код по хэш сумме т.к. в архитектуре Cartridge приложений, на всех узлах должен быть код всех ролей, чтобы в случае отказов подменить ф-сть на живых узлах.

В Cartridge должен быть API для перезагрузки кода. Он должен быть доступен через GraphQL, WebUI и cartridge-cli.

```bash
$ cartridge code-reload make
Start at 18.06.2020 12:20:34 UTC
-- Changing HTTP code response to 503 (Service Unavailable) [OK]
-- Verifying files hash-sum [OK]
-- Stopping current runned roles [OK]
-- Reloading code [OK]
-- Rejoining cluster [OK]
-- Initing roles [OK]
-- HTTP endpoints is available alive.
-- New version of code is 1.3.5-3-g3fd34d is applying

Done
```

### Алгоритм перезагрузки кода на одном инстансе

1. Деплой нового кода администратором на необходимый инстанс
2. Вызов команды релоада: из Web UI, cli итд

    ```bash
    cartrdge code-reload make --limit s1-replica
    ```

TODO: Отсутствие новой роли в кластерном конфиге 

3. Cartridge запускает релоад:
    1. Меняем состояние на **CodeReloading**  на текущем инстансе.  Это позволит отказывать в накатке новой конфигурацию во время перезагрузки кода.
    2. Ставим middleware на HTTP (для всех endpoint ов, кроме иммутабельных: для админки и статуса) с 503 кодом
    3. Если есть запущенные роли, вызываем `on_reload` callback у каждой.
    4. Если есть модули также со своим жизненным циклом, которые были зарегистрированы через API, например:

    ```lua
    cartridge.service_registry.set('memcached`, memcached, { with_lifecycle = true })
    ```

    вызываем у них `destroy()`

    4. начинаем заново загружать все модули

    - грузим **init.lua**: повторный запуск cartridge.cfg должен не ругаться в данном состоянии и уметь принимать новые роли и опции, которые умеют применяться без релоада инстанса
    - обновляем конфиг с новым списком ролей
    - вызываем `init()` у всех ролей заново

### Алгоритм перезагрузки кода на всем кластере

1. Деплой нового кода администратором
2. Вызов команды релоада: из Web UI, cli итд
3. Cartridge запускает релоад:
    1. Меняем состояние на **CodeReloading**
    2. Ставим middleware на HTTP (для всех endpoint ов, кроме иммутабельных: для админки и статуса) с 503 кодом
    3. Раскатываем новый конфиг: в нем хэш сумма новых файлов и команда на перезагрузку.
    4. Если есть запущенные роли, вызываем `on_reload` callback у каждой.
    5. Если есть модули также со своим жизненным циклом, которые были зарегистрированы через API, например:

    ```lua
    cartridge.service_registry.set('memcached`, memcached, { with_lifecycle = true })
    ```

    вызываем у них `destroy()`

    4. начинаем заново загружать все модули

    - грузим **init.lua**: повторный запуск cartridge.cfg должен не ругаться в данном состоянии и уметь принимать новые роли и опции, которые умеют применяться без релоада инстанса
    - обновляем конфиг с новым списком ролей (?)
    - вызываем `init()` у всех ролей заново

### Остановка текущих запущенных ролей

> stop() is the role’s termination function. Implement it if initialization starts a fiber that has to be stopped or does any job that needs to be undone on termination.

**Q: Консистентный вызов метода `stop()` у ролей подразумевает исключение их из конфига? Или можно позвать его оставив роль в конфиге?**

A: Так не получится, потому что консистентность достигается за счет нового конфига, в котором текущая роль уже отключена. При применении обновленного конфига, на стадии `apply_config` , роль останавливается.

**Q: Можно ли обойтись без вызова функции `stop()` у роли?**

A:  Да, но тогда нужно создать другой callback т.к. в нем должны убиваться файберы и выполняться прочая логика. С файберами проблема: даже если на них потеряется ссылка, они все равно продолжат выполняться.

Надо добавить новый callback: `on_reload`. Его вызов будет означать остановку текущей роли без удаления ее из конфига и выполнение других операций, связанных с перезагрузкой кода. Остановка нужна, чтобы убить файберы, которые запустили в init().

### Какие модули оставлять без перезагрузки?

По умолчанию, должна быть категория **system** в которой будут лежать наши экспериментальные/неподдерживаемые для перезагрузки модули. Там будут все модули из Tarantool, например.

Пользователь не сможет вмешиваться в это поведение. Добавлять их нужно будет через специальное Internal API в Cartridge.

Зато пользователь сможет задавать модули, которые нужно перезагрузить через RegExp:

- metrics.*
- vshard.*
- cache_*

**Comment by RunsFor** [comment]
Что такое "модули со своим жизненным циклом"?

**Comment by artur-barsegyan** [comment]
> Что такое "модули со своим жизненным циклом"?

Удалил из RFC. Вообще предполагалось, что помимо ролей у пользователей исторически могут быть собственные модули, у которых:
- будет свое промежуточное состояние, которое нужно будет сохранять между релоадами кода
- у них будут ресурсы, которые необходимо конструировать и удалять в специальном порядке, также при релоаде кода

В итоге решили отказаться от этого, ведь механизм ролей — это и есть те же модули.

**Comment by rosik** [comment]
Resolved in #1105
