### ISSUE TITLE
Add role's api for run box.ctl.on_schema_init

### ISSUE THREAD

**Issue by R-omk** [tarantool/cartridge#857]
on_schema_init should be run before box.cfg{}

Related https://github.com/tarantool/cartridge/issues/116

**Comment by rosik** [comment]
The proper place for calling `on_schema_init` is `init.lua` or roles top level (during require). There's no need for any other API.

**Comment by R-omk** [comment]
> The proper place for calling `on_schema_init` is `init.lua` or roles top level (during require). There's no need for any other API.

Yes it will work, but it will not be part of the role, it will run on all hosts. I assumed that schema migrations and trigger configuration would be as part of the role interface, which is used by the cartridge during the bootstrap phase.

**Comment by rosik** [comment]
Before `box.cfg` you've got no idea what roles would be enabled there. Roles can be enabled at any time, then disabled, then enabled again. If you think you need an `on_schema_init` trigger, you have to set it on all hosts. And when it's run, decide what to do. Cartridge can't decide for you.
