### ISSUE TITLE
Расширить доку по использованию systemctl и instances.yaml

### ISSUE THREAD

**Issue by ksenobait09** [tarantool/cartridge#865]
Неинтуитивно описание с использованием systemctl: 
https://www.tarantool.io/en/doc/1.10/book/cartridge/cartridge_dev/#start-stop-using-systemctl

1) нет описания того, как работа через systemctl взаимодействует с instances.yml, что может принимать, как и запуск через cartridge - [APP_NAME[.INSTANCE_NAME]]
2) куда нужно для этого положить instances.yml я тоже не нашел (в доке искал  по "instances.yml")

**Comment by rosik** [comment]
Спасибо за замечание, учтем.

Параметры и формат конфига описаны тут - https://www.tarantool.io/en/doc/1.10/book/cartridge/cartridge_api/modules/cartridge.argparse/.
И ещё вот тут есть полезные сведения - https://www.tarantool.io/en/doc/1.10/book/cartridge/cartridge_cli/#rpm-and-deb 

Если вкратце, то instances.yml надо класть в `/etc/tarantool/conf.d`. Но называться он может как угодно, не обязательно `instances.yml`. Systemctl выковыривает параметрамы app_name, instance_name из имени юнита, а картридж находит среди всех ямль файлов в `/etc/tarantool/conf.d` секцию со своим именем.

**Comment by ksenobait09** [comment]
Хорошо, спасибо.

Есть еще пару замечаний, но они скорее вкусовщина:

1) Функционал argsparse следует упомянуть как-то в Tarantool Cartridge developer’s guide у Иначе вообще не найдешь эту возможность конфигурирования.

2) Лично я в доке не видел, что все файлы  *.yml читаются из /etc/tarantool/conf.d/, возможно стоит про это тоже явно упомянуть.

**Comment by rosik** [comment]
Файлы читаются из директории, которая передается в переменной окружении TARANTOOL_CFG (либо в аргументах командной строки `--cfg`). Конкретное значение `/etc/tarantool/conf.d/` прописано в systemd юните (если этот юнит генерился cartridge pack). А при запуске через cartridge-cli оно может отличаться, там по дефолту используется `cartridge start --cfg instances.yml`

Но замечание верное и совсем не вкусовщинное, постараемся прояснить.

**Comment by artur-barsegyan** [comment]
> Неинтуитивно описание с использованием systemctl:
> https://www.tarantool.io/en/doc/1.10/book/cartridge/cartridge_dev/#start-stop-using-systemctl
> 
> 1. нет описания того, как работа через systemctl взаимодействует с instances.yml, что может принимать, как и запуск через cartridge - [APP_NAME[.INSTANCE_NAME]]
> 2. куда нужно для этого положить instances.yml я тоже не нашел (в доке искал  по "instances.yml")

Привет! Изменения уже в мастере.
