### ISSUE TITLE
remote-control: vshard router closes connection to rc without attempts to reconnect

### ISSUE THREAD

**Issue by olegrok** [tarantool/cartridge#875]
Symptoms: 
* "Mismatch UUID 00000000-0000-0000-0000-000000000000" in logs (https://github.com/tarantool/vshard/blob/79a4dbfc4229e922cbfe4be259193a7b18dc089d/vshard/replicaset.lua#L70)
* All read-only requests are sent to master

Details:
There is a possibility of raise condition when the first instance doesn't close remote control socket but the second instance is already connected with simple usual net.box.
In our case router's netbox connects storage's remote_control.

One difference between rc and netbox connections is peer_uuid. It's zero UUID for remote control.
Vshard has internal check that replica.uuid is equal to connect.peer_uuid. And in case if it's not true just closes such connection.
Here we get broken sharding.

Proposed solution. Bootstrap cluster without roles and only after that enable roles.

**Comment by rosik** [comment]
See also: https://github.com/tarantool/vshard/issues/241

**Comment by olegrok** [comment]
After https://github.com/tarantool/vshard/commit/92409ac9d167478ed07675faac5fc27b579204df we should upgrade vshard... But at first we have to lobby for the release of a new version of vshard.
