### ISSUE TITLE
Implement cartridge.backup_start() and cartridge.backup_stop()

### ISSUE THREAD

**Issue by knazarov** [tarantool/cartridge#879]
Tarantool has a convenient module that allows you to back up relevant files, called box.backup. When calling `box.backup.start()`, tarantool saves snapshots/xlogs and won't delete them until you call `box.backup.stop()`.  In addition, `box.backup.start()` returns a list of files you need to back up, in order to restore an instance to original state.

Since cartridge has a few additional files/directories that are critical for restoring (e.g. config), we should provide the same functionality as core tarantool. `cartridge.backup_start()` should return what `box.backup.start()` returns, plus its own files, and freeze config modifications until `cartridge.backup_stop()` is called.

**Comment by filonenko-mikhail** [comment]
This time we don't have the high quality user story for this feature. Feel free to reopen kindly.
