### ISSUE TITLE
Revise syntax highlighting in doc

### ISSUE THREAD

**Issue by rosik** [tarantool/cartridge#885]
Syntax highlighting is used improperly in our documentation. Many code blocks contain `shell` format, but mistakenly highlited as `console`. 

https://github.com/tarantool/cartridge/blob/3e9eca5115a27241d0e29ce2fb33e19321daf8d0/rst/cartridge_dev.rst#L1063-L1074

It results in inverse colors and broken 'copy' button on site:

![image](https://user-images.githubusercontent.com/2205188/83875501-dbc32900-a73f-11ea-9cbe-7e6582e83864.png)

![image](https://user-images.githubusercontent.com/2205188/83875384-aa4a5d80-a73f-11ea-8f1b-780571b6e660.png)

"Copy" button puts in buffer only what it thinks is the command, in this case the text:

```text
in application directory
in multi-application environment
```

See also https://github.com/tarantool/doc/issues/1362

But first of all we should stop messing around `shell` and `console`. Here is an example of how github highlghts the same block.

With `bash` sintax (ok):

```bash
# in application directory
cartridge start # starts all instances
cartridge start .router_1 # starts a single instance
```

And with `console` (not ok):

```console
# in application directory
cartridge start # starts all instances
cartridge start .router_1 # starts a single instance
```

And this is how `console` block should be formatted properly (but it makes copy-paste more difficult):
```console
$ # in application directory
$ cartridge start # starts all instances
$ cartridge start .router_1 # starts a single instance
here may come program output
```

**Comment by filonenko-mikhail** [comment]
pr #1636
