### ISSUE TITLE
Display replication health in cluster GUI

### ISSUE THREAD

**Issue by sharonovd** [tarantool/cartridge#90]
In GitLab by @sharonovd on Apr 29, 2019, 11:11

Need to display overall cluster health status, and detailed info for each instance:
- upstream/downstream as colored pictograms (arrows)
- lag(+idle)

Probably it could be put under separate 'Cluster health' tab

**Comment by sharonovd** [comment]
In GitLab by @sharonovd on Apr 29, 2019, 11:12

changed title from **Display replication he{-la-}th in cluster GUI** to **Display replication he{+al+}th in cluster GUI**

**Comment by sharonovd** [comment]
In GitLab by @rosik on Jun 5, 2019, 12:30

assigned to @KlonD90

**Comment by rosik** [comment]
Closing in favor of #289
