### ISSUE TITLE
[2pt] [UI] Need to add validation for etcd2

### ISSUE THREAD

**Issue by Errora** [tarantool/cartridge#900]
**Шаги:**

1. Перейти на страницу Cluster
2. Переключить Failover в режим Stateful
3. Выбрать etcd2 и заполнить поля некорректными данными (например, в таймаут записать букву и т.п.)

**Ожидаемый результат:**

Система ругнется, что такое сохранять нельзя

**Полученный результат:**

Нажать Apply с некорректными данными можно. Сообщений об ошибках нет. При этом значение сбрасывается на дефолтное

**Comment by Errora** [comment]
[https://github.com/tarantool/cartridge/issues/897](url)

**Comment by usenko-timur** [comment]
Данная проблема не повторяется в #1182 1578

**Comment by OlgaYakovleva** [comment]
Verified on the branch new-dashboard
