### ISSUE TITLE
[EPIC] ☂️ Implement manual failover mode

### ISSUE THREAD

**Issue by rosik** [tarantool/cartridge#902]
Nowadays in case of instance death with failover disabled user can't easily edit topology because the quorum is lost. This issue doesn't affect stateful mode, but some users doesn't want to enable failover at all.

As a compromise we could implement new manual failover mode. Like stateful, it'll store appointments in external storage (etcd or stateboard), but no decisions will be made automatically (except the first one).

This idea is partially described in RFC on consistent leader promotion (#749), but in general they're not related and can be implemented independently.

Things to be done:

- [ ] New mode implementation
- [ ] Tests
- [ ] GraphQL API
- [ ] Lua API
- [ ] WebUI integration (new radiobutton)

**Comment by filonenko-mikhail** [comment]
Seems that such feature will be done in raft failover. Feel free to reopen kindly.
