### ISSUE TITLE
Expose default metrics from admin httpd

### ISSUE THREAD

**Issue by sharonovd** [tarantool/cartridge#92]
In GitLab by @sharonovd on Apr 29, 2019, 11:23

Utilize default metrics from `metrics` for the purpose.

That would make operations life easier. The only trick would be to leave them extenadble.

**Comment by sharonovd** [comment]
In GitLab by @sharonovd on May 14, 2019, 15:23

The original idea can be borrowed from https://gitlab.com/tarantool/megafon/cia/merge_requests/41

**Comment by rosik** [comment]
Please, refer to https://github.com/tarantool/metrics (it provides cartridge role since 0.3.0)
