### ISSUE TITLE
[4pt] Describe operational cases

### ISSUE THREAD

**Issue by artur-barsegyan** [tarantool/cartridge#926]
-  [ ] Что делать, если в кластере два или более инстансов упало и пропал кворум?
	Объяснить, что GUI сделан так, чтобы в этом случае пользователь не мог менять конфигурацию и сделать топологию неконсистентной.

	Объяснить, как на текущей версии Cartridge можно выполнить вручную disable необходимых инстансов для восстановления кворума: зайти на инстанс, require('cartridge') итд

- [ ] Изменение IP:Port конфигурации для текущих инстансов в кластере

	Описать, что на текущей версии этого сделать нельзя и предложить workaround для этого с удалением текущего инстанса из конфига с сохранением снепшотов и валов.

- [ ] Описать процедуру удаления репликасета целиком
- [ ] Описать следующие сценарии работы кластера с конфигом
	- Как обновить конфиг на всем кластере?
	- Как обновить конфиг на определенных инстансах и заставить инстанс перечитать конфиг с файловой системы?

- [ ] Описать процедуру переноса части бакетов на другой инстанс
	
	Дать вводные ссылки слова по бакетной модели vshard. Описать, как нужно определять бакеты, которые есть у выбранного инстанса. Научить, как их переносить на другой инстанс и как контролировать и дожидаться процесса завершения.

- [ ] Описать процедуру переноса репликасета с одной машины на другую

	Описать, как остановить текущий репликасет в кластере, поднять новый инстанс на новом IP:Port и указать для этих бакетов новое местоположение. Показать как можно проверить, что все стало нормально и новые бакеты видятся в кластере на новой машине. 

	Описать, в каком состоянии будет находится кластер во время переноса репликасета и что будет, если в этот момент у нас сработает failover или пропадет сеть.

- [ ] Привести примеры потери кворума

**Comment by rosik** [comment]
> Что делать, если в кластере два или более инстансов упало и пропал кворум?
> Изменение IP:Port конфигурации для текущих инстансов в кластере

Сделано в #953

> Описать процедуру удаления репликасета целиком

Уже есть, https://www.tarantool.io/en/doc/2.3/book/cartridge/cartridge_admin/#expelling-instances
Плюс немного дополнено в #953 

> Как обновить конфиг на всем кластере?

Уже есть, https://www.tarantool.io/en/doc/2.3/book/cartridge/cartridge_admin/#updating-the-configuration

> Как обновить конфиг на определенных инстансах и заставить инстанс перечитать конфиг с файловой системы?

Дописали в #953 

> Описать процедуру переноса части бакетов на другой инстанс

Уже есть https://www.tarantool.io/en/doc/2.3/book/cartridge/cartridge_admin/#cartridge-rebalance-data

> Описать процедуру переноса репликасета с одной машины на другую

Комплексный вопрос, сводится к предыдущим пунктам.

> Привести примеры потери кворума

Не доконца понял смысл, но примеры привел в #953

**Comment by rosik** [comment]
Resolved in #953

**Comment by ksenobait09** [comment]
1) Нужно будет не забыть расширить эту доку инструкциями работы через cli
2) "Описать процедуру переноса репликасета с одной машины на другую". Я не совсем понял как он относится к предыдущим пунктам. Что по частям присутсвуют в доке операции, необходимые для переноса кластера? Тогда стоит собрать их в один пункт с сылками и порядком, что нужно сделать.
3) По поводу кворума хотелось следующее: какие могут быть причины потери кворума в кластере? Как понять, что в кластере потерян кворум? На что это будет влиять(какие операции запрещены с кластером, сайдэффекты)?
4) "Описать процедуру удаления репликасета целиком" - в https://www.tarantool.io/en/doc/2.3/book/cartridge/cartridge_admin/#expelling-instances указано только как  удалять инстансы по одному.
