### ISSUE TITLE
[1pt] [UI] User login and password in etcd2 form

### ISSUE THREAD

**Issue by dokshina** [tarantool/cartridge#928]
`etcd2` state provider form contains `username` and `password` fields.
These fields are filled by browser with my Cartridge user username and password.

![image](https://user-images.githubusercontent.com/32142520/86383595-d998af80-bc96-11ea-9c73-87811be3ee0f.png)

**Comment by aShelist** [comment]
It is impossible to solve now, since this problem is caused by the way browsers work. They compare the domain name and offer to fill in the saved variant
