### ISSUE TITLE
[2pt] Add rebalancer_max_sending support for cartridge

### ISSUE THREAD

**Issue by FanskiY** [tarantool/cartridge#934]
To speed up buckets migration to new storage, parallel buckets sending is needed.
Vshard has this option.

**Comment by artur-barsegyan** [comment]
Sound good. Do you want to send PR?

**Comment by FanskiY** [comment]
> Sound good. Do you want to send PR?

no, it's a feature request ;)

**Comment by rosik** [comment]
`discovery_mode` seems to be useful too.
