### ISSUE TITLE
[UI] Settings: the menu doesn't collapse

### ISSUE THREAD

**Issue by Errora** [tarantool/cartridge#939]
**Шаги:**

1. Развернуть меню Settings (или меню Configuration на тдг)
2. Свернуть меню Settings

**Ожидаемый результат:**

При нажатии на Setting меню разворачивается и сворачивается

**Полученный результат:**

При нажатии на Setting меню разворачивается, но не сворачивается

**Comment by rgbabaev** [comment]
Fixed
