### ISSUE TITLE
Make UI dialogs buttons consistent

### ISSUE THREAD

**Issue by sharonovd** [tarantool/cartridge#94]
In GitLab by @rosik on May 6, 2019, 16:56

Here are some examples. Let's unify buttons.

![image](/uploads/f08effd2128c97cbfd1cea9dedfcff07/image.png)

![image](/uploads/98c993ef909557225f2dd335cb5fa2a8/image.png)

![image](/uploads/0e9ee690a8e930fbbf152a53e4ffde74/image.png)

![image](/uploads/accfc882d188b4b2db8d6c11879440fc/image.png)

![image](/uploads/d536eb0af6f2c33dfaa70bf40f9fad40/image.png)

![image](/uploads/c928cb94bafa8f0e1129186751b945bb/image.png)

**Comment by sharonovd** [comment]
In GitLab by @rosik on May 6, 2019, 17:00

changed the description

**Comment by rosik** [comment]
Done in 1.0.0
