### ISSUE TITLE
[2pt] Indicate vshard issues

### ISSUE THREAD

**Issue by rosik** [tarantool/cartridge#941]
Inspired by #875: such problems could be monitored with cartridge [issues feature](https://github.com/tarantool/cartridge/issues/289)

See also #1112

**Comment by sharonovd** [comment]
It would be great to detect e. g. resharding issues (when it's stuck)

**Comment by rosik** [comment]
Closing because of https://github.com/tarantool/cartridge/pull/1528#issuecomment-926658316
