### ISSUE TITLE
Support "=" in argparse

### ISSUE THREAD

**Issue by olegrok** [tarantool/cartridge#948]
Usage of `=` symbol leads to unexpected results.

`./init.lua --http-port 8082 --workdir=dev/output/srv2 --advertise-uri 3302` is parsed into `{"1":"3302","http_port":"8082","app_name":"tdg","workdir=dev\/output\/srv2":"--advertise-uri"}` that leads to non-informative error "Socket bind error: Address already in use" if I have another server that runs at default ports.

**Comment by olegrok** [comment]
@dokshina said that lua cartridge-cli argparse supports it and I think we could steal it.

**Comment by dokshina** [comment]
Yes, there was a simple implementation based on internal argparse.

https://github.com/tarantool/cartridge-cli/blob/cf8f9056936025fc06d5ae52f8a71051ed20651a/cartridge-cli/argparse.lua

Also, there are unit tests

https://github.com/tarantool/cartridge-cli/blob/cf8f9056936025fc06d5ae52f8a71051ed20651a/test/unit/argparse_test.lua

**Comment by filonenko-mikhail** [comment]
Kindly sorry. We have no plans for it because of no users( Feel free to reopen.
