### ISSUE TITLE
Expand `argparse` section of documentation with the `box_opts` reference

### ISSUE THREAD

**Issue by opomuc** [tarantool/cartridge#952]
Expand `argparse` section of documentation with the remark to `box_opts` argument of the `cartridge.cfg` call:

https://www.tarantool.io/en/doc/2.3/book/cartridge/cartridge_api/modules/cartridge.argparse/

`box_opts` have "sane default" value which can be remapped with standard `argparse` functionality. 

https://github.com/tarantool/cartridge/blob/ea202581a045fb1a7675607c6c285e1bc8129604/cartridge.lua#L250-L255

where `_box_opts` is from `argparse`

https://github.com/tarantool/cartridge/blob/ea202581a045fb1a7675607c6c285e1bc8129604/cartridge.lua#L241

**Comment by filonenko-mikhail** [comment]
Sorry no resources for such refactoring.
