### ISSUE TITLE
Add callback to role interface that will be called after config has been applied

### ISSUE THREAD

**Issue by sharonovd** [tarantool/cartridge#96]
In GitLab by @racktear on Apr 18, 2019, 22:37

Currently you have to start all your role's worker fibers in the apply_config callback, which is wrong, because the new config hasn't been propagated across entire cluster yet, so your role can't start actively doing stuff. I propose to add another thing called post_apply_config that will be called exactly after the new config has been applied across the cluster.

It could work like this: after the node has applied its config, it starts to check with everyone else if they have the same config, and when it agrees with everyone, it calls post_apply_config itself. This step should not be coordinated by config applier.

**Comment by sharonovd** [comment]
In GitLab by @rosik on May 8, 2019, 11:04

moved from central#85

**Comment by sharonovd** [comment]
In GitLab by @rosik on May 8, 2019, 13:34

@racktear How should the failover behave? Should we call post_apply_config for failover switching?

My proposal is to use the same coordinator as for patch_clusterwide, but it will make impossible to trigger post_apply_config on failover.

**Comment by sharonovd** [comment]
In GitLab by @racktear on May 8, 2019, 19:56

We can discuss this verbally. I think we should not regard failover as change of configuration. It leads to all sorts of confusions (the one you mention is one example)

We should probably have 2 callbacks for failover: master_step_down, master_step_up. Or something like that.

**Comment by sharonovd** [comment]
In GitLab by @racktear on May 8, 2019, 19:57

The reason why post_apply_config should be able to coordinate itself, is because there is a procedure of cold start, which calls apply_config, but has no coordinator.

**Comment by sharonovd** [comment]
In GitLab by @rosik on May 14, 2019, 12:52

That's a good argument

**Comment by rosik** [comment]
I don't know how to implement it.
