### ISSUE TITLE
Prohibit numerical enum values in graphql

### ISSUE THREAD

**Issue by olegrok** [tarantool/cartridge#988]
Example:

e.g. I declare something like:
```
{
        "name": "QALevel",
        "type": "enum",
        "symbols" : ["zero", "one", "two", "3"]
}
```

Then I should specify value as `QALevel: zero/one/two`. Note that it's not a string it's a literal. If I specify `QALevel: "zero"` I get an error "expected enum got string".
But if I'll fairly specify `QALevel: 3` I'll get an error "enum expected got int". Such behaviour seems buggy but I don't know a ways to patch graphql parser for it (I don't know that Graphql specs say for such case).
But anyway I think it should be prohibited to avoid user confusion.

**Comment by olegrok** [comment]
https://spec.graphql.org/draft/#sec-Enums

```
Result Coercion
GraphQL servers must return one of the defined set of possible values. If a reasonable coercion is not possible they must raise a field error.

Input Coercion
GraphQL has a constant literal to represent enum input values. GraphQL string literals must not be accepted as an enum input and instead raise a query error.

Query variable transport serializations which have a different representation for non‐string symbolic values (for example, EDN) should only allow such values as enum input values. Otherwise, for most transport serializations that do not, strings may be interpreted as the enum input value with the same name.
```

Maybe we really can use any scalar value except of strings.

**Comment by rosik** [comment]
https://github.com/graphql/graphiql/issues/586

**Comment by olegrok** [comment]
> [graphql/graphiql#586](https://github.com/graphql/graphiql/issues/586)

http://spec.graphql.org/draft/#sec-Names

Yes, seems allowed names is quite restricted. And we can't start any names with numbers

**Comment by filonenko-mikhail** [comment]
So, it seems that ticket is irrelevant now. Feel free to reopen.
